// Additive child include inside native_people_directory_finalizer_tests.
// Existing six tests and v1 fixture remain unchanged. Missing successor assets
// are implementation prerequisites, never semantic RED or fake installation.
pub(in super::super) mod native_people_directory_row_lock_tests {
    use super::*;
    use sqlx::Acquire;

    const CORRECTED: [&str; 2] = [
        "b0d8ced14929a0c4ef041dfceb57519c64663cb87f39c1dccf61d61227e2278e",
        "2c69786d88b784ca348725dc85730b9d8be1bc835e1069f64de7b7d3ec6ac80d",
    ];
    const CORRECTIVE_FINALIZER: &str =
        include_str!("../../../../ops/postgres-finalize-native-people-directory-row-lock.sql");
    const CORRECTIVE_CLASSIFIER: &str =
        include_str!("../../../../ops/postgres-native-people-directory-row-lock-custody-state.sql");
    const CORRECTION: &str =
        include_str!("../../../../ops/native-people-directory/input-row-lock-v1.sql");

    fn reviewed_corrective_prerequisites() {
        reviewed_capture();
        assert_eq!(
            hex::encode(Sha256::digest(CORRECTION.as_bytes())),
            "d3c48ec3134fd8f67241f0eb4a19d76b02ab51266821a1a1faec530893f67f79"
        );
        assert_eq!(
            hex::encode(Sha256::digest(CORRECTIVE_FINALIZER.as_bytes())),
            "040652e06b9ae491514898964ff9cd6db03ffe860db3e14dfd9ccf8ea85b221f"
        );
        assert_eq!(
            hex::encode(Sha256::digest(CORRECTIVE_CLASSIFIER.as_bytes())),
            "781cc446ce26525cbad6cd281c66239d1a7366eb9369d914068f39886cad3d6e"
        );
        // Corrected fingerprints were independently captured and byte-reproduced
        // from actual v1 profiles. Exact generated bytes above are proposed by
        // store; their independent source approval is still required before mount.
    }
    async fn corrective_install(tx: &mut Transaction<'_, Postgres>) -> Result<(), sqlx::Error> {
        sqlx::raw_sql("SET LOCAL search_path=pg_catalog,pg_temp; SET LOCAL lock_timeout='1s'; SET LOCAL statement_timeout='120s'").execute(tx.as_mut()).await?;
        sqlx::raw_sql(CORRECTIVE_FINALIZER)
            .execute(tx.as_mut())
            .await?;
        sqlx::raw_sql("SET CONSTRAINTS ALL IMMEDIATE")
            .execute(tx.as_mut())
            .await?;
        Ok(())
    }
    async fn corrective_state(tx: &mut Transaction<'_, Postgres>) -> String {
        sqlx::raw_sql(CLASSIFIER_SESSION)
            .execute(tx.as_mut())
            .await
            .unwrap();
        sqlx::query_scalar(sqlx::AssertSqlSafe(CORRECTIVE_CLASSIFIER))
            .fetch_one(tx.as_mut())
            .await
            .unwrap()
    }
    async fn assert_corrected(
        tx: &mut Transaction<'_, Postgres>,
        variant: usize,
    ) -> (Value, String, Option<bool>) {
        let actual = captured(tx).await;
        assert_eq!(actual.1, CORRECTED[variant]);
        assert_eq!(actual.2, Some(true));
        assert_eq!(
            corrective_state(tx).await,
            "native_people_directory.finalized"
        );
        let historical: String = sqlx::query_scalar(sqlx::AssertSqlSafe(CLASSIFIER))
            .fetch_one(tx.as_mut())
            .await
            .unwrap();
        assert_eq!(
            historical, "native_people_directory.profile_mismatch",
            "historical classifier must not reinterpret corrected ACLs"
        );
        assert_all_relation_locks(tx, &actual.0).await;
        actual
    }
    pub(in super::super::super) async fn configured_row_lock_native_directory_fixture(
        pool: &PgPool,
    ) -> (Fixture, SigningKey, AppState) {
        reviewed_corrective_prerequisites();
        let (mut app, key, held) = configured_native_directory_fixture(pool).await;
        let config = account_browser_config(pool, app._artifacts.root.clone(), &key);
        let result = AssertUnwindSafe(async {
            assert_actual_applied_ledger(pool).await;
            assert_eq!(metadata(pool).await.1, ACTIVE[0]);
            assert_eq!(ready_status(&held).await, StatusCode::OK);
            let before = all_rows(pool).await;
            let mut tx = pool.begin().await.unwrap();
            assert_eq!(
                corrective_state(&mut tx).await,
                "native_people_directory.row_lock_required"
            );
            corrective_install(&mut tx).await.unwrap();
            assert_corrected(&mut tx, 0).await;
            tx.commit().await.unwrap();
            assert_eq!(
                all_rows(pool).await,
                before,
                "correction changed business/history/ledger rows"
            );
            assert_eq!(
                ready_status(&held).await,
                StatusCode::SERVICE_UNAVAILABLE,
                "held predecessor state must fence until fresh composition"
            );
        })
        .catch_unwind()
        .await;
        close_states(&[held], result).await;
        let fresh = AppState::from_config(config)
            .await
            .expect("actual newly verified corrected Directory startup");
        let positive = AssertUnwindSafe(async {
            assert_eq!(ready_status(&fresh).await, StatusCode::OK);
        })
        .catch_unwind()
        .await;
        if positive.is_err() {
            close_states(&[fresh], positive).await;
            unreachable!();
        }
        app.service = build_router(fresh.clone());
        (app, key, fresh)
    }

    #[sqlx::test(migrations = false)]
    async fn row_lock_finalizer_transitions_staged_and_active_both_variants_replays_and_rolls_back(
        pool: PgPool,
    ) {
        reviewed_corrective_prerequisites();
        native_people_codec2_install_probe::prepare_successor_ready_database(&pool).await;
        assert_actual_applied_ledger(&pool).await;
        let baseline = metadata(&pool).await;
        assert_eq!(baseline.1, STAGED[0]);
        let rows = all_rows(&pool).await;
        for variant in 0..2 {
            for from_active in [false, true] {
                let mut tx = pool.begin().await.unwrap();
                let outcome = AssertUnwindSafe(async {
                    if variant == 1 {
                        let absent: bool = sqlx::query_scalar("SELECT NOT EXISTS(SELECT 1 FROM pg_catalog.pg_roles WHERE rolname='console_durability_observer')").fetch_one(tx.as_mut()).await.unwrap();
                        assert!(absent);
                        sqlx::raw_sql(OBSERVER).execute(tx.as_mut()).await.unwrap();
                    }
                    assert_eq!(captured(&mut tx).await.1, STAGED[variant]);
                    if from_active {
                        install(&mut tx).await.unwrap();
                        assert_eq!(captured(&mut tx).await.1, ACTIVE[variant]);
                        assert_eq!(corrective_state(&mut tx).await, "native_people_directory.row_lock_required");
                    } else {
                        assert_eq!(corrective_state(&mut tx).await, "native_people_directory.staged_closed");
                    }
                    corrective_install(&mut tx).await.unwrap();
                    let first = assert_corrected(&mut tx, variant).await;
                    corrective_install(&mut tx).await.unwrap();
                    assert_eq!(assert_corrected(&mut tx, variant).await, first);
                    // Prove no hidden commit/connection hop survives a later failure.
                    let error = sqlx::query("SELECT 1/0").execute(tx.as_mut()).await.unwrap_err();
                    assert_eq!(error.as_database_error().unwrap().code().as_deref(), Some("22012"));
                }).catch_unwind().await;
                tx.rollback().await.unwrap();
                assert_eq!(metadata(&pool).await, baseline);
                assert_eq!(all_rows(&pool).await, rows);
                if let Err(panic) = outcome {
                    std::panic::resume_unwind(panic);
                }
            }
        }
    }

    #[sqlx::test(migrations = false)]
    async fn row_lock_finalizer_commits_restarts_and_preserves_replay_and_predecessor_identity(
        pool: PgPool,
    ) {
        let (app, _key, state) = configured_row_lock_native_directory_fixture(&pool).await;
        let outcome = AssertUnwindSafe(async {
            let original = metadata(&pool).await;
            assert_eq!(original.1, CORRECTED[0]);
            let rows = all_rows(&pool).await;
            let mut tx = pool.begin().await.unwrap();
            corrective_install(&mut tx).await.unwrap();
            assert_eq!(assert_corrected(&mut tx, 0).await, original);
            tx.commit().await.unwrap();
            assert_eq!(metadata(&pool).await, original);
            assert_eq!(all_rows(&pool).await, rows);
            assert_eq!(ready_status(&state).await, StatusCode::OK);
            // Diagnostic rollback only: software downgrade is fenced, never live.
            let mut tx = pool.begin().await.unwrap();
            sqlx::raw_sql("REVOKE UPDATE(command_id) ON public.native_people_inputs_v1 FROM console_account_owner").execute(tx.as_mut()).await.unwrap();
            assert_eq!(captured(&mut tx).await.1, ACTIVE[0]);
            assert_eq!(corrective_state(&mut tx).await, "native_people_directory.row_lock_required");
            let historical: String = sqlx::query_scalar(sqlx::AssertSqlSafe(CLASSIFIER)).fetch_one(tx.as_mut()).await.unwrap();
            assert_eq!(historical, "native_people_directory.finalized");
            tx.rollback().await.unwrap();
            assert_eq!(metadata(&pool).await, original);
            assert_eq!(all_rows(&pool).await, rows);
        }).catch_unwind().await;
        close_states(&[state], outcome).await;
        drop(app);
    }

    #[sqlx::test(migrations = false)]
    async fn row_lock_finalizer_refuses_principals_isolation_and_drift_in_every_phase(
        pool: PgPool,
    ) {
        reviewed_corrective_prerequisites();
        native_people_codec2_install_probe::prepare_successor_ready_database(&pool).await;
        assert_actual_applied_ledger(&pool).await;
        let baseline = metadata(&pool).await;
        assert_eq!(baseline.1, STAGED[0]);
        let rows = all_rows(&pool).await;
        let runtime = login_test_pool(&pool, TestDatabaseLogin::Business).await;
        let outcome = AssertUnwindSafe(async {
            let mut tx = runtime.begin().await.unwrap();
            let error = corrective_install(&mut tx).await.unwrap_err();
            exact_error(&error, "native_people_directory.operator_identity_mismatch");
            tx.rollback().await.unwrap();
            for setting in [
                "SET TRANSACTION ISOLATION LEVEL REPEATABLE READ",
                "SET TRANSACTION ISOLATION LEVEL SERIALIZABLE",
                "SET LOCAL ROLE console_account_owner",
            ] {
                let mut tx = pool.begin().await.unwrap();
                sqlx::raw_sql(sqlx::AssertSqlSafe(setting)).execute(tx.as_mut()).await.unwrap();
                let error = corrective_install(&mut tx).await.unwrap_err();
                exact_error(&error, if setting.starts_with("SET LOCAL ROLE") { "native_people_directory.operator_identity_mismatch" } else { "native_people_directory.unsupported_isolation" });
                tx.rollback().await.unwrap();
                assert_eq!(metadata(&pool).await, baseline);
                assert_eq!(all_rows(&pool).await, rows);
            }
            for phase in 0..3 {
                let mut tx = pool.begin().await.unwrap();
                let phase_result = AssertUnwindSafe(async {
                    if phase >= 1 { install(&mut tx).await.unwrap(); }
                    if phase == 2 { corrective_install(&mut tx).await.unwrap(); }
                    let original = captured(&mut tx).await;
                    assert_eq!(original.1, [STAGED[0], ACTIVE[0], CORRECTED[0]][phase]);
                    for (fault, capture_changes) in [
                        ("GRANT UPDATE(employee_id) ON public.native_people_inputs_v1 TO console_account_owner", true),
                        ("GRANT UPDATE ON public.native_people_inputs_v1 TO console_account_owner", true),
                        ("GRANT UPDATE(command_id) ON public.native_people_inputs_v1 TO console_rt", true),
                        ("GRANT SELECT(xmin) ON public.native_people_inputs_v1 TO console_rt", true),
                        ("ALTER TABLE public.native_people_inputs_v1 DISABLE TRIGGER native_people_inputs_immutable_v1", true),
                        ("CREATE TABLE public.native_people_row_lock_unknown_v1 (unexpected integer)", true),
                        ("CREATE POLICY native_people_owner_v1 ON public.leave_requests TO console_account_owner USING(true)", false),
                    ] {
                        let mut attempt = tx.begin().await.unwrap();
                        sqlx::raw_sql(sqlx::AssertSqlSafe(fault)).execute(attempt.as_mut()).await.unwrap();
                        let fault_result = AssertUnwindSafe(async {
                            let injected = captured(&mut attempt).await;
                            if capture_changes {
                                assert_ne!(injected, original, "capture omitted roster/namespace corruption");
                            } else {
                                // Reserved marker on an unrelated table is deliberately
                                // outside full73 metadata, but presence/classifier owns it.
                                assert!(!original.0["tables"].as_array().unwrap().iter().any(|table| table["name"] == "leave_requests"));
                                let witness: bool = sqlx::query_scalar("SELECT EXISTS(SELECT 1 FROM pg_catalog.pg_policy WHERE polrelid='public.leave_requests'::regclass AND polname='native_people_owner_v1')").fetch_one(attempt.as_mut()).await.unwrap();
                                assert!(witness, "outside-roster reserved policy must actually exist");
                                assert_eq!(injected, original, "outside-roster marker unexpectedly changed full73 metadata");
                            }
                            assert_eq!(corrective_state(&mut attempt).await, "native_people_directory.profile_mismatch");
                            let error = corrective_install(&mut attempt).await.unwrap_err();
                            exact_error(&error, "native_people_directory.profile_mismatch");
                        }).catch_unwind().await;
                        attempt.rollback().await.unwrap();
                        assert_eq!(captured(&mut tx).await, original);
                        if let Err(panic) = fault_result { std::panic::resume_unwind(panic); }
                    }
                    corrective_install(&mut tx).await.unwrap();
                    assert_corrected(&mut tx, 0).await;
                }).catch_unwind().await;
                tx.rollback().await.unwrap();
                assert_eq!(metadata(&pool).await, baseline);
                assert_eq!(all_rows(&pool).await, rows);
                if let Err(panic) = phase_result { std::panic::resume_unwind(panic); }
            }
        }).catch_unwind().await;
        runtime.close().await;
        if let Err(panic) = outcome {
            std::panic::resume_unwind(panic);
        }
    }
}
