load("@prelude//tests:test_toolchain.bzl", "noop_test_toolchain")
load("@prelude//toolchains:cxx.bzl", "system_cxx_toolchain")
load("@prelude//toolchains:genrule.bzl", "system_genrule_toolchain")
load("@prelude//toolchains:python.bzl", "remote_python_toolchain", "system_python_wheel_toolchain")
load("@prelude//toolchains:remote_test_execution.bzl", "remote_test_execution_toolchain")
load("@prelude//toolchains:rust.bzl", "system_rust_toolchain")

system_rust_toolchain(
    name = "rust",
    default_edition = "2024",
    rustc_flags = ["-Copt-level=0"],
    visibility = ["PUBLIC"],
)

_extra_cxx_link_flags = read_root_config("cxx", "link_flags", "")

system_cxx_toolchain(
    name = "cxx",
    compiler = "/usr/bin/clang",
    cxx_compiler = "/usr/bin/clang++",
    archiver = "/usr/bin/ar",
    linker = "/usr/bin/clang",
    link_flags = _extra_cxx_link_flags.split(" ") if _extra_cxx_link_flags else [],
    visibility = ["PUBLIC"],
)

system_genrule_toolchain(
    name = "genrule",
    visibility = ["PUBLIC"],
)

remote_python_toolchain(
    name = "python",
    visibility = ["PUBLIC"],
)

system_python_wheel_toolchain(
    name = "python_wheel",
    visibility = ["PUBLIC"],
)

remote_test_execution_toolchain(
    name = "remote_test_execution",
    visibility = ["PUBLIC"],
)

noop_test_toolchain(
    name = "test",
    visibility = ["PUBLIC"],
)
