/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.console.api.client.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 *
 *
 * @param recipientName
 * @param evidenceObjectId
 * @param handedOverAt
 */
@Serializable

data class Equipment3rCaseDetailViewAllOfHandover (

    @SerialName(value = "recipientName")
    val recipientName: kotlin.String? = null,

    @Contextual @SerialName(value = "evidenceObjectId")
    val evidenceObjectId: java.util.UUID? = null,

    @Contextual @SerialName(value = "handedOverAt")
    val handedOverAt: java.time.OffsetDateTime? = null

) {


}
