/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.console.api.client.model

import com.console.api.client.model.EvaluationEvidenceKind

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 *
 *
 * @param objectKind
 * @param objectRef
 * @param label
 */
@Serializable

data class EvaluationEvidenceLinkInput (

    @Contextual @SerialName(value = "object_kind")
    val objectKind: EvaluationEvidenceKind,

    @SerialName(value = "object_ref")
    val objectRef: kotlin.String,

    @SerialName(value = "label")
    val label: kotlin.String

) {


}
