/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.console.api.client.model


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable


/**
 * Deterministic per-site SLA state over OPEN/IN_PROGRESS/ON_HOLD tickets — BREACHED when any due_at is past, else AT_RISK when any due_at falls within 24 hours, else OK.
 *
 * Values: OK,AT_RISK,BREACHED
 */
@Serializable
enum class FieldSlaState(val value: kotlin.String) {

    @SerialName(value = "OK")
    OK("OK"),

    @SerialName(value = "AT_RISK")
    AT_RISK("AT_RISK"),

    @SerialName(value = "BREACHED")
    BREACHED("BREACHED");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is FieldSlaState) "$data" else null

        /**
         * Returns a valid [FieldSlaState] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): FieldSlaState? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}
