/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.console.api.client.model

import com.console.api.client.model.RecruitApplicant
import com.console.api.client.model.RecruitPosting

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 *
 *
 * @param employeeId
 * @param applicant
 * @param posting
 */
@Serializable

data class HireRecruitApplicantResponse (

    @Contextual @SerialName(value = "employee_id")
    val employeeId: java.util.UUID,

    @SerialName(value = "applicant")
    val applicant: RecruitApplicant,

    @SerialName(value = "posting")
    val posting: RecruitPosting

) {


}
