/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.console.api.client.model

import com.console.api.client.model.NotificationCategoryCount
import com.console.api.client.model.NotificationLink
import com.console.api.client.model.NotificationSummary

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 *
 *
 * @param link
 * @param total
 * @param unread Unread rows in the group; annotated, never mute-filtered.
 * @param categories Per-category unread breakdown within the group; zero-unread categories are omitted.
 * @param latest
 * @param muted True when an all-scope or matching object-scope mute policy covers this object for the caller; category-scope policies never flip the group bell.
 */
@Serializable

data class NotificationObjectGroup (

    @SerialName(value = "link")
    val link: NotificationLink,

    @SerialName(value = "total")
    val total: kotlin.Long,

    /* Unread rows in the group; annotated, never mute-filtered. */
    @SerialName(value = "unread")
    val unread: kotlin.Long,

    /* Per-category unread breakdown within the group; zero-unread categories are omitted. */
    @SerialName(value = "categories")
    val categories: kotlin.collections.List<NotificationCategoryCount>,

    @SerialName(value = "latest")
    val latest: NotificationSummary,

    /* True when an all-scope or matching object-scope mute policy covers this object for the caller; category-scope policies never flip the group bell. */
    @SerialName(value = "muted")
    val muted: kotlin.Boolean

) {


}
