/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.console.api.client.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 *
 *
 * @param code
 * @param label
 * @param dependentKind
 * @param count
 */
@Serializable

data class OrgChangePreflightWarning (

    @SerialName(value = "code")
    val code: kotlin.String,

    @SerialName(value = "label")
    val label: kotlin.String,

    @SerialName(value = "dependentKind")
    val dependentKind: kotlin.String? = null,

    @SerialName(value = "count")
    val count: kotlin.Long? = null

) {


}
