/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.console.api.client.model

import com.console.api.client.model.SupportTicketAcceptanceChannel
import com.console.api.client.model.SupportTicketAcceptanceKind

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 *
 *
 * @param kind
 * @param channel
 * @param acceptedBy Customer-side acknowledger name (business fact, never logged).
 * @param note Required when kind is CUSTOMER_DECLINED; it becomes the customer-visible comment on the reopen.
 */
@Serializable

data class RecordSupportTicketAcceptanceRequest (

    @Contextual @SerialName(value = "kind")
    val kind: SupportTicketAcceptanceKind,

    @Contextual @SerialName(value = "channel")
    val channel: SupportTicketAcceptanceChannel,

    /* Customer-side acknowledger name (business fact, never logged). */
    @SerialName(value = "accepted_by")
    val acceptedBy: kotlin.String,

    /* Required when kind is CUSTOMER_DECLINED; it becomes the customer-visible comment on the reopen. */
    @SerialName(value = "note")
    val note: kotlin.String? = null

) {


}
