/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.console.api.client.model

import com.console.api.client.model.EvaluationEvidenceLinkInput
import com.console.api.client.model.EvaluationGrade

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 *
 *
 * @param grade
 * @param note
 * @param evidenceLinks
 */
@Serializable

data class SaveEvaluationReviewRequest (

    @Contextual @SerialName(value = "grade")
    val grade: EvaluationGrade? = null,

    @SerialName(value = "note")
    val note: kotlin.String? = null,

    @SerialName(value = "evidence_links")
    val evidenceLinks: kotlin.collections.List<EvaluationEvidenceLinkInput>? = null

) {


}
