/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.console.api.client.model

import com.console.api.client.model.SupportTicketAcceptanceChannel
import com.console.api.client.model.SupportTicketAcceptanceKind

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 *
 *
 * @param id
 * @param ticketId
 * @param kind
 * @param channel
 * @param acceptedBy
 * @param note
 * @param recordedByUserId
 * @param recordedByName Recorder display name via a same-org lookup; null when the account no longer exists.
 * @param occurredAt
 */
@Serializable

data class SupportTicketAcceptance (

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @Contextual @SerialName(value = "ticket_id")
    val ticketId: java.util.UUID,

    @Contextual @SerialName(value = "kind")
    val kind: SupportTicketAcceptanceKind,

    @Contextual @SerialName(value = "channel")
    val channel: SupportTicketAcceptanceChannel,

    @SerialName(value = "accepted_by")
    val acceptedBy: kotlin.String,

    @SerialName(value = "note")
    val note: kotlin.String?,

    @Contextual @SerialName(value = "recorded_by_user_id")
    val recordedByUserId: java.util.UUID,

    /* Recorder display name via a same-org lookup; null when the account no longer exists. */
    @SerialName(value = "recorded_by_name")
    val recordedByName: kotlin.String?,

    @Contextual @SerialName(value = "occurred_at")
    val occurredAt: java.time.OffsetDateTime

) {


}
