/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.maintenance.api.client.model

import com.maintenance.api.client.model.ApprovalOntologyContext
import com.maintenance.api.client.model.ApprovalPolicyContext
import com.maintenance.api.client.model.ApprovalWorkflowContext
import com.maintenance.api.client.model.DailyPlanSummary
import com.maintenance.api.client.model.TargetChangeRequestSummary
import com.maintenance.api.client.model.WorkOrderListItem

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * A typed approval task over an ontology object. The source-specific payloads are mutually exclusive; `source` selects which payload is populated.
 *
 * @param id Stable federated id in `{source}:{source_id}` form.
 * @param source
 * @param sourceId
 * @param branchId
 * @param status
 * @param title
 * @param summary
 * @param requestedAt
 * @param dueAt
 * @param href
 * @param actionHref
 * @param ontology
 * @param workflow
 * @param policy
 * @param workOrder Present only when `source` is `WORK_ORDER`.
 * @param dailyPlan Present only when `source` is `DAILY_PLAN`.
 * @param targetChange Present only when `source` is `TARGET_CHANGE`.
 */
@Serializable

data class ApprovalItem (

    /* Stable federated id in `{source}:{source_id}` form. */
    @SerialName(value = "id")
    val id: kotlin.String,

    @SerialName(value = "source")
    val source: ApprovalItem.Source,

    @Contextual @SerialName(value = "source_id")
    val sourceId: java.util.UUID,

    @Contextual @SerialName(value = "branch_id")
    val branchId: java.util.UUID,

    @SerialName(value = "status")
    val status: kotlin.String,

    @SerialName(value = "title")
    val title: kotlin.String,

    @SerialName(value = "summary")
    val summary: kotlin.String,

    @Contextual @SerialName(value = "requested_at")
    val requestedAt: java.time.OffsetDateTime?,

    @Contextual @SerialName(value = "due_at")
    val dueAt: java.time.OffsetDateTime?,

    @SerialName(value = "href")
    val href: kotlin.String,

    @SerialName(value = "action_href")
    val actionHref: kotlin.String,

    @SerialName(value = "ontology")
    val ontology: ApprovalOntologyContext,

    @SerialName(value = "workflow")
    val workflow: ApprovalWorkflowContext,

    @SerialName(value = "policy")
    val policy: ApprovalPolicyContext,

    /* Present only when `source` is `WORK_ORDER`. */
    @SerialName(value = "work_order")
    val workOrder: WorkOrderListItem? = null,

    /* Present only when `source` is `DAILY_PLAN`. */
    @SerialName(value = "daily_plan")
    val dailyPlan: DailyPlanSummary? = null,

    /* Present only when `source` is `TARGET_CHANGE`. */
    @SerialName(value = "target_change")
    val targetChange: TargetChangeRequestSummary? = null

) {

    /**
     *
     *
     * Values: WORK_ORDER,DAILY_PLAN,TARGET_CHANGE
     */
    @Serializable
    enum class Source(val value: kotlin.String) {
        @SerialName(value = "WORK_ORDER") WORK_ORDER("WORK_ORDER"),
        @SerialName(value = "DAILY_PLAN") DAILY_PLAN("DAILY_PLAN"),
        @SerialName(value = "TARGET_CHANGE") TARGET_CHANGE("TARGET_CHANGE");
    }

}
