/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.maintenance.api.client.model

import com.maintenance.api.client.model.AttendanceSubstitutionCandidate

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 *
 *
 * @param items
 * @param total
 * @param limit
 * @param offset
 */
@Serializable

data class AttendanceSubstitutionCandidatePage (

    @SerialName(value = "items")
    val items: kotlin.collections.List<AttendanceSubstitutionCandidate>,

    @SerialName(value = "total")
    val total: kotlin.Long,

    @SerialName(value = "limit")
    val limit: kotlin.Long,

    @SerialName(value = "offset")
    val offset: kotlin.Long

) {


}
