/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.maintenance.api.client.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 *
 *
 * @param tierBasis
 * @param tierKey
 * @param valueLabel
 * @param criteria
 * @param displayOrder
 * @param id
 * @param benefitId
 * @param amountWon
 * @param limitPeriod
 */
@Serializable

data class BenefitCatalogTier (

    @SerialName(value = "tier_basis")
    val tierBasis: kotlin.String,

    @SerialName(value = "tier_key")
    val tierKey: kotlin.String,

    @SerialName(value = "value_label")
    val valueLabel: kotlin.String,

    @Contextual @SerialName(value = "criteria")
    val criteria: kotlin.collections.Map<kotlin.String, kotlinx.serialization.json.JsonElement>,

    @SerialName(value = "display_order")
    val displayOrder: kotlin.Int,

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID? = null,

    @Contextual @SerialName(value = "benefit_id")
    val benefitId: java.util.UUID? = null,

    @SerialName(value = "amount_won")
    val amountWon: kotlin.Long? = null,

    @SerialName(value = "limit_period")
    val limitPeriod: kotlin.String? = null

) {


}
