/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.maintenance.api.client.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 *
 *
 * @param id
 * @param regionId
 * @param name
 * @param deactivatedAt Set when the branch has been soft-deleted (deactivated); null for an active branch. Active-only listings omit deactivated rows.
 * @param createdAt
 */
@Serializable

data class BranchSummary (

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @Contextual @SerialName(value = "region_id")
    val regionId: java.util.UUID,

    @SerialName(value = "name")
    val name: kotlin.String,

    /* Set when the branch has been soft-deleted (deactivated); null for an active branch. Active-only listings omit deactivated rows. */
    @Contextual @SerialName(value = "deactivated_at")
    val deactivatedAt: java.time.OffsetDateTime?,

    @Contextual @SerialName(value = "created_at")
    val createdAt: java.time.OffsetDateTime

) {


}
