/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.maintenance.api.client.model

import com.maintenance.api.client.model.BulkApprovalTask

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 *
 *
 * @param items
 * @param hasMore
 * @param nextCursor
 */
@Serializable

data class BulkApprovalInboxResponse (

    @SerialName(value = "items")
    val items: kotlin.collections.List<BulkApprovalTask>,

    @SerialName(value = "has_more")
    val hasMore: kotlin.Boolean,

    @SerialName(value = "next_cursor")
    val nextCursor: kotlin.String? = null

) {


}
