/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.maintenance.api.client.model

import com.maintenance.api.client.model.FrameworkKind
import com.maintenance.api.client.model.FrameworkStatus

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 *
 *
 * @param id
 * @param code
 * @param name
 * @param versionLabel
 * @param frameworkKind
 * @param status
 * @param metadata
 * @param createdBy
 * @param updatedBy
 * @param createdAt
 * @param updatedAt
 * @param ownerUserId
 * @param effectiveFrom
 * @param effectiveTo
 */
@Serializable

data class ComplianceFramework (

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @SerialName(value = "code")
    val code: kotlin.String,

    @SerialName(value = "name")
    val name: kotlin.String,

    @SerialName(value = "version_label")
    val versionLabel: kotlin.String,

    @Contextual @SerialName(value = "framework_kind")
    val frameworkKind: FrameworkKind,

    @Contextual @SerialName(value = "status")
    val status: FrameworkStatus,

    @Contextual @SerialName(value = "metadata")
    val metadata: kotlin.collections.Map<kotlin.String, kotlinx.serialization.json.JsonElement>,

    @Contextual @SerialName(value = "created_by")
    val createdBy: java.util.UUID,

    @Contextual @SerialName(value = "updated_by")
    val updatedBy: java.util.UUID,

    @Contextual @SerialName(value = "created_at")
    val createdAt: java.time.OffsetDateTime,

    @Contextual @SerialName(value = "updated_at")
    val updatedAt: java.time.OffsetDateTime,

    @Contextual @SerialName(value = "owner_user_id")
    val ownerUserId: java.util.UUID? = null,

    @Contextual @SerialName(value = "effective_from")
    val effectiveFrom: java.time.LocalDate? = null,

    @Contextual @SerialName(value = "effective_to")
    val effectiveTo: java.time.LocalDate? = null

) {


}
