/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.maintenance.api.client.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 *
 *
 * @param id
 * @param customerId
 * @param title
 * @param status
 * @param version
 * @param createdAt
 * @param updatedAt
 * @param customerDocumentId
 * @param ontologyInstanceId
 * @param approvalId
 * @param workflowExecutionId
 */
@Serializable

data class ConsultingEngagement (

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @Contextual @SerialName(value = "customer_id")
    val customerId: java.util.UUID,

    @SerialName(value = "title")
    val title: kotlin.String,

    @SerialName(value = "status")
    val status: ConsultingEngagement.Status,

    @SerialName(value = "version")
    val version: kotlin.Long,

    @Contextual @SerialName(value = "created_at")
    val createdAt: java.time.OffsetDateTime,

    @Contextual @SerialName(value = "updated_at")
    val updatedAt: java.time.OffsetDateTime,

    @Contextual @SerialName(value = "customer_document_id")
    val customerDocumentId: java.util.UUID? = null,

    @Contextual @SerialName(value = "ontology_instance_id")
    val ontologyInstanceId: java.util.UUID? = null,

    @Contextual @SerialName(value = "approval_id")
    val approvalId: java.util.UUID? = null,

    @Contextual @SerialName(value = "workflow_execution_id")
    val workflowExecutionId: java.util.UUID? = null

) {

    /**
     *
     *
     * Values: DRAFT,PROPOSED,APPROVED,IMPLEMENTED,MEASURED,SUSTAINED,CORRECTIVE
     */
    @Serializable
    enum class Status(val value: kotlin.String) {
        @SerialName(value = "DRAFT") DRAFT("DRAFT"),
        @SerialName(value = "PROPOSED") PROPOSED("PROPOSED"),
        @SerialName(value = "APPROVED") APPROVED("APPROVED"),
        @SerialName(value = "IMPLEMENTED") IMPLEMENTED("IMPLEMENTED"),
        @SerialName(value = "MEASURED") MEASURED("MEASURED"),
        @SerialName(value = "SUSTAINED") SUSTAINED("SUSTAINED"),
        @SerialName(value = "CORRECTIVE") CORRECTIVE("CORRECTIVE");
    }

}
