/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.maintenance.api.client.model

import com.maintenance.api.client.model.CostLedgerSource

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 *
 *
 * @param id
 * @param branchId
 * @param equipmentId
 * @param source
 * @param amountWon
 * @param memo
 * @param residualBeforeWon
 * @param residualAfterWon
 * @param entryAt
 * @param workOrderId
 * @param purchaseRequestId
 */
@Serializable

data class CostLedgerEntrySummary (

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @Contextual @SerialName(value = "branch_id")
    val branchId: java.util.UUID,

    @Contextual @SerialName(value = "equipment_id")
    val equipmentId: java.util.UUID,

    @Contextual @SerialName(value = "source")
    val source: CostLedgerSource,

    @SerialName(value = "amount_won")
    val amountWon: kotlin.Long,

    @SerialName(value = "memo")
    val memo: kotlin.String,

    @SerialName(value = "residual_before_won")
    val residualBeforeWon: kotlin.Long,

    @SerialName(value = "residual_after_won")
    val residualAfterWon: kotlin.Long,

    @Contextual @SerialName(value = "entry_at")
    val entryAt: java.time.OffsetDateTime,

    @Contextual @SerialName(value = "work_order_id")
    val workOrderId: java.util.UUID? = null,

    @Contextual @SerialName(value = "purchase_request_id")
    val purchaseRequestId: java.util.UUID? = null

) {


}
