/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.maintenance.api.client.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 *
 *
 * @param roundNo
 * @param referenceYear
 * @param minRemainingDays
 * @param note
 */
@Serializable

data class CreateLeavePromotion (

    @SerialName(value = "round_no")
    val roundNo: CreateLeavePromotion.RoundNo,

    @SerialName(value = "reference_year")
    val referenceYear: kotlin.Int,

    @Contextual @SerialName(value = "min_remaining_days")
    val minRemainingDays: java.math.BigDecimal? = null,

    @SerialName(value = "note")
    val note: kotlin.String? = null

) {

    /**
     *
     *
     * Values: _1,_2
     */
    @Serializable
    enum class RoundNo(val value: kotlin.Int) {
        @SerialName(value = "1") _1(1),
        @SerialName(value = "2") _2(2);
    }

}
