/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.maintenance.api.client.model

import com.maintenance.api.client.model.WorkflowActionAllowlistEntry

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 *
 *
 * @param workflowKey
 * @param displayName
 * @param objectType
 * @param definition
 * @param approvalLine
 * @param paymentLine
 * @param notificationRules
 * @param actionAllowlist
 * @param requiredApprovalLine
 * @param requiredPaymentLine
 */
@Serializable

data class CreateWorkflowDefinitionRequest (

    @SerialName(value = "workflow_key")
    val workflowKey: kotlin.String,

    @SerialName(value = "display_name")
    val displayName: kotlin.String,

    @SerialName(value = "object_type")
    val objectType: kotlin.String,

    @Contextual @SerialName(value = "definition")
    val definition: kotlin.collections.Map<kotlin.String, kotlinx.serialization.json.JsonElement>? = null,

    @SerialName(value = "approval_line")
    val approvalLine: kotlin.collections.List<@Contextual kotlin.collections.Map<kotlin.String, kotlinx.serialization.json.JsonElement>>? = null,

    @SerialName(value = "payment_line")
    val paymentLine: kotlin.collections.List<@Contextual kotlin.collections.Map<kotlin.String, kotlinx.serialization.json.JsonElement>>? = null,

    @SerialName(value = "notification_rules")
    val notificationRules: kotlin.collections.List<@Contextual kotlin.collections.Map<kotlin.String, kotlinx.serialization.json.JsonElement>>? = null,

    @SerialName(value = "action_allowlist")
    val actionAllowlist: kotlin.collections.List<WorkflowActionAllowlistEntry>? = null,

    @SerialName(value = "required_approval_line")
    val requiredApprovalLine: kotlin.Boolean? = null,

    @SerialName(value = "required_payment_line")
    val requiredPaymentLine: kotlin.Boolean? = null

) {


}
