/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.maintenance.api.client.model

import com.maintenance.api.client.model.EvaluationCycleKind

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 *
 *
 * @param name
 * @param kind
 * @param periodLabel
 * @param dueDate
 */
@Serializable

data class CreateEvaluationCycleRequest (

    @SerialName(value = "name")
    val name: kotlin.String,

    @Contextual @SerialName(value = "kind")
    val kind: EvaluationCycleKind,

    @SerialName(value = "period_label")
    val periodLabel: kotlin.String,

    @Contextual @SerialName(value = "due_date")
    val dueDate: java.time.LocalDate

) {


}
