/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.maintenance.api.client.model

import com.maintenance.api.client.model.EmployeeLifecycleSignoffs

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 *
 *
 * @param eventType
 * @param effectiveDate
 * @param comment
 * @param signoffs
 * @param toStatus
 * @param toCompany
 * @param toOrgUnit
 * @param toPosition
 */
@Serializable

data class CreateEmployeeLifecycleEventRequest (

    @SerialName(value = "event_type")
    val eventType: CreateEmployeeLifecycleEventRequest.EventType,

    @SerialName(value = "effective_date")
    val effectiveDate: kotlin.String,

    @SerialName(value = "comment")
    val comment: kotlin.String,

    @SerialName(value = "signoffs")
    val signoffs: EmployeeLifecycleSignoffs,

    @SerialName(value = "to_status")
    val toStatus: CreateEmployeeLifecycleEventRequest.ToStatus? = null,

    @SerialName(value = "to_company")
    val toCompany: kotlin.String? = null,

    @SerialName(value = "to_org_unit")
    val toOrgUnit: kotlin.String? = null,

    @SerialName(value = "to_position")
    val toPosition: kotlin.String? = null

) {

    /**
     *
     *
     * Values: ONBOARD,OFFBOARD,TERMINATE,TRANSFER
     */
    @Serializable
    enum class EventType(val value: kotlin.String) {
        @SerialName(value = "ONBOARD") ONBOARD("ONBOARD"),
        @SerialName(value = "OFFBOARD") OFFBOARD("OFFBOARD"),
        @SerialName(value = "TERMINATE") TERMINATE("TERMINATE"),
        @SerialName(value = "TRANSFER") TRANSFER("TRANSFER");
    }
    /**
     *
     *
     * Values: ACTIVE,EXITED,UNKNOWN
     */
    @Serializable
    enum class ToStatus(val value: kotlin.String) {
        @SerialName(value = "ACTIVE") ACTIVE("ACTIVE"),
        @SerialName(value = "EXITED") EXITED("EXITED"),
        @SerialName(value = "UNKNOWN") UNKNOWN("UNKNOWN");
    }

}
