/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.maintenance.api.client.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 *
 *
 * @param id
 * @param itemId
 * @param ivCode
 * @param displayName
 * @param unitCode
 * @param systemQuantityMilli
 * @param countedQuantityMilli
 * @param varianceMilli
 * @param recordedBy
 * @param recordedAt
 * @param reason
 * @param note
 */
@Serializable

data class CycleCountLine (

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @Contextual @SerialName(value = "itemId")
    val itemId: java.util.UUID,

    @SerialName(value = "ivCode")
    val ivCode: kotlin.String,

    @SerialName(value = "displayName")
    val displayName: kotlin.String,

    @SerialName(value = "unitCode")
    val unitCode: kotlin.String,

    @SerialName(value = "systemQuantityMilli")
    val systemQuantityMilli: kotlin.Long,

    @SerialName(value = "countedQuantityMilli")
    val countedQuantityMilli: kotlin.Long,

    @SerialName(value = "varianceMilli")
    val varianceMilli: kotlin.Long,

    @Contextual @SerialName(value = "recordedBy")
    val recordedBy: java.util.UUID,

    @Contextual @SerialName(value = "recordedAt")
    val recordedAt: java.time.OffsetDateTime,

    @SerialName(value = "reason")
    val reason: CycleCountLine.Reason? = null,

    @SerialName(value = "note")
    val note: kotlin.String? = null

) {

    /**
     *
     *
     * Values: DAMAGE,LOSS,MISCOUNT,FOUND,OTHER
     */
    @Serializable
    enum class Reason(val value: kotlin.String) {
        @SerialName(value = "DAMAGE") DAMAGE("DAMAGE"),
        @SerialName(value = "LOSS") LOSS("LOSS"),
        @SerialName(value = "MISCOUNT") MISCOUNT("MISCOUNT"),
        @SerialName(value = "FOUND") FOUND("FOUND"),
        @SerialName(value = "OTHER") OTHER("OTHER");
    }

}
