/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.maintenance.api.client.model

import com.maintenance.api.client.model.TriggerBindingResponse
import com.maintenance.api.client.model.WorkflowDefinitionResponse

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 *
 *
 * @param kind
 * @param definitions
 * @param bindings
 */
@Serializable

data class DefinitionsByObjectKindResponse (

    @SerialName(value = "kind")
    val kind: kotlin.String,

    @SerialName(value = "definitions")
    val definitions: kotlin.collections.List<WorkflowDefinitionResponse>,

    @SerialName(value = "bindings")
    val bindings: kotlin.collections.List<TriggerBindingResponse>

) {


}
