/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.maintenance.api.client.model

import com.maintenance.api.client.model.DispatchQueueItem
import com.maintenance.api.client.model.DispatchQueueStats

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 *
 *
 * @param items
 * @param stats
 * @param nextAfter
 */
@Serializable

data class DispatchQueuePage (

    @SerialName(value = "items")
    val items: kotlin.collections.List<DispatchQueueItem>,

    @SerialName(value = "stats")
    val stats: DispatchQueueStats,

    @SerialName(value = "next_after")
    val nextAfter: kotlin.String? = null

) {


}
