/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.maintenance.api.client.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * One immutable version of an in-console office document. The storage key is internal and never returned.
 *
 * @param id
 * @param documentRef
 * @param versionNo
 * @param contentHash
 * @param fileType
 * @param byteSize
 * @param createdAt
 * @param restoredFrom The version_no this version non-destructively restored, when it is a rollback.
 * @param createdBy Actor who produced the version; omitted for system-initiated (force-save callback) versions.
 */
@Serializable

data class DocumentVersion (

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @SerialName(value = "documentRef")
    val documentRef: kotlin.String,

    @SerialName(value = "versionNo")
    val versionNo: kotlin.Int,

    @SerialName(value = "contentHash")
    val contentHash: kotlin.String,

    @SerialName(value = "fileType")
    val fileType: DocumentVersion.FileType,

    @SerialName(value = "byteSize")
    val byteSize: kotlin.Long,

    @Contextual @SerialName(value = "createdAt")
    val createdAt: java.time.OffsetDateTime,

    /* The version_no this version non-destructively restored, when it is a rollback. */
    @SerialName(value = "restoredFrom")
    val restoredFrom: kotlin.Int? = null,

    /* Actor who produced the version; omitted for system-initiated (force-save callback) versions. */
    @Contextual @SerialName(value = "createdBy")
    val createdBy: java.util.UUID? = null

) {

    /**
     *
     *
     * Values: DOCX,XLSX,PPTX
     */
    @Serializable
    enum class FileType(val value: kotlin.String) {
        @SerialName(value = "docx") DOCX("docx"),
        @SerialName(value = "xlsx") XLSX("xlsx"),
        @SerialName(value = "pptx") PPTX("pptx");
    }

}
