/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.maintenance.api.client.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 *
 *
 * @param id
 * @param company
 * @param name
 * @param identityResolutionStrategy Non-PII strategy used to keep same-name employees from being merged by name alone.
 * @param identityResolutionConfidence Confidence derived from the accepted identity strategy; never from user-supplied labels.
 * @param identityReviewRequired True when HR must manually verify the employee identity before account linkage or duplicate cleanup.
 * @param identityNameOnlyMerge Always false; name-only merging is not allowed because different people can share a name.
 * @param createdAt
 * @param updatedAt
 * @param employeeNumber
 * @param orgUnit
 * @param worksiteName
 * @param worksite
 * @param job
 * @param position
 * @param hireDate
 * @param exitDate
 * @param status
 * @param leaveAccrued
 * @param leaveUsed
 * @param leaveRemaining
 */
@Serializable

data class Employee (

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @SerialName(value = "company")
    val company: kotlin.String,

    @SerialName(value = "name")
    val name: kotlin.String,

    /* Non-PII strategy used to keep same-name employees from being merged by name alone. */
    @SerialName(value = "identity_resolution_strategy")
    val identityResolutionStrategy: Employee.IdentityResolutionStrategy,

    /* Confidence derived from the accepted identity strategy; never from user-supplied labels. */
    @SerialName(value = "identity_resolution_confidence")
    val identityResolutionConfidence: Employee.IdentityResolutionConfidence,

    /* True when HR must manually verify the employee identity before account linkage or duplicate cleanup. */
    @SerialName(value = "identity_review_required")
    val identityReviewRequired: kotlin.Boolean,

    /* Always false; name-only merging is not allowed because different people can share a name. */
    @SerialName(value = "identity_name_only_merge")
    val identityNameOnlyMerge: kotlin.Boolean,

    @Contextual @SerialName(value = "created_at")
    val createdAt: java.time.OffsetDateTime,

    @Contextual @SerialName(value = "updated_at")
    val updatedAt: java.time.OffsetDateTime,

    @SerialName(value = "employee_number")
    val employeeNumber: kotlin.String? = null,

    @SerialName(value = "org_unit")
    val orgUnit: kotlin.String? = null,

    @SerialName(value = "worksite_name")
    val worksiteName: kotlin.String? = null,

    @SerialName(value = "worksite")
    val worksite: kotlin.String? = null,

    @SerialName(value = "job")
    val job: kotlin.String? = null,

    @SerialName(value = "position")
    val position: kotlin.String? = null,

    @SerialName(value = "hire_date")
    val hireDate: kotlin.String? = null,

    @SerialName(value = "exit_date")
    val exitDate: kotlin.String? = null,

    @SerialName(value = "status")
    val status: kotlin.String? = null,

    @SerialName(value = "leave_accrued")
    val leaveAccrued: kotlin.String? = null,

    @SerialName(value = "leave_used")
    val leaveUsed: kotlin.String? = null,

    @SerialName(value = "leave_remaining")
    val leaveRemaining: kotlin.String? = null

) {

    /**
     * Non-PII strategy used to keep same-name employees from being merged by name alone.
     *
     * Values: EMPLOYEE_NUMBER,LEGAL_IDENTIFIER_HASH,BIRTH_HIRE_FINGERPRINT,SOURCE_ROW_FINGERPRINT
     */
    @Serializable
    enum class IdentityResolutionStrategy(val value: kotlin.String) {
        @SerialName(value = "employee_number") EMPLOYEE_NUMBER("employee_number"),
        @SerialName(value = "legal_identifier_hash") LEGAL_IDENTIFIER_HASH("legal_identifier_hash"),
        @SerialName(value = "birth_hire_fingerprint") BIRTH_HIRE_FINGERPRINT("birth_hire_fingerprint"),
        @SerialName(value = "source_row_fingerprint") SOURCE_ROW_FINGERPRINT("source_row_fingerprint");
    }
    /**
     * Confidence derived from the accepted identity strategy; never from user-supplied labels.
     *
     * Values: HIGH,MEDIUM,LOW
     */
    @Serializable
    enum class IdentityResolutionConfidence(val value: kotlin.String) {
        @SerialName(value = "high") HIGH("high"),
        @SerialName(value = "medium") MEDIUM("medium"),
        @SerialName(value = "low") LOW("low");
    }

}
