/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.maintenance.api.client.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 *
 *
 * @param id
 * @param company
 * @param name
 * @param createdAt
 * @param updatedAt
 * @param employeeNumber
 * @param orgUnit
 * @param worksiteName
 * @param worksite
 * @param job
 * @param position
 * @param hireDate
 * @param exitDate
 * @param status
 * @param leaveAccrued
 * @param leaveUsed
 * @param leaveRemaining
 */
@Serializable

data class Employee (

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @SerialName(value = "company")
    val company: kotlin.String,

    @SerialName(value = "name")
    val name: kotlin.String,

    @Contextual @SerialName(value = "created_at")
    val createdAt: java.time.OffsetDateTime,

    @Contextual @SerialName(value = "updated_at")
    val updatedAt: java.time.OffsetDateTime,

    @SerialName(value = "employee_number")
    val employeeNumber: kotlin.String? = null,

    @SerialName(value = "org_unit")
    val orgUnit: kotlin.String? = null,

    @SerialName(value = "worksite_name")
    val worksiteName: kotlin.String? = null,

    @SerialName(value = "worksite")
    val worksite: kotlin.String? = null,

    @SerialName(value = "job")
    val job: kotlin.String? = null,

    @SerialName(value = "position")
    val position: kotlin.String? = null,

    @SerialName(value = "hire_date")
    val hireDate: kotlin.String? = null,

    @SerialName(value = "exit_date")
    val exitDate: kotlin.String? = null,

    @SerialName(value = "status")
    val status: kotlin.String? = null,

    @SerialName(value = "leave_accrued")
    val leaveAccrued: kotlin.String? = null,

    @SerialName(value = "leave_used")
    val leaveUsed: kotlin.String? = null,

    @SerialName(value = "leave_remaining")
    val leaveRemaining: kotlin.String? = null

) {


}
