/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.maintenance.api.client.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 *
 *
 * @param sourceSheet
 * @param sourceRow
 * @param rowStatus
 * @param propertyValues
 */
@Serializable

data class EmployeeImportPreviewRow (

    @SerialName(value = "source_sheet")
    val sourceSheet: kotlin.String,

    @SerialName(value = "source_row")
    val sourceRow: kotlin.Int,

    @SerialName(value = "row_status")
    val rowStatus: EmployeeImportPreviewRow.RowStatus,

    @Contextual @SerialName(value = "values")
    val propertyValues: kotlin.collections.Map<kotlin.String, kotlinx.serialization.json.JsonElement>

) {

    /**
     *
     *
     * Values: CANDIDATE,PRESERVED,ERROR
     */
    @Serializable
    enum class RowStatus(val value: kotlin.String) {
        @SerialName(value = "CANDIDATE") CANDIDATE("CANDIDATE"),
        @SerialName(value = "PRESERVED") PRESERVED("PRESERVED"),
        @SerialName(value = "ERROR") ERROR("ERROR");
    }

}
