/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.maintenance.api.client.model

import com.maintenance.api.client.model.EquipmentStatus

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 *
 *
 * @param equipmentId
 * @param branchId
 * @param equipmentNo
 * @param status
 * @param specification
 * @param tonText
 * @param customerName
 * @param siteName
 * @param updatedAt
 * @param managementNo
 * @param model
 * @param maker
 * @param assetOwner Legal owner recorded on the asset master. Distinct from customer_name/site_name, which describe the current operator/site.
 * @param vin
 */
@Serializable

data class EquipmentListItem (

    @Contextual @SerialName(value = "equipment_id")
    val equipmentId: java.util.UUID,

    @Contextual @SerialName(value = "branch_id")
    val branchId: java.util.UUID,

    @SerialName(value = "equipment_no")
    val equipmentNo: kotlin.String,

    @Contextual @SerialName(value = "status")
    val status: EquipmentStatus,

    @SerialName(value = "specification")
    val specification: kotlin.String,

    @SerialName(value = "ton_text")
    val tonText: kotlin.String,

    @SerialName(value = "customer_name")
    val customerName: kotlin.String,

    @SerialName(value = "site_name")
    val siteName: kotlin.String,

    @Contextual @SerialName(value = "updated_at")
    val updatedAt: java.time.OffsetDateTime,

    @SerialName(value = "management_no")
    val managementNo: kotlin.String? = null,

    @SerialName(value = "model")
    val model: kotlin.String? = null,

    @SerialName(value = "maker")
    val maker: kotlin.String? = null,

    /* Legal owner recorded on the asset master. Distinct from customer_name/site_name, which describe the current operator/site. */
    @SerialName(value = "asset_owner")
    val assetOwner: kotlin.String? = null,

    @SerialName(value = "vin")
    val vin: kotlin.String? = null

) {


}
