/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.maintenance.api.client.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 *
 *
 * @param conditionGrade
 * @param findings
 * @param disposition
 * @param assessedBy
 * @param assessedAt
 */
@Serializable

data class Equipment3rCaseDetailViewAllOfAssessment (

    @SerialName(value = "conditionGrade")
    val conditionGrade: Equipment3rCaseDetailViewAllOfAssessment.ConditionGrade? = null,

    @SerialName(value = "findings")
    val findings: kotlin.String? = null,

    @SerialName(value = "disposition")
    val disposition: Equipment3rCaseDetailViewAllOfAssessment.Disposition? = null,

    @Contextual @SerialName(value = "assessedBy")
    val assessedBy: java.util.UUID? = null,

    @Contextual @SerialName(value = "assessedAt")
    val assessedAt: java.time.OffsetDateTime? = null

) {

    /**
     *
     *
     * Values: A,B,C,D
     */
    @Serializable
    enum class ConditionGrade(val value: kotlin.String) {
        @SerialName(value = "A") A("A"),
        @SerialName(value = "B") B("B"),
        @SerialName(value = "C") C("C"),
        @SerialName(value = "D") D("D");
    }
    /**
     *
     *
     * Values: REPAIR,REFURBISH,RESALE,REDEPLOY
     */
    @Serializable
    enum class Disposition(val value: kotlin.String) {
        @SerialName(value = "REPAIR") REPAIR("REPAIR"),
        @SerialName(value = "REFURBISH") REFURBISH("REFURBISH"),
        @SerialName(value = "RESALE") RESALE("RESALE"),
        @SerialName(value = "REDEPLOY") REDEPLOY("REDEPLOY");
    }

}
