/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.maintenance.api.client.model

import com.maintenance.api.client.model.EquipmentStatus

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 *
 *
 * @param equipmentId
 * @param branchId
 * @param equipmentNo
 * @param status
 * @param customerId
 * @param customerName
 * @param siteId
 * @param siteName
 * @param managementNo
 * @param model
 * @param maker
 */
@Serializable

data class EquipmentTimelineEquipment (

    @Contextual @SerialName(value = "equipment_id")
    val equipmentId: java.util.UUID,

    @Contextual @SerialName(value = "branch_id")
    val branchId: java.util.UUID,

    @SerialName(value = "equipment_no")
    val equipmentNo: kotlin.String,

    @Contextual @SerialName(value = "status")
    val status: EquipmentStatus,

    @Contextual @SerialName(value = "customer_id")
    val customerId: java.util.UUID,

    @SerialName(value = "customer_name")
    val customerName: kotlin.String,

    @Contextual @SerialName(value = "site_id")
    val siteId: java.util.UUID,

    @SerialName(value = "site_name")
    val siteName: kotlin.String,

    @SerialName(value = "management_no")
    val managementNo: kotlin.String? = null,

    @SerialName(value = "model")
    val model: kotlin.String? = null,

    @SerialName(value = "maker")
    val maker: kotlin.String? = null

) {


}
