/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.maintenance.api.client.model

import com.maintenance.api.client.model.Equipment3rCaseDetailViewAllOfApproval
import com.maintenance.api.client.model.Equipment3rCaseDetailViewAllOfAssessment
import com.maintenance.api.client.model.Equipment3rCaseDetailViewAllOfDispatch
import com.maintenance.api.client.model.Equipment3rCaseDetailViewAllOfHandover
import com.maintenance.api.client.model.Equipment3rInspectionView

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 *
 *
 * @param id
 * @param unitId
 * @param status
 * @param customerName
 * @param siteReference
 * @param monthlyRateMinor
 * @param durationMonths
 * @param currencyCode
 * @param branchId
 * @param inspections
 * @param createdBy
 * @param createdAt
 * @param updatedAt
 * @param replayed Present and true only on an idempotent replay
 * @param approval
 * @param dispatch
 * @param handover
 * @param returnedAt
 * @param assessment
 * @param dispositionId
 */
@Serializable

data class Equipment3rCaseDetailView (

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @Contextual @SerialName(value = "unitId")
    val unitId: java.util.UUID,

    @SerialName(value = "status")
    val status: Equipment3rCaseDetailView.Status,

    @SerialName(value = "customerName")
    val customerName: kotlin.String,

    @SerialName(value = "siteReference")
    val siteReference: kotlin.String,

    @SerialName(value = "monthlyRateMinor")
    val monthlyRateMinor: kotlin.Long,

    @SerialName(value = "durationMonths")
    val durationMonths: kotlin.Int,

    @SerialName(value = "currencyCode")
    val currencyCode: Equipment3rCaseDetailView.CurrencyCode,

    @Contextual @SerialName(value = "branchId")
    val branchId: java.util.UUID,

    @SerialName(value = "inspections")
    val inspections: kotlin.collections.List<Equipment3rInspectionView>,

    @Contextual @SerialName(value = "createdBy")
    val createdBy: java.util.UUID,

    @Contextual @SerialName(value = "createdAt")
    val createdAt: java.time.OffsetDateTime,

    @Contextual @SerialName(value = "updatedAt")
    val updatedAt: java.time.OffsetDateTime,

    /* Present and true only on an idempotent replay */
    @SerialName(value = "replayed")
    val replayed: kotlin.Boolean? = null,

    @SerialName(value = "approval")
    val approval: Equipment3rCaseDetailViewAllOfApproval? = null,

    @SerialName(value = "dispatch")
    val dispatch: Equipment3rCaseDetailViewAllOfDispatch? = null,

    @SerialName(value = "handover")
    val handover: Equipment3rCaseDetailViewAllOfHandover? = null,

    @Contextual @SerialName(value = "returnedAt")
    val returnedAt: java.time.OffsetDateTime? = null,

    @SerialName(value = "assessment")
    val assessment: Equipment3rCaseDetailViewAllOfAssessment? = null,

    @Contextual @SerialName(value = "dispositionId")
    val dispositionId: java.util.UUID? = null

) {

    /**
     *
     *
     * Values: QUOTED,APPROVED,DECLINED,DISPATCHED,HANDED_OVER,RETURNED,CLOSED
     */
    @Serializable
    enum class Status(val value: kotlin.String) {
        @SerialName(value = "QUOTED") QUOTED("QUOTED"),
        @SerialName(value = "APPROVED") APPROVED("APPROVED"),
        @SerialName(value = "DECLINED") DECLINED("DECLINED"),
        @SerialName(value = "DISPATCHED") DISPATCHED("DISPATCHED"),
        @SerialName(value = "HANDED_OVER") HANDED_OVER("HANDED_OVER"),
        @SerialName(value = "RETURNED") RETURNED("RETURNED"),
        @SerialName(value = "CLOSED") CLOSED("CLOSED");
    }
    /**
     *
     *
     * Values: KRW
     */
    @Serializable
    enum class CurrencyCode(val value: kotlin.String) {
        @SerialName(value = "KRW") KRW("KRW");
    }

}
