/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.maintenance.api.client.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 *
 *
 * @param version
 * @param status
 * @param content
 * @param createdAt
 * @param sourceVersion
 * @param createdBy
 */
@Serializable

data class EquipmentVersion (

    @SerialName(value = "version")
    val version: kotlin.Int,

    @SerialName(value = "status")
    val status: EquipmentVersion.Status,

    @Contextual @SerialName(value = "content")
    val content: kotlin.collections.Map<kotlin.String, kotlinx.serialization.json.JsonElement>,

    @Contextual @SerialName(value = "createdAt")
    val createdAt: java.time.OffsetDateTime,

    @SerialName(value = "sourceVersion")
    val sourceVersion: kotlin.Int? = null,

    @Contextual @SerialName(value = "createdBy")
    val createdBy: java.util.UUID? = null

) {

    /**
     *
     *
     * Values: CAPTURED,ROLLBACK
     */
    @Serializable
    enum class Status(val value: kotlin.String) {
        @SerialName(value = "CAPTURED") CAPTURED("CAPTURED"),
        @SerialName(value = "ROLLBACK") ROLLBACK("ROLLBACK");
    }

}
