/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.maintenance.api.client.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 *
 *
 * @param carrierName
 * @param vehicleReference
 * @param dispatchedAt
 */
@Serializable

data class Equipment3rCaseDetailViewAllOfDispatch (

    @SerialName(value = "carrierName")
    val carrierName: kotlin.String? = null,

    @SerialName(value = "vehicleReference")
    val vehicleReference: kotlin.String? = null,

    @Contextual @SerialName(value = "dispatchedAt")
    val dispatchedAt: java.time.OffsetDateTime? = null

) {


}
