/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.maintenance.api.client.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 *
 *
 * @param code
 * @param message
 * @param reasons Stable machine-readable reasons for review-required conflicts, when applicable.
 * @param currentKeyWriteRevision
 */
@Serializable

data class ErrorBodyError (

    @SerialName(value = "code")
    val code: kotlin.String,

    @SerialName(value = "message")
    val message: kotlin.String,

    /* Stable machine-readable reasons for review-required conflicts, when applicable. */
    @SerialName(value = "reasons")
    val reasons: kotlin.collections.List<kotlin.String>? = null,

    @SerialName(value = "current_key_write_revision")
    val currentKeyWriteRevision: kotlin.Long? = null

) {


}
