/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.maintenance.api.client.model

import com.maintenance.api.client.model.EvaluationGoal
import com.maintenance.api.client.model.EvaluationGrade
import com.maintenance.api.client.model.EvaluationReview
import com.maintenance.api.client.model.EvaluationSubjectState

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 *
 *
 * @param id
 * @param cycleId
 * @param employeeId
 * @param employeeName
 * @param orgUnit
 * @param managerUserId
 * @param state
 * @param finalGrade
 * @param rvCode
 * @param goals
 * @param reviews
 * @param calibratedGrade
 * @param calibrationReason
 * @param calibratedBy
 * @param calibratedAt
 * @param finalizedAt
 */
@Serializable

data class EvaluationSubjectDetail (

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @Contextual @SerialName(value = "cycle_id")
    val cycleId: java.util.UUID,

    @Contextual @SerialName(value = "employee_id")
    val employeeId: java.util.UUID,

    @SerialName(value = "employee_name")
    val employeeName: kotlin.String,

    @SerialName(value = "org_unit")
    val orgUnit: kotlin.String?,

    @Contextual @SerialName(value = "manager_user_id")
    val managerUserId: java.util.UUID,

    @Contextual @SerialName(value = "state")
    val state: EvaluationSubjectState,

    @Contextual @SerialName(value = "final_grade")
    val finalGrade: EvaluationGrade?,

    @SerialName(value = "rv_code")
    val rvCode: kotlin.String?,

    @SerialName(value = "goals")
    val goals: kotlin.collections.List<EvaluationGoal>,

    @SerialName(value = "reviews")
    val reviews: kotlin.collections.List<EvaluationReview>,

    @Contextual @SerialName(value = "calibrated_grade")
    val calibratedGrade: EvaluationGrade?,

    @SerialName(value = "calibration_reason")
    val calibrationReason: kotlin.String?,

    @Contextual @SerialName(value = "calibrated_by")
    val calibratedBy: java.util.UUID?,

    @Contextual @SerialName(value = "calibrated_at")
    val calibratedAt: java.time.OffsetDateTime?,

    @Contextual @SerialName(value = "finalized_at")
    val finalizedAt: java.time.OffsetDateTime?

) {


}
