/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.maintenance.api.client.model


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable


/**
 *
 *
 * Values: RECORD_ARCHIVE,INBOX_DOC,MAIL_ATTACHMENT,INGEST_JOB,WORK_ORDER_EVIDENCE_MEDIA,EXTERNAL_DOCUMENT
 */
@Serializable
enum class EvidenceSourceType(val value: kotlin.String) {

    @SerialName(value = "record_archive")
    RECORD_ARCHIVE("record_archive"),

    @SerialName(value = "inbox_doc")
    INBOX_DOC("inbox_doc"),

    @SerialName(value = "mail_attachment")
    MAIL_ATTACHMENT("mail_attachment"),

    @SerialName(value = "ingest_job")
    INGEST_JOB("ingest_job"),

    @SerialName(value = "work_order_evidence_media")
    WORK_ORDER_EVIDENCE_MEDIA("work_order_evidence_media"),

    @SerialName(value = "external_document")
    EXTERNAL_DOCUMENT("external_document");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is EvidenceSourceType) "$data" else null

        /**
         * Returns a valid [EvidenceSourceType] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): EvidenceSourceType? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}
