/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.maintenance.api.client.model

import com.maintenance.api.client.model.EvidenceObjectView

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 *
 *
 * @param items
 * @param limit
 * @param offset
 * @param total
 * @param asOf Immutable evidence-register sequence that fences every row in this response.
 * @param nextCursor Opaque unpadded-base64url continuation token, or null at the end of the snapshot.
 */
@Serializable

data class EvidenceObjectPage (

    @SerialName(value = "items")
    val items: kotlin.collections.List<EvidenceObjectView>,

    @SerialName(value = "limit")
    val limit: kotlin.Long,

    @SerialName(value = "offset")
    val offset: kotlin.Long,

    @SerialName(value = "total")
    val total: kotlin.Long,

    /* Immutable evidence-register sequence that fences every row in this response. */
    @SerialName(value = "as_of")
    val asOf: kotlin.Long,

    /* Opaque unpadded-base64url continuation token, or null at the end of the snapshot. */
    @SerialName(value = "next_cursor")
    val nextCursor: kotlin.String?

) {


}
