/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.maintenance.api.client.model

import com.maintenance.api.client.model.CustodyEventView
import com.maintenance.api.client.model.EvidenceCopyView
import com.maintenance.api.client.model.EvidenceExportView
import com.maintenance.api.client.model.EvidenceObjectView
import com.maintenance.api.client.model.LegalHoldRecordView
import com.maintenance.api.client.model.TimestampAuthorityProofView

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 *
 *
 * @param `object`
 * @param copies
 * @param tsaProofs
 * @param custodyHistory
 * @param legalHolds
 * @param exports
 */
@Serializable

data class EvidenceObjectDetail (

    @SerialName(value = "object")
    val `object`: EvidenceObjectView,

    @SerialName(value = "copies")
    val copies: kotlin.collections.List<EvidenceCopyView>,

    @SerialName(value = "tsa_proofs")
    val tsaProofs: kotlin.collections.List<TimestampAuthorityProofView>,

    @SerialName(value = "custody_history")
    val custodyHistory: kotlin.collections.List<CustodyEventView>,

    @SerialName(value = "legal_holds")
    val legalHolds: kotlin.collections.List<LegalHoldRecordView>,

    @SerialName(value = "exports")
    val exports: kotlin.collections.List<EvidenceExportView>

) {


}
