/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.maintenance.api.client.model

import com.maintenance.api.client.model.DepreciationMethod

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 *
 *
 * @param depreciationMethod
 * @param usefulLifeMonths
 * @param residualRateBps
 * @param decliningBalanceRateBps
 * @param managementFeeRateBps
 * @param profitRateBps
 * @param floorNegativeQuoteResidual
 * @param executiveApprovalThresholdWon
 */
@Serializable

data class FinancialConfigSnapshot (

    @Contextual @SerialName(value = "depreciation_method")
    val depreciationMethod: DepreciationMethod,

    @SerialName(value = "useful_life_months")
    val usefulLifeMonths: kotlin.Int,

    @SerialName(value = "residual_rate_bps")
    val residualRateBps: kotlin.Int,

    @SerialName(value = "declining_balance_rate_bps")
    val decliningBalanceRateBps: kotlin.Int,

    @SerialName(value = "management_fee_rate_bps")
    val managementFeeRateBps: kotlin.Int,

    @SerialName(value = "profit_rate_bps")
    val profitRateBps: kotlin.Int,

    @SerialName(value = "floor_negative_quote_residual")
    val floorNegativeQuoteResidual: kotlin.Boolean,

    @SerialName(value = "executive_approval_threshold_won")
    val executiveApprovalThresholdWon: kotlin.Long

) {


}
