/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.maintenance.api.client.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 *
 *
 * @param requestRef
 * @param kind
 * @param requestedBy
 * @param decision
 */
@Serializable

data class GovernanceDecideApprovalRequest (

    @Contextual @SerialName(value = "request_ref")
    val requestRef: java.util.UUID,

    @SerialName(value = "kind")
    val kind: kotlin.String,

    @Contextual @SerialName(value = "requested_by")
    val requestedBy: java.util.UUID,

    @SerialName(value = "decision")
    val decision: GovernanceDecideApprovalRequest.Decision

) {

    /**
     *
     *
     * Values: APPROVED,REJECTED
     */
    @Serializable
    enum class Decision(val value: kotlin.String) {
        @SerialName(value = "approved") APPROVED("approved"),
        @SerialName(value = "rejected") REJECTED("rejected");
    }

}
