/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.maintenance.api.client.model

import com.maintenance.api.client.model.FindingSeverity
import com.maintenance.api.client.model.FindingStatus

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * A governance finding raised by the integrity engine (#34). Findings are \"검토 필요\" (review needed) — e.g. a self-approval record (detector_id `anomaly.self_approval`) or a price anomaly (`anomaly.price_outlier`) — and are NOT accusations of wrongdoing.
 *
 * @param id
 * @param orgId
 * @param detectorId Dot-namespaced detector identity, e.g. `anomaly.self_approval` or `anomaly.price_outlier`.
 * @param entityType The domain entity the finding concerns, e.g. `financial_purchase_request`.
 * @param entityId Identifier of the entity the finding concerns.
 * @param score Non-negative detector score; the severity enum is the primary triage signal.
 * @param severity
 * @param evidence Detector-specific evidence bag. For `anomaly.self_approval` this includes action, requested_by, submitted_by, approver, and exemption_reason (org_lead_exempt or super_admin_exempt).
 * @param status
 * @param detectedAt
 * @param createdAt
 * @param updatedAt
 * @param sourceAuditEventId Audit event that triggered the finding (OnWrite detectors); may be null.
 * @param subjectUserId The user whose action was flagged (e.g. the self-approver). Null for non-person findings. A raw id; resolve to a display name in the UI.
 * @param reviewedBy The reviewer who triaged the finding; null until triaged.
 * @param reviewedAt
 * @param reviewMemo Reviewer memo recorded at triage; required when dismissing or escalating.
 */
@Serializable

data class GovernanceFinding (

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @Contextual @SerialName(value = "org_id")
    val orgId: java.util.UUID,

    /* Dot-namespaced detector identity, e.g. `anomaly.self_approval` or `anomaly.price_outlier`. */
    @SerialName(value = "detector_id")
    val detectorId: kotlin.String,

    /* The domain entity the finding concerns, e.g. `financial_purchase_request`. */
    @SerialName(value = "entity_type")
    val entityType: kotlin.String,

    /* Identifier of the entity the finding concerns. */
    @SerialName(value = "entity_id")
    val entityId: kotlin.String,

    /* Non-negative detector score; the severity enum is the primary triage signal. */
    @SerialName(value = "score")
    val score: kotlin.Double,

    @Contextual @SerialName(value = "severity")
    val severity: FindingSeverity,

    /* Detector-specific evidence bag. For `anomaly.self_approval` this includes action, requested_by, submitted_by, approver, and exemption_reason (org_lead_exempt or super_admin_exempt). */
    @Contextual @SerialName(value = "evidence")
    val evidence: kotlin.collections.Map<kotlin.String, kotlinx.serialization.json.JsonElement>,

    @Contextual @SerialName(value = "status")
    val status: FindingStatus,

    @Contextual @SerialName(value = "detected_at")
    val detectedAt: java.time.OffsetDateTime,

    @Contextual @SerialName(value = "created_at")
    val createdAt: java.time.OffsetDateTime,

    @Contextual @SerialName(value = "updated_at")
    val updatedAt: java.time.OffsetDateTime,

    /* Audit event that triggered the finding (OnWrite detectors); may be null. */
    @Contextual @SerialName(value = "source_audit_event_id")
    val sourceAuditEventId: java.util.UUID? = null,

    /* The user whose action was flagged (e.g. the self-approver). Null for non-person findings. A raw id; resolve to a display name in the UI. */
    @Contextual @SerialName(value = "subject_user_id")
    val subjectUserId: java.util.UUID? = null,

    /* The reviewer who triaged the finding; null until triaged. */
    @Contextual @SerialName(value = "reviewed_by")
    val reviewedBy: java.util.UUID? = null,

    @Contextual @SerialName(value = "reviewed_at")
    val reviewedAt: java.time.OffsetDateTime? = null,

    /* Reviewer memo recorded at triage; required when dismissing or escalating. */
    @SerialName(value = "review_memo")
    val reviewMemo: kotlin.String? = null

) {


}
