/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.maintenance.api.client.model

import com.maintenance.api.client.model.InventoryConsumptionSource

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 *
 *
 * @param id
 * @param itemId
 * @param ivCode
 * @param branchId
 * @param stockLocationId
 * @param source
 * @param quantityBeforeMilli
 * @param quantityConsumedMilli
 * @param quantityAfterMilli
 * @param consumedBy
 * @param occurredAt
 * @param createdAt
 * @param unitCostWon
 * @param costWon
 * @param memo
 */
@Serializable

data class InventoryConsumptionEvent (

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @Contextual @SerialName(value = "item_id")
    val itemId: java.util.UUID,

    @SerialName(value = "iv_code")
    val ivCode: kotlin.String,

    @Contextual @SerialName(value = "branch_id")
    val branchId: java.util.UUID,

    @Contextual @SerialName(value = "stock_location_id")
    val stockLocationId: java.util.UUID,

    @SerialName(value = "source")
    val source: InventoryConsumptionSource,

    @SerialName(value = "quantity_before_milli")
    val quantityBeforeMilli: kotlin.Long,

    @SerialName(value = "quantity_consumed_milli")
    val quantityConsumedMilli: kotlin.Long,

    @SerialName(value = "quantity_after_milli")
    val quantityAfterMilli: kotlin.Long,

    @Contextual @SerialName(value = "consumed_by")
    val consumedBy: java.util.UUID,

    @Contextual @SerialName(value = "occurred_at")
    val occurredAt: java.time.OffsetDateTime,

    @Contextual @SerialName(value = "created_at")
    val createdAt: java.time.OffsetDateTime,

    @SerialName(value = "unit_cost_won")
    val unitCostWon: kotlin.Long? = null,

    @SerialName(value = "cost_won")
    val costWon: kotlin.Long? = null,

    @SerialName(value = "memo")
    val memo: kotlin.String? = null

) {


}
