/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.maintenance.api.client.model

import com.maintenance.api.client.model.InventoryConsumptionSourceOneOf
import com.maintenance.api.client.model.InventoryConsumptionSourceOneOf1

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 *
 *
 * @param kind
 * @param workOrderId
 * @param dispatchId
 */
@Serializable

data class InventoryConsumptionSource (

    @SerialName(value = "kind")
    val kind: InventoryConsumptionSource.Kind,

    @Contextual @SerialName(value = "work_order_id")
    val workOrderId: java.util.UUID,

    @Contextual @SerialName(value = "dispatch_id")
    val dispatchId: java.util.UUID

) {

    /**
     *
     *
     * Values: P1_DISPATCH
     */
    @Serializable
    enum class Kind(val value: kotlin.String) {
        @SerialName(value = "p1_dispatch") P1_DISPATCH("p1_dispatch");
    }

}
