/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.maintenance.api.client.model

import com.maintenance.api.client.model.LeaveChargeReviewReason

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * One leave request in the approval queue (결재함 leave variant).
 *
 * @param id
 * @param branchId
 * @param requesterUserId
 * @param subjectEmployeeId
 * @param leaveType
 * @param days Non-null legacy compatibility projection; never authoritative for new approvals.
 * @param chargeUnits Exact resolved charge; null while review is required or no charge applies.
 * @param chargeState
 * @param chargeReviewReasons
 * @param requestVersion Mutable request/workflow CAS token; submit as expected_version for resolve or decide.
 * @param chargeVersion Monotonic immutable charge-evidence revision counter; decisions do not advance it and it is never a request mutation precondition.
 * @param startDate
 * @param endDate
 * @param reason
 * @param status
 * @param decidedBy
 * @param decidedAt
 * @param createdAt
 * @param chargeDigest Server digest of the immutable resolution snapshot, when resolved.
 * @param chargeResolvedBy
 * @param chargeResolutionOrigin Provenance of the current immutable charge snapshot, when one exists.
 * @param partialDayPeriod
 * @param decisionComment Mandatory on return/reject; present only when set.
 * @param apRunId The engine AP- run, when the submittable definition exists.
 */
@Serializable

data class LeaveRequestV2View (

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @Contextual @SerialName(value = "branch_id")
    val branchId: java.util.UUID,

    @Contextual @SerialName(value = "requester_user_id")
    val requesterUserId: java.util.UUID,

    @Contextual @SerialName(value = "subject_employee_id")
    val subjectEmployeeId: java.util.UUID,

    @SerialName(value = "leave_type")
    val leaveType: LeaveRequestV2View.LeaveType,

    /* Non-null legacy compatibility projection; never authoritative for new approvals. */
    @SerialName(value = "days")
    @Deprecated(message = "This property is deprecated.")
    val days: kotlin.Double,

    /* Exact resolved charge; null while review is required or no charge applies. */
    @SerialName(value = "charge_units")
    val chargeUnits: kotlin.String?,

    @SerialName(value = "charge_state")
    val chargeState: LeaveRequestV2View.ChargeState,

    @SerialName(value = "charge_review_reasons")
    val chargeReviewReasons: kotlin.collections.List<@Contextual LeaveChargeReviewReason>,

    /* Mutable request/workflow CAS token; submit as expected_version for resolve or decide. */
    @SerialName(value = "request_version")
    val requestVersion: kotlin.Long,

    /* Monotonic immutable charge-evidence revision counter; decisions do not advance it and it is never a request mutation precondition. */
    @SerialName(value = "charge_version")
    val chargeVersion: kotlin.Long,

    @Contextual @SerialName(value = "start_date")
    val startDate: java.time.LocalDate,

    @Contextual @SerialName(value = "end_date")
    val endDate: java.time.LocalDate,

    @SerialName(value = "reason")
    val reason: kotlin.String,

    @SerialName(value = "status")
    val status: LeaveRequestV2View.Status,

    @Contextual @SerialName(value = "decided_by")
    val decidedBy: java.util.UUID?,

    @Contextual @SerialName(value = "decided_at")
    val decidedAt: java.time.OffsetDateTime?,

    @Contextual @SerialName(value = "created_at")
    val createdAt: java.time.OffsetDateTime,

    /* Server digest of the immutable resolution snapshot, when resolved. */
    @SerialName(value = "charge_digest")
    val chargeDigest: kotlin.String? = null,

    @Contextual @SerialName(value = "charge_resolved_by")
    val chargeResolvedBy: java.util.UUID? = null,

    /* Provenance of the current immutable charge snapshot, when one exists. */
    @SerialName(value = "charge_resolution_origin")
    val chargeResolutionOrigin: LeaveRequestV2View.ChargeResolutionOrigin? = null,

    @SerialName(value = "partial_day_period")
    val partialDayPeriod: LeaveRequestV2View.PartialDayPeriod? = null,

    /* Mandatory on return/reject; present only when set. */
    @SerialName(value = "decision_comment")
    val decisionComment: kotlin.String? = null,

    /* The engine AP- run, when the submittable definition exists. */
    @Contextual @SerialName(value = "ap_run_id")
    val apRunId: java.util.UUID? = null

) {

    /**
     *
     *
     * Values: ANNUAL,HALF_DAY
     */
    @Serializable
    enum class LeaveType(val value: kotlin.String) {
        @SerialName(value = "annual") ANNUAL("annual"),
        @SerialName(value = "half_day") HALF_DAY("half_day");
    }
    /**
     *
     *
     * Values: REVIEW_REQUIRED,RESOLVED,NOT_REQUIRED,LEGACY_UNVERIFIED
     */
    @Serializable
    enum class ChargeState(val value: kotlin.String) {
        @SerialName(value = "review_required") REVIEW_REQUIRED("review_required"),
        @SerialName(value = "resolved") RESOLVED("resolved"),
        @SerialName(value = "not_required") NOT_REQUIRED("not_required"),
        @SerialName(value = "legacy_unverified") LEGACY_UNVERIFIED("legacy_unverified");
    }
    /**
     *
     *
     * Values: PENDING,APPROVED,RETURNED,REJECTED
     */
    @Serializable
    enum class Status(val value: kotlin.String) {
        @SerialName(value = "pending") PENDING("pending"),
        @SerialName(value = "approved") APPROVED("approved"),
        @SerialName(value = "returned") RETURNED("returned"),
        @SerialName(value = "rejected") REJECTED("rejected");
    }
    /**
     * Provenance of the current immutable charge snapshot, when one exists.
     *
     * Values: AUTOMATED,MANUAL
     */
    @Serializable
    enum class ChargeResolutionOrigin(val value: kotlin.String) {
        @SerialName(value = "automated") AUTOMATED("automated"),
        @SerialName(value = "manual") MANUAL("manual");
    }
    /**
     *
     *
     * Values: AM,PM
     */
    @Serializable
    enum class PartialDayPeriod(val value: kotlin.String) {
        @SerialName(value = "am") AM("am"),
        @SerialName(value = "pm") PM("pm");
    }

}
