/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.maintenance.api.client.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 *
 *
 * @param id
 * @param employeeId
 * @param leaveType
 * @param reason
 * @param startDate
 * @param endDate
 * @param status
 * @param requestedBy
 * @param requestedAt
 * @param employeeName
 * @param branchId
 * @param note
 * @param decidedBy
 * @param decidedAt
 * @param decisionNote
 */
@Serializable

data class LeaveRequest (

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @Contextual @SerialName(value = "employee_id")
    val employeeId: java.util.UUID,

    @SerialName(value = "leave_type")
    val leaveType: kotlin.String,

    @SerialName(value = "reason")
    val reason: kotlin.String,

    @Contextual @SerialName(value = "start_date")
    val startDate: java.time.LocalDate,

    @Contextual @SerialName(value = "end_date")
    val endDate: java.time.LocalDate,

    @SerialName(value = "status")
    val status: LeaveRequest.Status,

    @Contextual @SerialName(value = "requested_by")
    val requestedBy: java.util.UUID,

    @Contextual @SerialName(value = "requested_at")
    val requestedAt: java.time.OffsetDateTime,

    @SerialName(value = "employee_name")
    val employeeName: kotlin.String? = null,

    @Contextual @SerialName(value = "branch_id")
    val branchId: java.util.UUID? = null,

    @SerialName(value = "note")
    val note: kotlin.String? = null,

    @Contextual @SerialName(value = "decided_by")
    val decidedBy: java.util.UUID? = null,

    @Contextual @SerialName(value = "decided_at")
    val decidedAt: java.time.OffsetDateTime? = null,

    @SerialName(value = "decision_note")
    val decisionNote: kotlin.String? = null

) {

    /**
     *
     *
     * Values: DRAFT,SUBMITTED,APPROVED,REJECTED
     */
    @Serializable
    enum class Status(val value: kotlin.String) {
        @SerialName(value = "DRAFT") DRAFT("DRAFT"),
        @SerialName(value = "SUBMITTED") SUBMITTED("SUBMITTED"),
        @SerialName(value = "APPROVED") APPROVED("APPROVED"),
        @SerialName(value = "REJECTED") REJECTED("REJECTED");
    }

}
