/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.maintenance.api.client.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * A 노무수령거부 notice served after a round-2 promotion.
 *
 * @param branchId
 * @param targetUserId
 * @param targetEmployeeId
 * @param targetName
 * @param unusedDays
 */
@Serializable

data class LeaveRefusalRequest (

    @Contextual @SerialName(value = "branch_id")
    val branchId: java.util.UUID,

    @Contextual @SerialName(value = "target_user_id")
    val targetUserId: java.util.UUID,

    @Contextual @SerialName(value = "target_employee_id")
    val targetEmployeeId: java.util.UUID,

    @SerialName(value = "target_name")
    val targetName: kotlin.String,

    @SerialName(value = "unused_days")
    val unusedDays: kotlin.Double? = null

) {


}
