/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.maintenance.api.client.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * One employee's annual-leave balance row (직원별 연차 현황).
 *
 * @param employeeId
 * @param name
 * @param team
 * @param grant
 * @param used
 * @param left
 * @param tone Bar color / 촉진 bucket — one of ok, promote, low.
 */
@Serializable

data class LeaveRosterEntry (

    @Contextual @SerialName(value = "employee_id")
    val employeeId: java.util.UUID,

    @SerialName(value = "name")
    val name: kotlin.String,

    @SerialName(value = "team")
    val team: kotlin.String?,

    @SerialName(value = "grant")
    val grant: kotlin.Double,

    @SerialName(value = "used")
    val used: kotlin.Double,

    @SerialName(value = "left")
    val left: kotlin.Double,

    /* Bar color / 촉진 bucket — one of ok, promote, low. */
    @SerialName(value = "tone")
    val tone: LeaveRosterEntry.Tone

) {

    /**
     * Bar color / 촉진 bucket — one of ok, promote, low.
     *
     * Values: OK,PROMOTE,LOW
     */
    @Serializable
    enum class Tone(val value: kotlin.String) {
        @SerialName(value = "ok") OK("ok"),
        @SerialName(value = "promote") PROMOTE("promote"),
        @SerialName(value = "low") LOW("low");
    }

}
