/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.maintenance.api.client.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * A §61 연차 사용 촉진 push to a target employee.
 *
 * @param branchId
 * @param targetUserId
 * @param targetEmployeeId
 * @param targetName
 * @param round §61 round — 1 (사용 촉구) or 2 (시기 지정).
 * @param unusedDays Unused annual-leave days motivating the push.
 */
@Serializable

data class LeavePromotionRequest (

    @Contextual @SerialName(value = "branch_id")
    val branchId: java.util.UUID,

    @Contextual @SerialName(value = "target_user_id")
    val targetUserId: java.util.UUID,

    @Contextual @SerialName(value = "target_employee_id")
    val targetEmployeeId: java.util.UUID,

    @SerialName(value = "target_name")
    val targetName: kotlin.String,

    /* §61 round — 1 (사용 촉구) or 2 (시기 지정). */
    @SerialName(value = "round")
    val round: kotlin.Int,

    /* Unused annual-leave days motivating the push. */
    @SerialName(value = "unused_days")
    val unusedDays: kotlin.Double? = null

) {


}
