/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.maintenance.api.client.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * One photo attached to a sales listing.
 *
 * @param id
 * @param url
 * @param contentType
 * @param altText
 * @param sortOrder
 */
@Serializable

data class ListingMediaView (

    @SerialName(value = "id")
    val id: kotlin.String,

    @SerialName(value = "url")
    val url: kotlin.String,

    @SerialName(value = "content_type")
    val contentType: kotlin.String,

    @SerialName(value = "alt_text")
    val altText: kotlin.String?,

    @SerialName(value = "sort_order")
    val sortOrder: kotlin.Int

) {


}
