/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.maintenance.api.client.model

import com.maintenance.api.client.model.MailAddress
import com.maintenance.api.client.model.MailAttachmentView

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 *
 *
 * @param id
 * @param threadId
 * @param direction IN (mirrored from IMAP) or OUT (sent by the tenant).
 * @param fromAddress
 * @param to
 * @param cc
 * @param subject
 * @param snippet
 * @param seen
 * @param flagged
 * @param answered
 * @param hasAttachments
 * @param receivedAt
 * @param attachments
 * @param messageId
 * @param inReplyTo
 * @param fromName
 * @param bodyText
 * @param bodyHtml The stored HTML body, returned verbatim. The client MUST sanitize it (DOMPurify-class) before rendering.
 */
@Serializable

data class MailMessageView (

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @Contextual @SerialName(value = "thread_id")
    val threadId: java.util.UUID,

    /* IN (mirrored from IMAP) or OUT (sent by the tenant). */
    @SerialName(value = "direction")
    val direction: kotlin.String,

    @SerialName(value = "from_address")
    val fromAddress: kotlin.String,

    @SerialName(value = "to")
    val to: kotlin.collections.List<MailAddress>,

    @SerialName(value = "cc")
    val cc: kotlin.collections.List<MailAddress>,

    @SerialName(value = "subject")
    val subject: kotlin.String,

    @SerialName(value = "snippet")
    val snippet: kotlin.String,

    @SerialName(value = "seen")
    val seen: kotlin.Boolean,

    @SerialName(value = "flagged")
    val flagged: kotlin.Boolean,

    @SerialName(value = "answered")
    val answered: kotlin.Boolean,

    @SerialName(value = "has_attachments")
    val hasAttachments: kotlin.Boolean,

    @Contextual @SerialName(value = "received_at")
    val receivedAt: java.time.OffsetDateTime,

    @SerialName(value = "attachments")
    val attachments: kotlin.collections.List<MailAttachmentView>,

    @SerialName(value = "message_id")
    val messageId: kotlin.String? = null,

    @SerialName(value = "in_reply_to")
    val inReplyTo: kotlin.String? = null,

    @SerialName(value = "from_name")
    val fromName: kotlin.String? = null,

    @SerialName(value = "body_text")
    val bodyText: kotlin.String? = null,

    /* The stored HTML body, returned verbatim. The client MUST sanitize it (DOMPurify-class) before rendering. */
    @SerialName(value = "body_html")
    val bodyHtml: kotlin.String? = null

) {


}
