/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.maintenance.api.client.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 *
 *
 * @param id
 * @param threadId
 * @param branchId
 * @param senderId
 * @param senderName Sender display name, resolved via a same-org LEFT JOIN on users. Null when the sender account no longer exists.
 * @param body
 * @param attachmentEvidenceIds
 * @param readCount Non-sender thread members whose read receipt has reached this message.
 * @param readTargetCount Non-sender thread members expected to read this message.
 * @param sentAt
 * @param createdAt
 */
@Serializable

data class MessengerMessageSummary (

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @Contextual @SerialName(value = "thread_id")
    val threadId: java.util.UUID,

    @Contextual @SerialName(value = "branch_id")
    val branchId: java.util.UUID,

    @Contextual @SerialName(value = "sender_id")
    val senderId: java.util.UUID,

    /* Sender display name, resolved via a same-org LEFT JOIN on users. Null when the sender account no longer exists. */
    @SerialName(value = "sender_name")
    val senderName: kotlin.String?,

    @SerialName(value = "body")
    val body: kotlin.String,

    @SerialName(value = "attachment_evidence_ids")
    val attachmentEvidenceIds: kotlin.collections.List<@Contextual java.util.UUID>,

    /* Non-sender thread members whose read receipt has reached this message. */
    @SerialName(value = "read_count")
    val readCount: kotlin.Long,

    /* Non-sender thread members expected to read this message. */
    @SerialName(value = "read_target_count")
    val readTargetCount: kotlin.Long,

    @Contextual @SerialName(value = "sent_at")
    val sentAt: java.time.OffsetDateTime,

    @Contextual @SerialName(value = "created_at")
    val createdAt: java.time.OffsetDateTime

) {


}
