/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.maintenance.api.client.model

import com.maintenance.api.client.model.MobilePasskeyStepUpBinding

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 *
 *
 * @param ceremonyId
 * @param challenge
 * @param expiresAt
 * @param binding
 */
@Serializable

data class MobilePasskeyStepUpStartResponse (

    @Contextual @SerialName(value = "ceremony_id")
    val ceremonyId: java.util.UUID,

    @Contextual @SerialName(value = "challenge")
    val challenge: kotlin.collections.Map<kotlin.String, kotlinx.serialization.json.JsonElement>,

    @Contextual @SerialName(value = "expires_at")
    val expiresAt: java.time.OffsetDateTime,

    @SerialName(value = "binding")
    val binding: MobilePasskeyStepUpBinding

) {


}
