/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.maintenance.api.client.model

import com.maintenance.api.client.model.MobilePasskeyStepUpEnvelope

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 *
 *
 * @param selectedOptionIds
 * @param stepUp
 */
@Serializable

data class MobileVotePollRequest (

    @SerialName(value = "selected_option_ids")
    val selectedOptionIds: kotlin.collections.List<@Contextual java.util.UUID>,

    @SerialName(value = "step_up")
    val stepUp: MobilePasskeyStepUpEnvelope

) {


}
