/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.maintenance.api.client.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Compact, kind-agnostic head for any object. exists=false means the object is absent OR outside the caller's scope (indistinguishable, by design). Carries no route/URL — objectRegistry (frontend) is the sole kind->URL authority.
 *
 * @param kind
 * @param id
 * @param exists
 * @param code Canonical issued code if the kind has one (e.g. work-order request_no); absent otherwise.
 * @param title Human display label if available.
 * @param status Domain status string if available.
 */
@Serializable

data class ObjectHead (

    @SerialName(value = "kind")
    val kind: kotlin.String,

    @SerialName(value = "id")
    val id: kotlin.String,

    @SerialName(value = "exists")
    val exists: kotlin.Boolean,

    /* Canonical issued code if the kind has one (e.g. work-order request_no); absent otherwise. */
    @SerialName(value = "code")
    val code: kotlin.String? = null,

    /* Human display label if available. */
    @SerialName(value = "title")
    val title: kotlin.String? = null,

    /* Domain status string if available. */
    @SerialName(value = "status")
    val status: kotlin.String? = null

) {


}
