/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.maintenance.api.client.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 *
 *
 * @param executionId
 * @param actionId
 * @param objectType
 * @param objectId
 * @param status
 * @param auditEventId
 * @param targetHref
 * @param message
 */
@Serializable

data class ObjectActionExecutionResponse (

    @Contextual @SerialName(value = "execution_id")
    val executionId: java.util.UUID,

    @SerialName(value = "action_id")
    val actionId: kotlin.String,

    @SerialName(value = "object_type")
    val objectType: kotlin.String,

    @Contextual @SerialName(value = "object_id")
    val objectId: java.util.UUID,

    @SerialName(value = "status")
    val status: ObjectActionExecutionResponse.Status,

    @Contextual @SerialName(value = "audit_event_id")
    val auditEventId: java.util.UUID,

    @SerialName(value = "target_href")
    val targetHref: kotlin.String,

    @SerialName(value = "message")
    val message: kotlin.String

) {

    /**
     *
     *
     * Values: SUCCEEDED
     */
    @Serializable
    enum class Status(val value: kotlin.String) {
        @SerialName(value = "succeeded") SUCCEEDED("succeeded");
    }

}
