/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.maintenance.api.client.model

import com.maintenance.api.client.model.ObjectHead
import com.maintenance.api.client.model.ObjectLinkResponse

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * The bounded, caller-visible neighborhood of an object, walked over object_links. Unresolvable nodes are omitted entirely (never returned as stubs), and edges touching an omitted node are omitted too.
 *
 * @param nodes Every object the caller can resolve, each passed through the same visibility guard as resolveObject.
 * @param edges Links between resolved nodes (the induced subgraph over the visible node set).
 * @param truncated True if the node cap was hit before the walk exhausted the requested depth.
 */
@Serializable

data class ObjectGraphResponse (

    /* Every object the caller can resolve, each passed through the same visibility guard as resolveObject. */
    @SerialName(value = "nodes")
    val nodes: kotlin.collections.List<ObjectHead>,

    /* Links between resolved nodes (the induced subgraph over the visible node set). */
    @SerialName(value = "edges")
    val edges: kotlin.collections.List<ObjectLinkResponse>,

    /* True if the node cap was hit before the walk exhausted the requested depth. */
    @SerialName(value = "truncated")
    val truncated: kotlin.Boolean

) {


}
