/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.maintenance.api.client.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 *
 *
 * @param received
 * @param assigned
 * @param inProgress
 * @param completed
 */
@Serializable

data class OpsFunnel (

    @SerialName(value = "received")
    val received: kotlin.Int,

    @SerialName(value = "assigned")
    val assigned: kotlin.Int,

    @SerialName(value = "in_progress")
    val inProgress: kotlin.Int,

    @SerialName(value = "completed")
    val completed: kotlin.Int

) {


}
