/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.maintenance.api.client.model

import com.maintenance.api.client.model.OrgChangeApprovalRoleKey
import com.maintenance.api.client.model.OrgChangeStepDecision

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 *
 *
 * @param id
 * @param stepOrder
 * @param roleKey
 * @param decision
 * @param decidedBy
 * @param decidedAt
 * @param memo
 */
@Serializable

data class OrgChangeApprovalStep (

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @SerialName(value = "stepOrder")
    val stepOrder: kotlin.Int,

    @Contextual @SerialName(value = "roleKey")
    val roleKey: OrgChangeApprovalRoleKey,

    @Contextual @SerialName(value = "decision")
    val decision: OrgChangeStepDecision,

    @Contextual @SerialName(value = "decidedBy")
    val decidedBy: java.util.UUID? = null,

    @Contextual @SerialName(value = "decidedAt")
    val decidedAt: java.time.OffsetDateTime? = null,

    @SerialName(value = "memo")
    val memo: kotlin.String? = null

) {


}
