/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.maintenance.api.client.model

import com.maintenance.api.client.model.OrgProposalOpCreateBranch
import com.maintenance.api.client.model.OrgProposalOpCreateRegion
import com.maintenance.api.client.model.OrgProposalOpCreateSite
import com.maintenance.api.client.model.OrgProposalOpDeactivateBranch
import com.maintenance.api.client.model.OrgProposalOpDeactivateRegion
import com.maintenance.api.client.model.OrgProposalOpReassignOrgUnit
import com.maintenance.api.client.model.OrgProposalOpRenameBranch
import com.maintenance.api.client.model.OrgProposalOpRenameRegion
import com.maintenance.api.client.model.OrgProposalOpUpdateSite
import com.maintenance.api.client.model.OrgProposalReassignScope

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.ExperimentalSerializationApi
import kotlinx.serialization.json.JsonClassDiscriminator

/**
 * One typed sandbox-diff operation, replayed in order at apply time. Internally tagged by `op`; unknown properties are rejected.
 *
 * @param op
 * @param name
 * @param regionId
 * @param branchId
 * @param customerId
 * @param siteId
 * @param fromOrgUnit
 * @param toOrgUnit
 * @param scope
 */
@Serializable


@OptIn(ExperimentalSerializationApi::class)
@JsonClassDiscriminator(discriminator = "op")
sealed class OrgProposalOp {

    @SerialName(value = "op")
    abstract val op: OrgProposalOp.Op
    @SerialName(value = "name")
    abstract val name: kotlin.String
    @Contextual @SerialName(value = "regionId")
    abstract val regionId: java.util.UUID
    @Contextual @SerialName(value = "branchId")
    abstract val branchId: java.util.UUID
    @Contextual @SerialName(value = "customerId")
    abstract val customerId: java.util.UUID
    @Contextual @SerialName(value = "siteId")
    abstract val siteId: java.util.UUID
    @SerialName(value = "fromOrgUnit")
    abstract val fromOrgUnit: kotlin.String
    @SerialName(value = "toOrgUnit")
    abstract val toOrgUnit: kotlin.String
    @SerialName(value = "scope")
    abstract val scope: OrgProposalReassignScope
    /**
     *
     *
     * Values: REASSIGN_ORG_UNIT
     */
    @Serializable
    enum class Op(val value: kotlin.String) {
        @SerialName(value = "REASSIGN_ORG_UNIT") REASSIGN_ORG_UNIT("REASSIGN_ORG_UNIT");
    }

}
