/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.maintenance.api.client.model

import com.maintenance.api.client.model.PolicyRoleResponse
import com.maintenance.api.client.model.PolicyVersionResponse
import com.maintenance.api.client.model.SystemPolicyRoleResponse

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 *
 *
 * @param policyVersion
 * @param systemRoles
 * @param customRoles
 */
@Serializable

data class PolicyRoleCatalogResponse (

    @SerialName(value = "policy_version")
    val policyVersion: PolicyVersionResponse,

    @SerialName(value = "system_roles")
    val systemRoles: kotlin.collections.List<SystemPolicyRoleResponse>,

    @SerialName(value = "custom_roles")
    val customRoles: kotlin.collections.List<PolicyRoleResponse>

) {


}
