/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.maintenance.api.client.model

import com.maintenance.api.client.model.PolicyFeatureGrantPreviewResponse
import com.maintenance.api.client.model.PolicyRoleAssignmentDeltaResponse
import com.maintenance.api.client.model.PolicyRoleImpactResponse

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 *
 *
 * @param userId
 * @param previewReceiptId
 * @param previewReceiptExpiresAt
 * @param effective True when the requested saved assignment set contains at least one ACTIVE custom role that will produce runtime-effective feature grants for the target user's live branch scope. DRAFT/RETIRED roles, unsupported conditions, invalid branch values, and reserved elevated/scope-widening features remain fail-closed.
 * @param systemRoles
 * @param currentSystemRoles System-role set currently persisted on the target before this preview.
 * @param requestedSystemRoles Replacement system-role set covered by the preview receipt. Defaults to the current system roles when omitted.
 * @param currentBranchIds Branch membership set currently persisted on the target before this preview.
 * @param requestedBranchIds Replacement branch membership set covered by the preview receipt. Defaults to the current branch ids when omitted.
 * @param currentRoleIds
 * @param requestedRoleIds
 * @param delta
 * @param customRoles
 * @param featureGrants Effective runtime grant preview. Custom-role rows are included only for runtime_effective custom roles; DRAFT roles, unsupported conditions, branch/team mismatches, and unsupported permissions are reported through custom_roles[].runtime_warnings instead of being shown as grants.
 * @param warnings Preview-level warnings. Includes deterministic custom-role runtime warning codes when any requested role is planning/audit-only.
 */
@Serializable

data class PolicyAssignmentPreviewResponse (

    @Contextual @SerialName(value = "user_id")
    val userId: java.util.UUID,

    @Contextual @SerialName(value = "preview_receipt_id")
    val previewReceiptId: java.util.UUID,

    @Contextual @SerialName(value = "preview_receipt_expires_at")
    val previewReceiptExpiresAt: java.time.OffsetDateTime,

    /* True when the requested saved assignment set contains at least one ACTIVE custom role that will produce runtime-effective feature grants for the target user's live branch scope. DRAFT/RETIRED roles, unsupported conditions, invalid branch values, and reserved elevated/scope-widening features remain fail-closed. */
    @SerialName(value = "effective")
    val effective: kotlin.Boolean,

    @SerialName(value = "system_roles")
    val systemRoles: kotlin.collections.List<kotlin.String>,

    /* System-role set currently persisted on the target before this preview. */
    @SerialName(value = "current_system_roles")
    val currentSystemRoles: kotlin.collections.List<kotlin.String>,

    /* Replacement system-role set covered by the preview receipt. Defaults to the current system roles when omitted. */
    @SerialName(value = "requested_system_roles")
    val requestedSystemRoles: kotlin.collections.List<kotlin.String>,

    /* Branch membership set currently persisted on the target before this preview. */
    @SerialName(value = "current_branch_ids")
    val currentBranchIds: kotlin.collections.List<@Contextual java.util.UUID>,

    /* Replacement branch membership set covered by the preview receipt. Defaults to the current branch ids when omitted. */
    @SerialName(value = "requested_branch_ids")
    val requestedBranchIds: kotlin.collections.List<@Contextual java.util.UUID>,

    @SerialName(value = "current_role_ids")
    val currentRoleIds: kotlin.collections.List<@Contextual java.util.UUID>,

    @SerialName(value = "requested_role_ids")
    val requestedRoleIds: kotlin.collections.List<@Contextual java.util.UUID>,

    @SerialName(value = "delta")
    val delta: PolicyRoleAssignmentDeltaResponse,

    @SerialName(value = "custom_roles")
    val customRoles: kotlin.collections.List<PolicyRoleImpactResponse>,

    /* Effective runtime grant preview. Custom-role rows are included only for runtime_effective custom roles; DRAFT roles, unsupported conditions, branch/team mismatches, and unsupported permissions are reported through custom_roles[].runtime_warnings instead of being shown as grants. */
    @SerialName(value = "feature_grants")
    val featureGrants: kotlin.collections.List<PolicyFeatureGrantPreviewResponse>,

    /* Preview-level warnings. Includes deterministic custom-role runtime warning codes when any requested role is planning/audit-only. */
    @SerialName(value = "warnings")
    val warnings: kotlin.collections.List<kotlin.String>

) {


}
