/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.maintenance.api.client.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 *
 *
 * @param roleId
 * @param roleKey
 * @param displayName
 * @param currentStatus
 * @param requestedStatus
 * @param permissionCount
 * @param conditionCount
 * @param plannedAssignmentCount
 * @param requiresPasskeyStepUp
 * @param effectiveRuntimeChange True when changing this role status would make existing assignments gain or lose runtime-effective custom-role grants on the next request.
 * @param warnings
 */
@Serializable

data class PolicyRoleStatusPreviewResponse (

    @Contextual @SerialName(value = "role_id")
    val roleId: java.util.UUID,

    @SerialName(value = "role_key")
    val roleKey: kotlin.String,

    @SerialName(value = "display_name")
    val displayName: kotlin.String,

    @SerialName(value = "current_status")
    val currentStatus: PolicyRoleStatusPreviewResponse.CurrentStatus,

    @SerialName(value = "requested_status")
    val requestedStatus: PolicyRoleStatusPreviewResponse.RequestedStatus,

    @SerialName(value = "permission_count")
    val permissionCount: kotlin.Long,

    @SerialName(value = "condition_count")
    val conditionCount: kotlin.Long,

    @SerialName(value = "planned_assignment_count")
    val plannedAssignmentCount: kotlin.Long,

    @SerialName(value = "requires_passkey_step_up")
    val requiresPasskeyStepUp: kotlin.Boolean,

    /* True when changing this role status would make existing assignments gain or lose runtime-effective custom-role grants on the next request. */
    @SerialName(value = "effective_runtime_change")
    val effectiveRuntimeChange: kotlin.Boolean,

    @SerialName(value = "warnings")
    val warnings: kotlin.collections.List<PolicyRoleStatusPreviewResponse.Warnings>

) {

    /**
     *
     *
     * Values: DRAFT,ACTIVE,RETIRED
     */
    @Serializable
    enum class CurrentStatus(val value: kotlin.String) {
        @SerialName(value = "DRAFT") DRAFT("DRAFT"),
        @SerialName(value = "ACTIVE") ACTIVE("ACTIVE"),
        @SerialName(value = "RETIRED") RETIRED("RETIRED");
    }
    /**
     *
     *
     * Values: DRAFT,ACTIVE,RETIRED
     */
    @Serializable
    enum class RequestedStatus(val value: kotlin.String) {
        @SerialName(value = "DRAFT") DRAFT("DRAFT"),
        @SerialName(value = "ACTIVE") ACTIVE("ACTIVE"),
        @SerialName(value = "RETIRED") RETIRED("RETIRED");
    }
    /**
     *
     *
     * Values: PASSKEY_STEP_UP_REQUIRED,NO_STATUS_CHANGE,ASSIGNED_USERS_MAY_GAIN_OR_LOSE_RUNTIME_PERMISSIONS,ROLLBACK_DISABLES_ASSIGNED_CUSTOM_ROLE_RUNTIME_GRANTS,RETIRE_DISABLES_ASSIGNED_CUSTOM_ROLE_RUNTIME_GRANTS,PUBLISH_ENABLES_ASSIGNED_CUSTOM_ROLE_RUNTIME_GRANTS
     */
    @Serializable
    enum class Warnings(val value: kotlin.String) {
        @SerialName(value = "passkey_step_up_required") PASSKEY_STEP_UP_REQUIRED("passkey_step_up_required"),
        @SerialName(value = "no_status_change") NO_STATUS_CHANGE("no_status_change"),
        @SerialName(value = "assigned_users_may_gain_or_lose_runtime_permissions") ASSIGNED_USERS_MAY_GAIN_OR_LOSE_RUNTIME_PERMISSIONS("assigned_users_may_gain_or_lose_runtime_permissions"),
        @SerialName(value = "rollback_disables_assigned_custom_role_runtime_grants") ROLLBACK_DISABLES_ASSIGNED_CUSTOM_ROLE_RUNTIME_GRANTS("rollback_disables_assigned_custom_role_runtime_grants"),
        @SerialName(value = "retire_disables_assigned_custom_role_runtime_grants") RETIRE_DISABLES_ASSIGNED_CUSTOM_ROLE_RUNTIME_GRANTS("retire_disables_assigned_custom_role_runtime_grants"),
        @SerialName(value = "publish_enables_assigned_custom_role_runtime_grants") PUBLISH_ENABLES_ASSIGNED_CUSTOM_ROLE_RUNTIME_GRANTS("publish_enables_assigned_custom_role_runtime_grants");
    }

}
