/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.maintenance.api.client.model

import com.maintenance.api.client.model.ProjectionAssumptions

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 *
 *
 * @param pointEstimate Deterministic central projection.
 * @param ci95Low 2.5th percentile of terminal outcomes.
 * @param ci95High 97.5th percentile of terminal outcomes.
 * @param cvar95 EVT-refined expected shortfall of the worst 5% of outcomes.
 * @param assumptions
 */
@Serializable

data class ProjectionResult (

    /* Deterministic central projection. */
    @SerialName(value = "point_estimate")
    val pointEstimate: kotlin.Double,

    /* 2.5th percentile of terminal outcomes. */
    @SerialName(value = "ci95_low")
    val ci95Low: kotlin.Double,

    /* 97.5th percentile of terminal outcomes. */
    @SerialName(value = "ci95_high")
    val ci95High: kotlin.Double,

    /* EVT-refined expected shortfall of the worst 5% of outcomes. */
    @SerialName(value = "cvar95")
    val cvar95: kotlin.Double,

    @SerialName(value = "assumptions")
    val assumptions: ProjectionAssumptions

) {


}
