/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.maintenance.api.client.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 *
 *
 * @param equipmentRequired
 * @param statementEvidenceRequired
 * @param priceAnomaly
 * @param quoteUpdateRequired
 * @param submitBlocked
 * @param messages
 */
@Serializable

data class PurchasePolicySummary (

    @SerialName(value = "equipment_required")
    val equipmentRequired: kotlin.Boolean,

    @SerialName(value = "statement_evidence_required")
    val statementEvidenceRequired: kotlin.Boolean,

    @SerialName(value = "price_anomaly")
    val priceAnomaly: kotlin.Boolean,

    @SerialName(value = "quote_update_required")
    val quoteUpdateRequired: kotlin.Boolean,

    @SerialName(value = "submit_blocked")
    val submitBlocked: kotlin.Boolean,

    @SerialName(value = "messages")
    val messages: kotlin.collections.List<kotlin.String>

) {


}
