/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.maintenance.api.client.model

import com.maintenance.api.client.model.PurchaseStatus

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 *
 *
 * @param id
 * @param branchId
 * @param equipmentId
 * @param statementEvidenceId
 * @param vendorName
 * @param amountWon
 * @param status
 * @param createdAt
 * @param updatedAt
 * @param workOrderId
 * @param expenditureNo
 * @param rejectionMemo
 */
@Serializable

data class PurchaseRequestSummary (

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @Contextual @SerialName(value = "branch_id")
    val branchId: java.util.UUID,

    @Contextual @SerialName(value = "equipment_id")
    val equipmentId: java.util.UUID,

    @Contextual @SerialName(value = "statement_evidence_id")
    val statementEvidenceId: java.util.UUID,

    @SerialName(value = "vendor_name")
    val vendorName: kotlin.String,

    @SerialName(value = "amount_won")
    val amountWon: kotlin.Long,

    @Contextual @SerialName(value = "status")
    val status: PurchaseStatus,

    @Contextual @SerialName(value = "created_at")
    val createdAt: java.time.OffsetDateTime,

    @Contextual @SerialName(value = "updated_at")
    val updatedAt: java.time.OffsetDateTime,

    @Contextual @SerialName(value = "work_order_id")
    val workOrderId: java.util.UUID? = null,

    @SerialName(value = "expenditure_no")
    val expenditureNo: kotlin.String? = null,

    @SerialName(value = "rejection_memo")
    val rejectionMemo: kotlin.String? = null

) {


}
