/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.maintenance.api.client.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 *
 *
 * @param expectedVersion
 * @param idempotencyKey
 * @param outputQuantity
 * @param scrapQuantity
 * @param downtimeMinutes
 * @param qualityEvidenceRef
 * @param qualityPassed
 * @param note
 */
@Serializable

data class RecordProductionOperation (

    @SerialName(value = "expected_version")
    val expectedVersion: kotlin.Int,

    @SerialName(value = "idempotency_key")
    val idempotencyKey: kotlin.String,

    @SerialName(value = "output_quantity")
    val outputQuantity: kotlin.Long,

    @SerialName(value = "scrap_quantity")
    val scrapQuantity: kotlin.Long,

    @SerialName(value = "downtime_minutes")
    val downtimeMinutes: kotlin.Int,

    @SerialName(value = "quality_evidence_ref")
    val qualityEvidenceRef: kotlin.String,

    @SerialName(value = "quality_passed")
    val qualityPassed: kotlin.Boolean,

    @SerialName(value = "note")
    val note: kotlin.String

) {


}
