/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.maintenance.api.client.model

import com.maintenance.api.client.model.RegistryRowError

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 *
 *
 * @param inputRows
 * @param equipmentCount
 * @param added
 * @param updated
 * @param unchanged
 * @param orphaned
 * @param errors
 */
@Serializable

data class RegistryImportReport (

    @SerialName(value = "input_rows")
    val inputRows: kotlin.Int,

    @SerialName(value = "equipment_count")
    val equipmentCount: kotlin.Int,

    @SerialName(value = "added")
    val added: kotlin.Int,

    @SerialName(value = "updated")
    val updated: kotlin.Int,

    @SerialName(value = "unchanged")
    val unchanged: kotlin.Int,

    @SerialName(value = "orphaned")
    val orphaned: kotlin.Int,

    @SerialName(value = "errors")
    val errors: kotlin.collections.List<RegistryRowError>

) {


}
