/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.maintenance.api.client.model

import com.maintenance.api.client.model.QuoteLine

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 *
 *
 * @param id
 * @param branchId
 * @param equipmentId
 * @param acquisitionValue
 * @param currentResidualValue
 * @param effectiveResidualValue
 * @param residualWasFloored
 * @param cumulativeRepairCost
 * @param monthlyTotal
 * @param lines
 * @param createdAt
 */
@Serializable

data class RentalQuoteSummary (

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @Contextual @SerialName(value = "branch_id")
    val branchId: java.util.UUID,

    @Contextual @SerialName(value = "equipment_id")
    val equipmentId: java.util.UUID,

    @SerialName(value = "acquisition_value")
    val acquisitionValue: kotlin.Long,

    @SerialName(value = "current_residual_value")
    val currentResidualValue: kotlin.Long,

    @SerialName(value = "effective_residual_value")
    val effectiveResidualValue: kotlin.Long,

    @SerialName(value = "residual_was_floored")
    val residualWasFloored: kotlin.Boolean,

    @SerialName(value = "cumulative_repair_cost")
    val cumulativeRepairCost: kotlin.Long,

    @SerialName(value = "monthly_total")
    val monthlyTotal: kotlin.Long,

    @SerialName(value = "lines")
    val lines: kotlin.collections.List<QuoteLine>,

    @Contextual @SerialName(value = "created_at")
    val createdAt: java.time.OffsetDateTime

) {


}
