/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.maintenance.api.client.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 *
 *
 * @param employeeId
 * @param effectiveExitDate
 * @param siteManagerNote
 * @param branchId
 * @param absenceAlertId
 */
@Serializable

data class ReportEmployeeExitCaseRequest (

    @Contextual @SerialName(value = "employee_id")
    val employeeId: java.util.UUID,

    @SerialName(value = "effective_exit_date")
    val effectiveExitDate: kotlin.String,

    @SerialName(value = "site_manager_note")
    val siteManagerNote: kotlin.String,

    @Contextual @SerialName(value = "branch_id")
    val branchId: java.util.UUID? = null,

    @Contextual @SerialName(value = "absence_alert_id")
    val absenceAlertId: java.util.UUID? = null

) {


}
