/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.maintenance.api.client.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 *
 *
 * @param releaseCycle
 * @param consoleRouteEvents
 * @param legacyRouteEvents
 * @param rumErrorEvents
 * @param rumPerfP95Ms
 * @param lastEventAt
 */
@Serializable

data class RouteAdoptionMetric (

    @SerialName(value = "release_cycle")
    val releaseCycle: kotlin.String,

    @SerialName(value = "console_route_events")
    val consoleRouteEvents: kotlin.Long,

    @SerialName(value = "legacy_route_events")
    val legacyRouteEvents: kotlin.Long,

    @SerialName(value = "rum_error_events")
    val rumErrorEvents: kotlin.Long,

    @SerialName(value = "rum_perf_p95_ms")
    val rumPerfP95Ms: kotlin.Long?,

    @Contextual @SerialName(value = "last_event_at")
    val lastEventAt: java.time.OffsetDateTime

) {


}
