/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.maintenance.api.client.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 *
 *
 * @param runId
 * @param status
 * @param definitionId
 * @param definitionVersion
 * @param startedAt
 * @param completedAt
 * @param failedAt
 */
@Serializable

data class ScheduleRunItem (

    @Contextual @SerialName(value = "run_id")
    val runId: java.util.UUID,

    @SerialName(value = "status")
    val status: kotlin.String,

    @Contextual @SerialName(value = "definition_id")
    val definitionId: java.util.UUID,

    @SerialName(value = "definition_version")
    val definitionVersion: kotlin.Int,

    @Contextual @SerialName(value = "started_at")
    val startedAt: java.time.OffsetDateTime,

    @Contextual @SerialName(value = "completed_at")
    val completedAt: java.time.OffsetDateTime? = null,

    @Contextual @SerialName(value = "failed_at")
    val failedAt: java.time.OffsetDateTime? = null

) {


}
