/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.maintenance.api.client.model

import com.maintenance.api.client.model.MailAddress
import com.maintenance.api.client.model.MailAttachment

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Compose a message. For reply/forward, in_reply_to is required and references carries the accumulated chain. The From is constrained to the configured account address (it cannot be set here).
 *
 * @param to
 * @param subject
 * @param bodyText
 * @param cc
 * @param bcc
 * @param attachments
 * @param inReplyTo Required for reply/forward — the Message-ID being responded to.
 * @param references
 */
@Serializable

data class SendMailRequest (

    @SerialName(value = "to")
    val to: kotlin.collections.List<MailAddress>,

    @SerialName(value = "subject")
    val subject: kotlin.String,

    @SerialName(value = "body_text")
    val bodyText: kotlin.String,

    @SerialName(value = "cc")
    val cc: kotlin.collections.List<MailAddress>? = null,

    @SerialName(value = "bcc")
    val bcc: kotlin.collections.List<MailAddress>? = null,

    @SerialName(value = "attachments")
    val attachments: kotlin.collections.List<MailAttachment>? = null,

    /* Required for reply/forward — the Message-ID being responded to. */
    @SerialName(value = "in_reply_to")
    val inReplyTo: kotlin.String? = null,

    @SerialName(value = "references")
    val references: kotlin.collections.List<kotlin.String>? = null

) {


}
