/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.maintenance.api.client.model


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable


/**
 *
 *
 * Values: CUSTOMER_ACCEPTED,CUSTOMER_DECLINED
 */
@Serializable
enum class SupportTicketAcceptanceKind(val value: kotlin.String) {

    @SerialName(value = "CUSTOMER_ACCEPTED")
    CUSTOMER_ACCEPTED("CUSTOMER_ACCEPTED"),

    @SerialName(value = "CUSTOMER_DECLINED")
    CUSTOMER_DECLINED("CUSTOMER_DECLINED");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is SupportTicketAcceptanceKind) "$data" else null

        /**
         * Returns a valid [SupportTicketAcceptanceKind] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): SupportTicketAcceptanceKind? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}
