/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.maintenance.api.client.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 *
 *
 * @param id
 * @param ticketId
 * @param authorUserId
 * @param authorName Comment author display name, resolved via a same-org LEFT JOIN on users. Null for an authorless comment or a deleted author.
 * @param body
 * @param isInternalNote
 * @param createdAt
 */
@Serializable

data class SupportTicketComment (

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @Contextual @SerialName(value = "ticket_id")
    val ticketId: java.util.UUID,

    @Contextual @SerialName(value = "author_user_id")
    val authorUserId: java.util.UUID,

    /* Comment author display name, resolved via a same-org LEFT JOIN on users. Null for an authorless comment or a deleted author. */
    @SerialName(value = "author_name")
    val authorName: kotlin.String?,

    @SerialName(value = "body")
    val body: kotlin.String,

    @SerialName(value = "is_internal_note")
    val isInternalNote: kotlin.Boolean,

    @Contextual @SerialName(value = "created_at")
    val createdAt: java.time.OffsetDateTime

) {


}
