/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.maintenance.api.client.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 *
 *
 * @param accessToken
 * @param tokenType
 * @param refreshExpiresAt
 * @param requiresPasskeySetup True when the refreshed session belongs to an OTP-signed-in user who still has no passkey. Web clients must keep routing this session to initial passkey enrollment after a reload; passkey-authenticated sessions return false.
 * @param refreshToken The opaque rotating refresh token in the body transport (mobile). It is null in the cookie transport (web), where the token is set as an HttpOnly `mnt_refresh` cookie and must never reach web JS.
 */
@Serializable

data class TokenPairResponse (

    @SerialName(value = "access_token")
    val accessToken: kotlin.String,

    @SerialName(value = "token_type")
    val tokenType: TokenPairResponse.TokenType,

    @Contextual @SerialName(value = "refresh_expires_at")
    val refreshExpiresAt: java.time.OffsetDateTime,

    /* True when the refreshed session belongs to an OTP-signed-in user who still has no passkey. Web clients must keep routing this session to initial passkey enrollment after a reload; passkey-authenticated sessions return false. */
    @SerialName(value = "requires_passkey_setup")
    val requiresPasskeySetup: kotlin.Boolean,

    /* The opaque rotating refresh token in the body transport (mobile). It is null in the cookie transport (web), where the token is set as an HttpOnly `mnt_refresh` cookie and must never reach web JS. */
    @SerialName(value = "refresh_token")
    val refreshToken: kotlin.String? = null

) {

    /**
     *
     *
     * Values: BEARER
     */
    @Serializable
    enum class TokenType(val value: kotlin.String) {
        @SerialName(value = "Bearer") BEARER("Bearer");
    }

}
