/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.maintenance.api.client.model

import com.maintenance.api.client.model.Team

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 *
 *
 * @param id
 * @param displayName
 * @param phone
 * @param team
 * @param roles
 * @param branchIds
 * @param isActive
 * @param createdAt
 */
@Serializable

data class UserSummary (

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @SerialName(value = "display_name")
    val displayName: kotlin.String,

    @SerialName(value = "phone")
    val phone: kotlin.String?,

    @Contextual @SerialName(value = "team")
    val team: Team,

    @SerialName(value = "roles")
    val roles: kotlin.collections.List<kotlin.String>,

    @SerialName(value = "branch_ids")
    val branchIds: kotlin.collections.List<@Contextual java.util.UUID>,

    @SerialName(value = "is_active")
    val isActive: kotlin.Boolean,

    @Contextual @SerialName(value = "created_at")
    val createdAt: java.time.OffsetDateTime

) {


}
