/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.maintenance.api.client.model

import com.maintenance.api.client.model.VoucherLineSummary
import com.maintenance.api.client.model.VoucherStatus

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 *
 *
 * @param id
 * @param voucherNo
 * @param branchId
 * @param status
 * @param memo
 * @param debitTotalWon
 * @param creditTotalWon
 * @param lines
 * @param createdBy
 * @param createdAt
 * @param updatedAt
 * @param branchName
 * @param sourceObjectType
 * @param sourceObjectId
 * @param reversalOfVoucherId
 * @param reversedByVoucherId
 * @param createdByName
 * @param approvedBy
 * @param approvedByName
 * @param postedAt
 */
@Serializable

data class VoucherSummary (

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @SerialName(value = "voucher_no")
    val voucherNo: kotlin.String,

    @Contextual @SerialName(value = "branch_id")
    val branchId: java.util.UUID,

    @Contextual @SerialName(value = "status")
    val status: VoucherStatus,

    @SerialName(value = "memo")
    val memo: kotlin.String,

    @SerialName(value = "debit_total_won")
    val debitTotalWon: kotlin.Long,

    @SerialName(value = "credit_total_won")
    val creditTotalWon: kotlin.Long,

    @SerialName(value = "lines")
    val lines: kotlin.collections.List<VoucherLineSummary>,

    @Contextual @SerialName(value = "created_by")
    val createdBy: java.util.UUID,

    @Contextual @SerialName(value = "created_at")
    val createdAt: java.time.OffsetDateTime,

    @Contextual @SerialName(value = "updated_at")
    val updatedAt: java.time.OffsetDateTime,

    @SerialName(value = "branch_name")
    val branchName: kotlin.String? = null,

    @SerialName(value = "source_object_type")
    val sourceObjectType: kotlin.String? = null,

    @SerialName(value = "source_object_id")
    val sourceObjectId: kotlin.String? = null,

    @Contextual @SerialName(value = "reversal_of_voucher_id")
    val reversalOfVoucherId: java.util.UUID? = null,

    @Contextual @SerialName(value = "reversed_by_voucher_id")
    val reversedByVoucherId: java.util.UUID? = null,

    @SerialName(value = "created_by_name")
    val createdByName: kotlin.String? = null,

    @Contextual @SerialName(value = "approved_by")
    val approvedBy: java.util.UUID? = null,

    @SerialName(value = "approved_by_name")
    val approvedByName: kotlin.String? = null,

    @Contextual @SerialName(value = "posted_at")
    val postedAt: java.time.OffsetDateTime? = null

) {


}
