/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.maintenance.api.client.model

import com.maintenance.api.client.model.WorkflowSimulationFinding

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 *
 *
 * @param decision
 * @param findings
 * @param simulatedPath For a wf.exec.v1 definition, the ordered node keys that would execute for the sample context (the branch actually taken), stopping at the first human task or terminal node. Absent for non-executable definitions.
 */
@Serializable

data class WorkflowSimulationResponse (

    @SerialName(value = "decision")
    val decision: WorkflowSimulationResponse.Decision,

    @SerialName(value = "findings")
    val findings: kotlin.collections.List<WorkflowSimulationFinding>,

    /* For a wf.exec.v1 definition, the ordered node keys that would execute for the sample context (the branch actually taken), stopping at the first human task or terminal node. Absent for non-executable definitions. */
    @SerialName(value = "simulated_path")
    val simulatedPath: kotlin.collections.List<kotlin.String>? = null

) {

    /**
     *
     *
     * Values: READY,BLOCKED
     */
    @Serializable
    enum class Decision(val value: kotlin.String) {
        @SerialName(value = "ready") READY("ready"),
        @SerialName(value = "blocked") BLOCKED("blocked");
    }

}
