/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.maintenance.api.client.model


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable


/**
 *
 *
 * Values: COMPLETED,TEMPORARY_ACTION,INCOMPLETE,REVISIT_REQUIRED,UNKNOWN
 */
@Serializable
enum class WorkResultType(val value: kotlin.String) {

    @SerialName(value = "COMPLETED")
    COMPLETED("COMPLETED"),

    @SerialName(value = "TEMPORARY_ACTION")
    TEMPORARY_ACTION("TEMPORARY_ACTION"),

    @SerialName(value = "INCOMPLETE")
    INCOMPLETE("INCOMPLETE"),

    @SerialName(value = "REVISIT_REQUIRED")
    REVISIT_REQUIRED("REVISIT_REQUIRED"),

    @SerialName(value = "UNKNOWN")
    UNKNOWN("UNKNOWN");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is WorkResultType) "$data" else null

        /**
         * Returns a valid [WorkResultType] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): WorkResultType? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}
