/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.maintenance.api.client.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 *
 *
 * @param id
 * @param code
 * @param definitionId
 * @param definitionVersion
 * @param triggerType
 * @param status
 * @param actorDisplayName
 * @param summary
 * @param errorMessage
 * @param generatedObjects
 * @param startedAt
 * @param updatedAt
 * @param completedAt
 * @param failedAt
 */
@Serializable

data class WorkflowRunResponse (

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @SerialName(value = "code")
    val code: kotlin.String,

    @Contextual @SerialName(value = "definition_id")
    val definitionId: java.util.UUID,

    @SerialName(value = "definition_version")
    val definitionVersion: kotlin.Int,

    @SerialName(value = "trigger_type")
    val triggerType: WorkflowRunResponse.TriggerType,

    @SerialName(value = "status")
    val status: WorkflowRunResponse.Status,

    @SerialName(value = "actor_display_name")
    val actorDisplayName: kotlin.String?,

    @SerialName(value = "summary")
    val summary: kotlin.String,

    @SerialName(value = "error_message")
    val errorMessage: kotlin.String?,

    @SerialName(value = "generated_objects")
    val generatedObjects: kotlin.collections.List<kotlin.String>,

    @Contextual @SerialName(value = "started_at")
    val startedAt: java.time.OffsetDateTime,

    @Contextual @SerialName(value = "updated_at")
    val updatedAt: java.time.OffsetDateTime,

    @Contextual @SerialName(value = "completed_at")
    val completedAt: java.time.OffsetDateTime?,

    @Contextual @SerialName(value = "failed_at")
    val failedAt: java.time.OffsetDateTime?

) {

    /**
     *
     *
     * Values: MANUAL,SCHEDULE,WEBHOOK,SYSTEM
     */
    @Serializable
    enum class TriggerType(val value: kotlin.String) {
        @SerialName(value = "MANUAL") MANUAL("MANUAL"),
        @SerialName(value = "SCHEDULE") SCHEDULE("SCHEDULE"),
        @SerialName(value = "WEBHOOK") WEBHOOK("WEBHOOK"),
        @SerialName(value = "SYSTEM") SYSTEM("SYSTEM");
    }
    /**
     *
     *
     * Values: STARTING,RUNNING,WAITING,SUCCEEDED,FAILED,CANCELLED
     */
    @Serializable
    enum class Status(val value: kotlin.String) {
        @SerialName(value = "STARTING") STARTING("STARTING"),
        @SerialName(value = "RUNNING") RUNNING("RUNNING"),
        @SerialName(value = "WAITING") WAITING("WAITING"),
        @SerialName(value = "SUCCEEDED") SUCCEEDED("SUCCEEDED"),
        @SerialName(value = "FAILED") FAILED("FAILED"),
        @SerialName(value = "CANCELLED") CANCELLED("CANCELLED");
    }

}
