export_file(
    name = "openapi.yaml",
    src = "openapi.yaml",
    mode = "reference",
    visibility = ["PUBLIC"],
)

export_file(
    name = "shared-tree",
    src = "shared",
    mode = "reference",
    visibility = ["PUBLIC"],
)
