import {
  Activity,
  Ban,
  Bell,
  BookOpen,
  Box,
  Calculator,
  CalendarCheck,
  ChartNoAxesCombined,
  CircleCheck,
  Clock,
  Download,
  Eye,
  FileCheck,
  Fingerprint,
  Folder,
  Gauge,
  Gavel,
  Heart,
  History,
  Inbox,
  Layers,
  LayoutDashboard,
  Lock,
  LockOpen,
  Mail,
  Mailbox,
  MapPin,
  Megaphone,
  MessageSquare,
  Minimize2,
  Monitor,
  Moon,
  Network,
  PenLine,
  Pin,
  Plus,
  Receipt,
  Repeat,
  ScrollText,
  Share2,
  ShieldCheck,
  ShoppingCart,
  SquareCheck,
  Sun,
  TrendingUp,
  TriangleAlert,
  Truck,
  UserPlus,
  Users,
  Workflow,
  Wrench,
  X,
  type LucideIcon,
} from "lucide-react";

export const consoleIconNames = [
  "overview",
  "inbox",
  "users",
  "userPlus",
  "network",
  "circleCheck",
  "calc",
  "clock",
  "calCheck",
  "heart",
  "receipt",
  "cart",
  "box",
  "layers",
  "truck",
  "wrench",
  "mapPin",
  "checkSq",
  "shieldCheck",
  "fileCheck",
  "folder",
  "history",
  "chart",
  "trend",
  "share",
  "gauge",
  "workflow",
  "repeat",
  "msg",
  "mail",
  "bell",
  "megaphone",
  "book",
  "plus",
  "pen",
  "sun",
  "moon",
  "monitor",
  "mailbox",
  "fingerprint",
  "lock",
  "lockOpen",
  "scroll",
  "gavel",
  "eye",
  "ban",
  "activity",
  "download",
  "alert",
  "pin",
  "minz",
  "close",
] as const;

export type ConsoleIconName = (typeof consoleIconNames)[number];
export type ConsoleIconComponent = LucideIcon;

export const consoleIcons = {
  overview: LayoutDashboard,
  inbox: Inbox,
  users: Users,
  userPlus: UserPlus,
  network: Network,
  circleCheck: CircleCheck,
  calc: Calculator,
  clock: Clock,
  calCheck: CalendarCheck,
  heart: Heart,
  receipt: Receipt,
  cart: ShoppingCart,
  box: Box,
  layers: Layers,
  truck: Truck,
  wrench: Wrench,
  mapPin: MapPin,
  checkSq: SquareCheck,
  shieldCheck: ShieldCheck,
  fileCheck: FileCheck,
  folder: Folder,
  history: History,
  chart: ChartNoAxesCombined,
  trend: TrendingUp,
  share: Share2,
  gauge: Gauge,
  workflow: Workflow,
  repeat: Repeat,
  msg: MessageSquare,
  mail: Mail,
  bell: Bell,
  megaphone: Megaphone,
  book: BookOpen,
  plus: Plus,
  pen: PenLine,
  sun: Sun,
  moon: Moon,
  monitor: Monitor,
  mailbox: Mailbox,
  fingerprint: Fingerprint,
  lock: Lock,
  lockOpen: LockOpen,
  scroll: ScrollText,
  gavel: Gavel,
  eye: Eye,
  ban: Ban,
  activity: Activity,
  download: Download,
  alert: TriangleAlert,
  pin: Pin,
  minz: Minimize2,
  close: X,
} satisfies Record<ConsoleIconName, ConsoleIconComponent>;
