export type CossPageGroup = 'HOME' | 'COMPANY' | 'BUSINESS' | 'SUSTAINABILITY' | 'CONTACT US' | 'POLICY';

export type CossPage = {
  id: string;
  group: CossPageGroup;
  route: string;
  title: string;
  eyebrow: string;
  subtitle: string;
  lead: string;
  bullets: readonly string[];
  highlights?: readonly string[];
};

const cossHeroVideoPath = '/html/_skin/files/coss_main_all_251229.mp4?ver=251224';

export const cossHeroVideo = {
  path: cossHeroVideoPath,
  legacyUri: `https://www.cossok.com${cossHeroVideoPath}`,
  targetUri: `https://www.cosskorea.com${cossHeroVideoPath}`,
  contentType: 'video/mp4',
  contentLengthBytes: 29386296,
} as const;

export const cossPages: readonly CossPage[] = [
  {
    id: 'home',
    group: 'HOME',
    route: '/',
    title: 'COSS',
    eyebrow: 'INNOVATION PARTNER',
    subtitle: '대한민국 대표 아웃소싱 기업 (주) 코스',
    lead: 'cossok.com 메인 랜딩의 고정 비디오, 풀페이지 섹션, 사업 영역, 지속가능경영, 문의 흐름을 React Native 화면으로 옮겼습니다.',
    bullets: ['메인 비디오 비주얼과 RECRUIT 슬라이더', 'BUSINESS·SUSTAINABILITY·CONTACT US 랜딩 섹션', 'cosskorea.com 공개 사이트와 console.cosskorea.com 운영 콘솔 분리'],
    highlights: ['cosskorea.com', 'console.cosskorea.com', 'React Native'],
  },
  {
    id: 'company',
    group: 'COMPANY',
    route: '/company',
    title: 'COMPANY',
    eyebrow: 'We challenge limits and create new standards',
    subtitle: '한계에 도전하고 새로운 기준을 만듭니다.',
    lead: 'COSS의 가치와 비전, 연혁, 계열사, 인허가 및 인증을 한 곳에서 소개하는 회사 섹션입니다.',
    bullets: ['가치와 비젼', '연혁', '계열사 소개', '인허가ㅣ인증'],
    highlights: ['VISION 3050', 'CONNECTING DOTS', 'CERTIFICATION'],
  },
  {
    id: 'vision',
    group: 'COMPANY',
    route: '/company/vision',
    title: '가치와 비젼',
    eyebrow: 'We challenge limits and create new standards',
    subtitle: '한계에 도전하고 새로운 기준을 만듭니다.',
    lead: 'VISION 3050. 생산도급, 시설물 통합관리, 장비 렌탈, 생산 및 물류 컨설팅 등 고객 핵심 사업영역을 책임지는 전문 아웃소싱 파트너입니다.',
    bullets: [
      '고객 감동을 넘어 고객사의 가치를 극대화하는 전략적 파트너',
      '구성원 모두의 주인의식으로 고객과 함께 성장',
      '기술, 안전, 품질을 기반으로 현장의 지속 가능성을 높이는 조직',
    ],
    highlights: ['VISION 3050', '고객 중심', '현장 중심 서비스'],
  },
  {
    id: 'history',
    group: 'COMPANY',
    route: '/company/history',
    title: '연혁',
    eyebrow: 'CONNECTING DOTS',
    subtitle: '“새로운 도약, 미래를 잇다”',
    lead: '2023년 이후 VISION 3050 수립, ISO9001·ISO14001·ISO45001 취득, 연간매출 2,000억 달성 등 새로운 성장 단계에 진입했습니다.',
    bullets: [
      '2023- : VISION 3050 수립 및 주요 계열사 ISO 인증 취득',
      '2018-2022 : 연간매출 1,000억 달성 및 주요 고객사 지정도급 확대',
      '2011-2017 : 밀양공장 설립, 생산·물류 사업영역 확장',
      '2004-2010 : 아웃소싱 전문기업 기반 구축',
    ],
    highlights: ['CONNECTING DOTS', 'SCALING BOUNDARIES', 'FUELING GROWTH'],
  },
  {
    id: 'affiliates',
    group: 'COMPANY',
    route: '/company/affiliates',
    title: '계열사 소개',
    eyebrow: 'Integrated Facility Management',
    subtitle: '부문별 아웃소싱 전문 회사 네트워크',
    lead: '주식회사 코스 외 10개의 부문별 아웃소싱 전문 회사로 제조공장, 생산도급, 물류, 통합서비스, 컨설팅 영역을 운영합니다.',
    bullets: [
      '자가 제조공장 운영: 자동차 샷시·써멀계통 부품 생산',
      '고객사 사내 생산도급: 조립·용접·가공·도장·차체스템핑',
      '물류: 생산물류, 자재보급, 물류센터 운영, 장비 렌탈',
      '통합서비스: 시설물 유지관리, 보안, 미화, 물류혁신 컨설팅',
    ],
    highlights: ['10+ 계열사', '자가 제조공장', '통합 서비스'],
  },
  {
    id: 'certification',
    group: 'COMPANY',
    route: '/company/certification',
    title: '인허가ㅣ인증',
    eyebrow: 'CERTIFICATION',
    subtitle: '운영 신뢰를 증명하는 인허가와 인증',
    lead: '화물운송·위생용역·경비업 등 사업 인허가와 ISO9001, ISO14001, ISO45001 인증을 통해 품질·환경·안전보건 운영 체계를 검증받았습니다.',
    bullets: ['화물운송주선사업허가증', '화물운송사업허가증', 'ISO45001', 'ISO14001', 'ISO9001', '위생용역신고증'],
    highlights: ['12건', 'ISO 3종', '운영 인증'],
  },
  {
    id: 'business',
    group: 'BUSINESS',
    route: '/business',
    title: 'BUSINESS',
    eyebrow: 'COSS BUSINESS',
    subtitle: 'COSS는 고객 곁에서 최적의 방향을 함께 설계합니다.',
    lead: '생산도급, 물류도급, 통합시설관리, 물류장비, 컨설팅, 자가공장까지 메인 사이트의 사업 카테고리 전체를 복제했습니다.',
    bullets: ['생산도급', '물류도급', '통합시설관리', '물류장비', '컨설팅', '자가공장'],
    highlights: ['6 Business Lines', 'Field Operations', 'Outsourcing Partner'],
  },
  {
    id: 'production',
    group: 'BUSINESS',
    route: '/business/production',
    title: '생산도급',
    eyebrow: 'In-house Production Subcontracting',
    subtitle: '품질과 생산성을 동시에 확보하는 생산도급',
    lead: '경험과 기술력을 갖춘 전문 인력이 조립·가공 등 전 공정에 투입되어 고객사의 생산계획에 맞춘 유연한 인력 운영과 납기 대응력을 제공합니다.',
    bullets: ['조립·가공·용접·도장 등 전 공정 투입', 'KPI 기반 품질·생산성 관리', '완성차 및 산업설비 제조사 대상 운영 실적'],
    highlights: ['CTR', 'KG Mobility', 'Hanwha Aerospace'],
  },
  {
    id: 'logistics',
    group: 'BUSINESS',
    route: '/business/logistics',
    title: '물류도급',
    eyebrow: 'In-house Logistics Subcontracting',
    subtitle: '입·출고부터 창고관리까지 통합 물류 운영',
    lead: '입·출고, 포장, 창고관리 등 전 물류 과정을 통합 운영하고 지게차·AGV 등 장비 운영과 인력 배치를 최적화합니다.',
    bullets: ['입고·출고·포장·창고관리 통합 운영', '지게차·AGV 장비 운영 및 안전관리', '자동차·기계·전자업종 검증 노하우'],
    highlights: ['Homeplus', 'LG Electronics', 'Samsung SDI'],
  },
  {
    id: 'integrated',
    group: 'BUSINESS',
    route: '/business/integrated',
    title: '통합시설관리',
    eyebrow: 'Integrated Facility Management',
    subtitle: '보안·미화·유지보수·에너지관리 통합 운영',
    lead: 'IFM은 보안, 청소, 유지보수, 에너지관리 등을 중앙집중형 관리 체계로 통합 운영하여 효율성, 비용절감, 품질 향상을 동시에 실현합니다.',
    bullets: ['제조·호텔·공동주택·학교·병원·백화점 대상 서비스', '단일 공급자를 통한 시설 관련 서비스 통합', '품질 표준화와 비용절감 동시 달성'],
    highlights: ['IFM', '보안·환경·안전', '전 산업군'],
  },
  {
    id: 'equipment',
    group: 'BUSINESS',
    route: '/business/three_r',
    title: '물류장비',
    eyebrow: 'Logistics Equipment',
    subtitle: '현장 운영에 필요한 물류장비 공급과 관리',
    lead: '지게차 및 물류장비 렌탈·정비·운영관리까지 현장 흐름에 맞춰 제공합니다.',
    bullets: ['물류장비 렌탈 및 운영관리', '장비 정비와 A/S 대응', '운영인력과 장비 배치 최적화'],
    highlights: ['지게차', '렌탈', '정비'],
  },
  {
    id: 'consulting',
    group: 'BUSINESS',
    route: '/business/consulting',
    title: '컨설팅',
    eyebrow: 'Consulting Services',
    subtitle: '생산·물류 현장의 개선 방향을 설계합니다',
    lead: '공정개선, 물류혁신, 비용구조 최적화 등 고객 현장의 성장과 효율화를 위한 실행 중심 컨설팅을 제공합니다.',
    bullets: ['공정개선 컨설팅', '물류혁신 컨설팅', '운영 비용 및 생산성 개선안 설계'],
    highlights: ['진단', '설계', '실행'],
  },
  {
    id: 'own-factory',
    group: 'BUSINESS',
    route: '/business/own-factory',
    title: '자가공장',
    eyebrow: 'Owned Factories',
    subtitle: '직접 운영하는 제조 기반',
    lead: '첨단 설비와 숙련된 기술력으로 자동차 부품의 정밀가공 및 조립공장을 직접 운영합니다.',
    bullets: ['밀양·창원·울산 공장 운영', '자동차 샷시 및 써멀계통 부품 생산', '품질 기준에 맞춘 정밀가공·조립'],
    highlights: ['밀양공장', '창원공장', '울산공장'],
  },
  {
    id: 'sustainability',
    group: 'SUSTAINABILITY',
    route: '/sustainability',
    title: 'SUSTAINABILITY',
    eyebrow: 'COSS SUSTAINABILITY',
    subtitle: '행동과 혁신으로 더 나은 세상을 만듭니다',
    lead: 'Net Zero, 인권과 윤리, 환경과 안전보건, 품질의 네 개 앵커 페이지를 갖는 지속가능경영 섹션입니다.',
    bullets: ['Net Zero', '인권과 윤리', '환경과 안전보건', '품질'],
    highlights: ['ESG', 'Safety', 'Quality'],
  },
  {
    id: 'net-zero',
    group: 'SUSTAINABILITY',
    route: '/sustainability/#net',
    title: 'Net Zero',
    eyebrow: 'SUSTAINABILITY',
    subtitle: '탄소중립을 향한 운영 개선',
    lead: '에너지 사용과 현장 운영을 체계적으로 관리하여 환경 영향을 줄이고 지속 가능한 아웃소싱 운영 모델을 구축합니다.',
    bullets: ['에너지 절감 활동', '환경 리스크 관리', '현장 운영 효율화'],
    highlights: ['Net Zero', '환경경영', '운영 효율'],
  },
  {
    id: 'human',
    group: 'SUSTAINABILITY',
    route: '/sustainability/#human',
    title: '인권과 윤리',
    eyebrow: 'SUSTAINABILITY',
    subtitle: '사람과 윤리를 우선하는 조직문화',
    lead: '인권 존중, 윤리경영, 소통과 존중을 바탕으로 구성원과 고객이 함께 성장하는 조직을 지향합니다.',
    bullets: ['인권 존중', '윤리경영', '소통과 존중의 조직문화'],
    highlights: ['Human Rights', 'Ethics', 'Culture'],
  },
  {
    id: 'environment',
    group: 'SUSTAINABILITY',
    route: '/sustainability/#environment',
    title: '환경과 안전보건',
    eyebrow: 'SUSTAINABILITY',
    subtitle: '안전을 최우선 가치로 삼는 현장 운영',
    lead: '환경과 안전보건을 핵심 관리 지표로 두고, 산업 현장의 위험을 줄이며 안정적인 운영 품질을 확보합니다.',
    bullets: ['안전보건 관리체계', '환경 리스크 예방', '현장 중심 교육과 점검'],
    highlights: ['ISO45001', 'ISO14001', 'Safety'],
  },
  {
    id: 'quality',
    group: 'SUSTAINABILITY',
    route: '/sustainability/#quality',
    title: '품질',
    eyebrow: 'SUSTAINABILITY',
    subtitle: '품질 우선주의와 KPI 기반 성과 운영',
    lead: '품질 기준과 성과 지표를 기반으로 고객 현장의 안정성과 생산성을 높입니다.',
    bullets: ['ISO9001 기반 품질관리', 'KPI 기반 성과 운영', '지속적인 개선 활동'],
    highlights: ['ISO9001', 'KPI', '품질 개선'],
  },
  {
    id: 'contactus',
    group: 'CONTACT US',
    route: '/contactus',
    title: 'CONTACT US',
    eyebrow: 'CONTACT US',
    subtitle: '문의사항을 남겨주시면 담당자가 영업일 1일 이내로 연락드리겠습니다.',
    lead: '사업문의, 인재상, FAQ, 제보하기까지 메인 사이트의 연락/채용/제보 흐름을 포함합니다.',
    bullets: ['사업문의', '인재상', 'FAQ', '제보하기'],
    highlights: ['055-253-2720', 'cossok@cosskorea.com', '창원시 의창구'],
  },
  {
    id: 'business-inquiry',
    group: 'CONTACT US',
    route: '/contactus/business-inquiry',
    title: '사업문의',
    eyebrow: 'CONTACT US',
    subtitle: '문의사항을 남겨주시면 담당자가 영업일 1일 이내로 연락드리겠습니다.',
    lead: '생산도급, 물류도급, 통합시설관리, 물류장비, 컨설팅, 자가공장 관련 상담을 연결합니다.',
    bullets: ['담당자 영업일 1일 이내 연락', '서비스 영역별 상담', 'cossok@cosskorea.com'],
    highlights: ['사업 문의하기', '055-253-2720', 'cosskorea.com'],
  },
  {
    id: 'ideal-person',
    group: 'CONTACT US',
    route: '/contactus/ideal-person',
    title: '인재상',
    eyebrow: 'RECRUIT',
    subtitle: '현장과 고객을 함께 성장시키는 COSS 인재',
    lead: '안전, 책임, 협업, 성장 의지를 갖춘 구성원이 COSS의 브랜드가 됩니다.',
    bullets: ['안전을 최우선으로 생각하는 사람', '책임감 있게 현장을 운영하는 사람', '고객과 동료를 존중하며 성장하는 사람'],
    highlights: ['안전', '책임', '성장'],
  },
  {
    id: 'faq',
    group: 'CONTACT US',
    route: '/contactus/faq',
    title: 'FAQ',
    eyebrow: 'CONTACT US',
    subtitle: '자주 묻는 질문',
    lead: '서비스 도입, 상담 절차, 채용 및 제보 관련 주요 질문을 빠르게 확인할 수 있습니다.',
    bullets: ['서비스 상담은 어떻게 시작하나요?', '도급 운영 범위는 어떻게 정하나요?', '채용 지원은 어디에서 확인하나요?'],
    highlights: ['상담', '운영 범위', '채용'],
  },
  {
    id: 'report',
    group: 'CONTACT US',
    route: '/contactus/report',
    title: '제보하기',
    eyebrow: 'CONTACT US',
    subtitle: '투명한 운영을 위한 제보 채널',
    lead: '윤리, 안전, 품질, 현장 운영 관련 제보를 접수해 더 나은 조직과 현장을 만듭니다.',
    bullets: ['윤리·인권 제보', '안전·환경 제보', '품질·운영 개선 제안'],
    highlights: ['윤리', '안전', '품질'],
  },
  {
    id: 'terms',
    group: 'POLICY',
    route: '/policy/terms',
    title: '이용약관',
    eyebrow: 'POLICY',
    subtitle: '서비스 이용조건 및 절차',
    lead: '주식회사 코스가 제공하는 사업 관련 서비스의 이용조건, 절차, 권리와 의무, 책임사항을 규정하는 약관 페이지입니다.',
    bullets: ['목적 및 약관의 효력', '이용자와 회원의 의무', '서비스 제공 및 이용 제한', '손해배상과 면책사항'],
    highlights: ['Terms', '서비스 이용조건', '권리와 의무'],
  },
  {
    id: 'privacy',
    group: 'POLICY',
    route: '/policy/privacy',
    title: '개인정보 취급방침',
    eyebrow: 'POLICY',
    subtitle: '개인정보 보호 및 권익 보호',
    lead: '개인정보보호법에 따라 이용자의 개인정보 보호와 고충 처리를 위한 처리방침을 안내합니다. 원문 기준 시행일은 2025년 7월 18일입니다.',
    bullets: ['개인정보 처리 목적', '개인정보 보유 및 이용기간', '처리 위탁과 정보주체 권리', '개인정보 보호책임자 및 고충 처리'],
    highlights: ['Privacy', '2025.07.18', '개인정보보호법'],
  },
  {
    id: 'email-policy',
    group: 'POLICY',
    route: '/policy/email',
    title: '이메일 무단수집 거부',
    eyebrow: 'POLICY',
    subtitle: '전자우편 주소 무단 수집 금지',
    lead: '게시된 이메일 주소가 전자우편 수집 프로그램이나 그 밖의 기술적 장치로 무단 수집되는 것을 거부합니다.',
    bullets: ['전자우편 수집 프로그램 이용 금지', '기술적 장치를 통한 무단 수집 금지', '정보통신망 이용촉진 및 정보보호 등에 관한 법률에 따른 보호'],
    highlights: ['Email Policy', '무단수집 거부', '정보통신망법'],
  },
  {
    id: 'sitemap',
    group: 'POLICY',
    route: '/policy/sitemap',
    title: '사이트맵',
    eyebrow: 'POLICY',
    subtitle: 'cossok.com 전체 공개 사이트맵',
    lead: '원본 사이트의 사이트맵 페이지가 노출하는 COMPANY, BUSINESS, SUSTAINABILITY, CONTACT US 전체 경로를 cosskorea.com 기준으로 복제했습니다.',
    bullets: ['COMPANY 5개 경로', 'BUSINESS 7개 경로', 'SUSTAINABILITY 5개 경로', 'CONTACT US 5개 경로'],
    highlights: ['Full Sitemap', 'cosskorea.com', 'Route Parity'],
  },
] as const;

export const cossPageGroups: readonly CossPageGroup[] = [
  'HOME',
  'COMPANY',
  'BUSINESS',
  'SUSTAINABILITY',
  'CONTACT US',
  'POLICY',
] as const;

export const cossSourceSitemapRoutes = [
  '/',
  '/company',
  '/company/vision',
  '/company/history',
  '/company/affiliates',
  '/company/certification',
  '/business',
  '/business/production',
  '/business/logistics',
  '/business/integrated',
  '/business/three_r',
  '/business/consulting',
  '/business/own-factory',
  '/sustainability',
  '/sustainability/#net',
  '/sustainability/#human',
  '/sustainability/#environment',
  '/sustainability/#quality',
  '/contactus',
  '/contactus/business-inquiry',
  '/contactus/ideal-person',
  '/contactus/faq',
  '/contactus/report',
] as const;

export const cossPolicyRoutes = [
  '/policy/terms',
  '/policy/privacy',
  '/policy/email',
  '/policy/sitemap',
] as const;

export const cossSiteRoutes = [
  ...cossSourceSitemapRoutes,
  '/sustainability/',
  '/index.html',
  ...cossPolicyRoutes,
] as const;
