import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { after, describe, it } from "node:test";
import { fileURLToPath } from "node:url";

import { ACTION_FLOOR, CANONICAL_ACTIONS } from "./check-openapi-semantic-contract.mjs";
import { MANIFEST_REL } from "./check-openapi-semantic-generate.mjs";
import {
  TYPED_ACTION_GENERATED_REL,
  TYPED_ACTION_RS_REL,
} from "./check-openapi-typed-action-codecs.mjs";
import { evaluateTypedActionBinder } from "./check-openapi-typed-action-binder.mjs";

const repoRoot = fileURLToPath(new URL("..", import.meta.url));
const cli = fileURLToPath(new URL("./check-openapi-typed-action-binder.mjs", import.meta.url));
const fixtureRoots = [];

after(() => {
  for (const root of fixtureRoots) rmSync(root, { recursive: true, force: true });
});

function fixture(files) {
  const root = mkdtempSync(join(tmpdir(), "openapi-typed-action-binder-"));
  fixtureRoots.push(root);
  for (const [rel, body] of Object.entries(files)) {
    const absolute = join(root, rel);
    mkdirSync(dirname(absolute), { recursive: true });
    writeFileSync(absolute, body);
  }
  return root;
}

function completeManifest() {
  return {
    version: 1,
    objects: [],
    links: [],
    actions: CANONICAL_ACTIONS.map((action) => ({
      action_key: action.action_key,
      object: action.object,
      object_key: action.object_key,
      input: action.input,
      four_eyes: action.four_eyes,
      edits: [...action.edits],
      permissions: ["role_manage"],
      concurrency: {
        command_id: "tenant_global_idempotency",
        expected_revision: "optional_cas",
      },
    })),
  };
}

function generatedBinder(manifest) {
  const arms = manifest.actions
    .map((action) => {
      const variant = action.action_key
        .split(/[._]/)
        .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
        .join("");
      return `        DispatchTarget::${variant} => decode::<${action.input}>(target, params),`;
    })
    .join("\n");
  return `// @generated by console-openapi-gen from semantic_manifest.json. Do not edit.

fn decode_dispatch_target(target: DispatchTarget, params: &Value) -> Result<(), ActionError> {
    match target {
${arms}
    }
}

fn decode<T: DeserializeOwned>(target: DispatchTarget, params: &Value) -> Result<(), ActionError> {
    Ok(())
}

fn reject_caller_action_key(action_key: &str, params: &Value) -> Result<(), ActionError> {
    for field in ["target", "action_key"] {
        let _ = field;
    }
    Ok(())
}

pub(crate) fn bind_canonical_action_params(
    action_key: &str,
    params: &Value,
) -> Result<Value, ActionError> {
    match DispatchTarget::from_str(action_key) {
        Ok(target) => {
            reject_caller_action_key(action_key, params)?;
            decode_dispatch_target(target, params)?;
            Ok(params.clone())
        }
        Err(_) => match params {
            Value::Null | Value::Object(_) => Ok(params.clone()),
            other => Err(ActionError::Validation(format!(
                "params must be a JSON object, got {other}"
            ))),
        },
    }
}
`;
}

const GREEN_EMITTER = `pub fn generated_typed_action_rs() -> Result<String, String> {
    let _ = include_str!("semantic_manifest.json");
    emit_typed_action_binder();
    let _ = "fn bind_canonical_action_params";
    let _ = "fn reject_caller_action_key";
    Ok(String::new())
}
fn emit_typed_action_binder() {}
`;

const GREEN_GEN = `fn main() {
    let _ = console_contracts::generated_typed_action_rs();
    let _ = "fn bind_canonical_action_params";
    let _ = "typed_action_generated.rs";
}
`;

const GREEN_HOST = `include!("typed_action_generated.rs");
`;

function greenFiles(manifest, extra = {}) {
  return {
    [MANIFEST_REL]: JSON.stringify(manifest, null, 2),
    "backend/crates/contracts/src/semantic.rs": GREEN_EMITTER,
    "backend/crates/contracts/src/bin/console_openapi_gen.rs": GREEN_GEN,
    [TYPED_ACTION_RS_REL]: GREEN_HOST,
    [TYPED_ACTION_GENERATED_REL]: generatedBinder(manifest),
    ...extra,
  };
}

describe("typed-action-binder floors", () => {
  it("locks examined-zero to the thirteen DispatchTarget actions", () => {
    assert.equal(ACTION_FLOOR, 13);
    assert.equal(CANONICAL_ACTIONS.length, ACTION_FLOOR);
  });
});

describe("evaluateTypedActionBinder", () => {
  it("fails when the manifest is absent", () => {
    const root = fixture({
      [TYPED_ACTION_RS_REL]: "pub(crate) fn bind_canonical_action_params() {}\n",
    });
    const result = evaluateTypedActionBinder({ repoRoot: root });
    assert.equal(result.actions, 0);
    assert.ok(
      result.findings.some((finding) => /semantic manifest is absent/.test(finding.message)),
    );
  });

  it("fails while typed_action.rs hand-defines bind_canonical_action_params", () => {
    const manifest = completeManifest();
    const root = fixture(
      greenFiles(manifest, {
        [TYPED_ACTION_RS_REL]: `pub(crate) fn bind_canonical_action_params(
    action_key: &str,
    params: &Value,
) -> Result<Value, ActionError> {
    match DispatchTarget::from_str(action_key) {
        Ok(target) => Ok(params.clone()),
        Err(_) => Ok(params.clone()),
    }
}
include!("typed_action_generated.rs");
`,
      }),
    );
    const result = evaluateTypedActionBinder({ repoRoot: root });
    assert.ok(
      result.findings.some((finding) =>
        /hand-defines bind_canonical_action_params/.test(finding.message),
      ),
      JSON.stringify(result.findings),
    );
  });

  it("fails when generated rust omits the binder", () => {
    const manifest = completeManifest();
    const files = greenFiles(manifest);
    files[TYPED_ACTION_GENERATED_REL] = `// @generated
fn decode_dispatch_target(target: DispatchTarget, params: &Value) -> Result<(), ActionError> {
    match target {
        DispatchTarget::CompanyRevise => decode::<CompanyReviseInput>(target, params),
    }
}
`;
    const root = fixture(files);
    const result = evaluateTypedActionBinder({ repoRoot: root });
    assert.ok(
      result.findings.some((finding) =>
        /must define bind_canonical_action_params/.test(finding.message),
      ),
      JSON.stringify(result.findings),
    );
  });

  it("fails when the emitter does not generate the binder", () => {
    const manifest = completeManifest();
    const root = fixture(
      greenFiles(manifest, {
        "backend/crates/contracts/src/semantic.rs": `pub fn generated_typed_action_rs() -> Result<String, String> {
    let _ = include_str!("semantic_manifest.json");
    Ok(String::new())
}
`,
      }),
    );
    const result = evaluateTypedActionBinder({ repoRoot: root });
    assert.ok(
      result.findings.some((finding) =>
        /emit bind_canonical_action_params/.test(finding.message),
      ),
      JSON.stringify(result.findings),
    );
  });

  it("fails when the non-roster catch-all is missing", () => {
    const manifest = completeManifest();
    const files = greenFiles(manifest);
    files[TYPED_ACTION_GENERATED_REL] = files[TYPED_ACTION_GENERATED_REL].replace(
      "Value::Null | Value::Object(_)",
      "Value::Object(_)",
    );
    const root = fixture(files);
    const result = evaluateTypedActionBinder({ repoRoot: root });
    assert.ok(
      result.findings.some((finding) => /object-or-null catch-all/.test(finding.message)),
      JSON.stringify(result.findings),
    );
  });

  it("passes a fixture whose binder is generated from the manifest", () => {
    const manifest = completeManifest();
    const root = fixture(greenFiles(manifest));
    const result = evaluateTypedActionBinder({ repoRoot: root });
    assert.deepEqual(result.findings, []);
    assert.equal(result.actions, ACTION_FLOOR);
  });
});

describe("cli", () => {
  it("accepts the live binder only when bind_canonical_action_params is generated", () => {
    const run = spawnSync(process.execPath, [cli, repoRoot], { encoding: "utf8" });
    assert.equal(run.status, 0, run.stderr);
    assert.match(run.stdout, /typed-action-binder gate passed/);
  });
});
