export_file(
    name = "daily-progress",
    src = "일일업무진행현황_0605.xlsx",
    mode = "reference",
    visibility = ["PUBLIC"],
)

export_file(
    name = "work-log",
    src = "업무일지_26.05.27.xlsx",
    mode = "reference",
    visibility = ["PUBLIC"],
)

export_file(
    name = "master-list",
    src = "master-list_251120.xlsx",
    mode = "reference",
    visibility = ["PUBLIC"],
)
