/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.maintenance.api.client.api

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import com.maintenance.api.client.model.AttendanceImportApplyReport
import com.maintenance.api.client.model.AttendanceImportDryRunSummary
import com.maintenance.api.client.model.AttendanceImportPreviewResponse
import com.maintenance.api.client.model.AttendanceImportSummaryPage
import com.maintenance.api.client.model.AttendanceSummaryPage
import com.maintenance.api.client.model.ConfirmEmployeeExitCaseRequest
import com.maintenance.api.client.model.CreateEmployeeAttendanceRecordRequest
import com.maintenance.api.client.model.DraftEmployeeExitApprovalRequest
import com.maintenance.api.client.model.EmployeeAttendanceRecord
import com.maintenance.api.client.model.EmployeeAttendanceRecordPage
import com.maintenance.api.client.model.ErrorBody
import com.maintenance.api.client.model.HrOrgChartResponse
import com.maintenance.api.client.model.LeaveBalancePage
import com.maintenance.api.client.model.ReportEmployeeExitCaseRequest

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import com.maintenance.api.client.infrastructure.ApiClient
import com.maintenance.api.client.infrastructure.ApiResponse
import com.maintenance.api.client.infrastructure.ClientException
import com.maintenance.api.client.infrastructure.ClientError
import com.maintenance.api.client.infrastructure.ServerException
import com.maintenance.api.client.infrastructure.ServerError
import com.maintenance.api.client.infrastructure.MultiValueMap
import com.maintenance.api.client.infrastructure.PartConfig
import com.maintenance.api.client.infrastructure.RequestConfig
import com.maintenance.api.client.infrastructure.RequestMethod
import com.maintenance.api.client.infrastructure.ResponseType
import com.maintenance.api.client.infrastructure.Success
import com.maintenance.api.client.infrastructure.toMultiValue
import com.maintenance.api.client.infrastructure.Serializer

open class HrApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "http://localhost")
        }
    }

    /**
     * POST /api/v1/hr/attendance-import/{run_id}/apply
     * Apply a dry-run direct attendance import as append-only coordinate-free facts
     * Applies only a DRY_RUN attendance_direct import with no unresolved row errors. It writes lineage-preserving attendance_direct_import_events and leaves geofence-derived site_attendance_events unchanged.
     * @param runId
     * @return AttendanceImportApplyReport
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun applyAttendanceImport(runId: java.util.UUID) : AttendanceImportApplyReport = withContext(Dispatchers.IO) {
        val localVarResponse = applyAttendanceImportWithHttpInfo(runId = runId)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as AttendanceImportApplyReport
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /api/v1/hr/attendance-import/{run_id}/apply
     * Apply a dry-run direct attendance import as append-only coordinate-free facts
     * Applies only a DRY_RUN attendance_direct import with no unresolved row errors. It writes lineage-preserving attendance_direct_import_events and leaves geofence-derived site_attendance_events unchanged.
     * @param runId
     * @return ApiResponse<AttendanceImportApplyReport?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun applyAttendanceImportWithHttpInfo(runId: java.util.UUID) : ApiResponse<AttendanceImportApplyReport?> = withContext(Dispatchers.IO) {
        val localVariableConfig = applyAttendanceImportRequestConfig(runId = runId)

        return@withContext request<Unit, AttendanceImportApplyReport>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation applyAttendanceImport
     *
     * @param runId
     * @return RequestConfig
     */
    fun applyAttendanceImportRequestConfig(runId: java.util.UUID) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/v1/hr/attendance-import/{run_id}/apply".replace("{"+"run_id"+"}", encodeURIComponent(runId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /api/v1/hr/exit-cases/{id}/confirm
     * Confirm an employee exit case for HR/HQ review
     *
     * @param id
     * @param confirmEmployeeExitCaseRequest
     * @return kotlin.collections.Map<kotlin.String, kotlinx.serialization.json.JsonElement>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun confirmEmployeeExitCase(id: java.util.UUID, confirmEmployeeExitCaseRequest: ConfirmEmployeeExitCaseRequest) : kotlin.collections.Map<kotlin.String, kotlinx.serialization.json.JsonElement> = withContext(Dispatchers.IO) {
        val localVarResponse = confirmEmployeeExitCaseWithHttpInfo(id = id, confirmEmployeeExitCaseRequest = confirmEmployeeExitCaseRequest)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.collections.Map<kotlin.String, kotlinx.serialization.json.JsonElement>
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /api/v1/hr/exit-cases/{id}/confirm
     * Confirm an employee exit case for HR/HQ review
     *
     * @param id
     * @param confirmEmployeeExitCaseRequest
     * @return ApiResponse<kotlin.collections.Map<kotlin.String, kotlinx.serialization.json.JsonElement>?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun confirmEmployeeExitCaseWithHttpInfo(id: java.util.UUID, confirmEmployeeExitCaseRequest: ConfirmEmployeeExitCaseRequest) : ApiResponse<kotlin.collections.Map<kotlin.String, kotlinx.serialization.json.JsonElement>?> = withContext(Dispatchers.IO) {
        val localVariableConfig = confirmEmployeeExitCaseRequestConfig(id = id, confirmEmployeeExitCaseRequest = confirmEmployeeExitCaseRequest)

        return@withContext request<ConfirmEmployeeExitCaseRequest, kotlin.collections.Map<kotlin.String, kotlinx.serialization.json.JsonElement>>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation confirmEmployeeExitCase
     *
     * @param id
     * @param confirmEmployeeExitCaseRequest
     * @return RequestConfig
     */
    fun confirmEmployeeExitCaseRequestConfig(id: java.util.UUID, confirmEmployeeExitCaseRequest: ConfirmEmployeeExitCaseRequest) : RequestConfig<ConfirmEmployeeExitCaseRequest> {
        val localVariableBody = confirmEmployeeExitCaseRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/v1/hr/exit-cases/{id}/confirm".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /api/v1/hr/attendance-records/me
     * Record the signed-in employee&#39;s attendance transition
     * Appends a mobile/PC attendance fact and an immutable payroll material reference. Payroll calculation remains blocked by the legal gate.
     * @param createEmployeeAttendanceRecordRequest
     * @return EmployeeAttendanceRecord
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun createMyEmployeeAttendanceRecord(createEmployeeAttendanceRecordRequest: CreateEmployeeAttendanceRecordRequest) : EmployeeAttendanceRecord = withContext(Dispatchers.IO) {
        val localVarResponse = createMyEmployeeAttendanceRecordWithHttpInfo(createEmployeeAttendanceRecordRequest = createEmployeeAttendanceRecordRequest)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as EmployeeAttendanceRecord
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /api/v1/hr/attendance-records/me
     * Record the signed-in employee&#39;s attendance transition
     * Appends a mobile/PC attendance fact and an immutable payroll material reference. Payroll calculation remains blocked by the legal gate.
     * @param createEmployeeAttendanceRecordRequest
     * @return ApiResponse<EmployeeAttendanceRecord?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun createMyEmployeeAttendanceRecordWithHttpInfo(createEmployeeAttendanceRecordRequest: CreateEmployeeAttendanceRecordRequest) : ApiResponse<EmployeeAttendanceRecord?> = withContext(Dispatchers.IO) {
        val localVariableConfig = createMyEmployeeAttendanceRecordRequestConfig(createEmployeeAttendanceRecordRequest = createEmployeeAttendanceRecordRequest)

        return@withContext request<CreateEmployeeAttendanceRecordRequest, EmployeeAttendanceRecord>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation createMyEmployeeAttendanceRecord
     *
     * @param createEmployeeAttendanceRecordRequest
     * @return RequestConfig
     */
    fun createMyEmployeeAttendanceRecordRequestConfig(createEmployeeAttendanceRecordRequest: CreateEmployeeAttendanceRecordRequest) : RequestConfig<CreateEmployeeAttendanceRecordRequest> {
        val localVariableBody = createEmployeeAttendanceRecordRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/v1/hr/attendance-records/me",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /api/v1/hr/exit-cases/{id}/approval-draft
     * Draft or submit employee exit approval documents
     *
     * @param id
     * @param draftEmployeeExitApprovalRequest
     * @return kotlin.collections.Map<kotlin.String, kotlinx.serialization.json.JsonElement>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun draftEmployeeExitApproval(id: java.util.UUID, draftEmployeeExitApprovalRequest: DraftEmployeeExitApprovalRequest) : kotlin.collections.Map<kotlin.String, kotlinx.serialization.json.JsonElement> = withContext(Dispatchers.IO) {
        val localVarResponse = draftEmployeeExitApprovalWithHttpInfo(id = id, draftEmployeeExitApprovalRequest = draftEmployeeExitApprovalRequest)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.collections.Map<kotlin.String, kotlinx.serialization.json.JsonElement>
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /api/v1/hr/exit-cases/{id}/approval-draft
     * Draft or submit employee exit approval documents
     *
     * @param id
     * @param draftEmployeeExitApprovalRequest
     * @return ApiResponse<kotlin.collections.Map<kotlin.String, kotlinx.serialization.json.JsonElement>?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun draftEmployeeExitApprovalWithHttpInfo(id: java.util.UUID, draftEmployeeExitApprovalRequest: DraftEmployeeExitApprovalRequest) : ApiResponse<kotlin.collections.Map<kotlin.String, kotlinx.serialization.json.JsonElement>?> = withContext(Dispatchers.IO) {
        val localVariableConfig = draftEmployeeExitApprovalRequestConfig(id = id, draftEmployeeExitApprovalRequest = draftEmployeeExitApprovalRequest)

        return@withContext request<DraftEmployeeExitApprovalRequest, kotlin.collections.Map<kotlin.String, kotlinx.serialization.json.JsonElement>>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation draftEmployeeExitApproval
     *
     * @param id
     * @param draftEmployeeExitApprovalRequest
     * @return RequestConfig
     */
    fun draftEmployeeExitApprovalRequestConfig(id: java.util.UUID, draftEmployeeExitApprovalRequest: DraftEmployeeExitApprovalRequest) : RequestConfig<DraftEmployeeExitApprovalRequest> {
        val localVariableBody = draftEmployeeExitApprovalRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/v1/hr/exit-cases/{id}/approval-draft".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /api/v1/hr/attendance-import/{run_id}/dry-run
     * Resolve employees and branches for a direct attendance import without writing facts
     *
     * @param runId
     * @return AttendanceImportDryRunSummary
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun dryRunAttendanceImport(runId: java.util.UUID) : AttendanceImportDryRunSummary = withContext(Dispatchers.IO) {
        val localVarResponse = dryRunAttendanceImportWithHttpInfo(runId = runId)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as AttendanceImportDryRunSummary
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /api/v1/hr/attendance-import/{run_id}/dry-run
     * Resolve employees and branches for a direct attendance import without writing facts
     *
     * @param runId
     * @return ApiResponse<AttendanceImportDryRunSummary?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun dryRunAttendanceImportWithHttpInfo(runId: java.util.UUID) : ApiResponse<AttendanceImportDryRunSummary?> = withContext(Dispatchers.IO) {
        val localVariableConfig = dryRunAttendanceImportRequestConfig(runId = runId)

        return@withContext request<Unit, AttendanceImportDryRunSummary>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation dryRunAttendanceImport
     *
     * @param runId
     * @return RequestConfig
     */
    fun dryRunAttendanceImportRequestConfig(runId: java.util.UUID) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/v1/hr/attendance-import/{run_id}/dry-run".replace("{"+"run_id"+"}", encodeURIComponent(runId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /api/v1/hr/absence-exit-dashboard
     * Read absence-to-exit HR dashboard
     * Lists absence alerts and exit-case workflow state for HR users who can triage Korean labor-law exit flows.
     * @param limit  (optional)
     * @param offset  (optional)
     * @param employeeId  (optional)
     * @return kotlin.collections.Map<kotlin.String, kotlinx.serialization.json.JsonElement>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun getHrAbsenceExitDashboard(limit: kotlin.Long? = null, offset: kotlin.Long? = null, employeeId: java.util.UUID? = null) : kotlin.collections.Map<kotlin.String, kotlinx.serialization.json.JsonElement> = withContext(Dispatchers.IO) {
        val localVarResponse = getHrAbsenceExitDashboardWithHttpInfo(limit = limit, offset = offset, employeeId = employeeId)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.collections.Map<kotlin.String, kotlinx.serialization.json.JsonElement>
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /api/v1/hr/absence-exit-dashboard
     * Read absence-to-exit HR dashboard
     * Lists absence alerts and exit-case workflow state for HR users who can triage Korean labor-law exit flows.
     * @param limit  (optional)
     * @param offset  (optional)
     * @param employeeId  (optional)
     * @return ApiResponse<kotlin.collections.Map<kotlin.String, kotlinx.serialization.json.JsonElement>?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun getHrAbsenceExitDashboardWithHttpInfo(limit: kotlin.Long?, offset: kotlin.Long?, employeeId: java.util.UUID?) : ApiResponse<kotlin.collections.Map<kotlin.String, kotlinx.serialization.json.JsonElement>?> = withContext(Dispatchers.IO) {
        val localVariableConfig = getHrAbsenceExitDashboardRequestConfig(limit = limit, offset = offset, employeeId = employeeId)

        return@withContext request<Unit, kotlin.collections.Map<kotlin.String, kotlinx.serialization.json.JsonElement>>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getHrAbsenceExitDashboard
     *
     * @param limit  (optional)
     * @param offset  (optional)
     * @param employeeId  (optional)
     * @return RequestConfig
     */
    fun getHrAbsenceExitDashboardRequestConfig(limit: kotlin.Long?, offset: kotlin.Long?, employeeId: java.util.UUID?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (limit != null) {
                    put("limit", listOf(limit.toString()))
                }
                if (offset != null) {
                    put("offset", listOf(offset.toString()))
                }
                if (employeeId != null) {
                    put("employee_id", listOf(employeeId.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/v1/hr/absence-exit-dashboard",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /api/v1/hr/org-chart
     * Read the tenant HR organization chart
     * Executive/admin/super-admin read model grouped by company, org unit, and position. Source workbook rows remain preserved in the employee directory.
     * @return HrOrgChartResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun getHrOrgChart() : HrOrgChartResponse = withContext(Dispatchers.IO) {
        val localVarResponse = getHrOrgChartWithHttpInfo()

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as HrOrgChartResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /api/v1/hr/org-chart
     * Read the tenant HR organization chart
     * Executive/admin/super-admin read model grouped by company, org unit, and position. Source workbook rows remain preserved in the employee directory.
     * @return ApiResponse<HrOrgChartResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun getHrOrgChartWithHttpInfo() : ApiResponse<HrOrgChartResponse?> = withContext(Dispatchers.IO) {
        val localVariableConfig = getHrOrgChartRequestConfig()

        return@withContext request<Unit, HrOrgChartResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getHrOrgChart
     *
     * @return RequestConfig
     */
    fun getHrOrgChartRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/v1/hr/org-chart",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /api/v1/hr/readiness-summary
     * Read HR data readiness counters
     * Returns import, payroll, annual-leave, and attendance readiness counters for org-wide HR operators without exposing raw workbook rows.
     * @return kotlin.collections.Map<kotlin.String, kotlinx.serialization.json.JsonElement>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun getHrReadinessSummary() : kotlin.collections.Map<kotlin.String, kotlinx.serialization.json.JsonElement> = withContext(Dispatchers.IO) {
        val localVarResponse = getHrReadinessSummaryWithHttpInfo()

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.collections.Map<kotlin.String, kotlinx.serialization.json.JsonElement>
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /api/v1/hr/readiness-summary
     * Read HR data readiness counters
     * Returns import, payroll, annual-leave, and attendance readiness counters for org-wide HR operators without exposing raw workbook rows.
     * @return ApiResponse<kotlin.collections.Map<kotlin.String, kotlinx.serialization.json.JsonElement>?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun getHrReadinessSummaryWithHttpInfo() : ApiResponse<kotlin.collections.Map<kotlin.String, kotlinx.serialization.json.JsonElement>?> = withContext(Dispatchers.IO) {
        val localVariableConfig = getHrReadinessSummaryRequestConfig()

        return@withContext request<Unit, kotlin.collections.Map<kotlin.String, kotlinx.serialization.json.JsonElement>>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getHrReadinessSummary
     *
     * @return RequestConfig
     */
    fun getHrReadinessSummaryRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/v1/hr/readiness-summary",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /api/v1/hr/attendance-import/summary
     * List governed direct attendance import runs
     * Lists attendance_direct import runs and summaries for authorized HR readers without exposing raw source rows.
     * @param limit  (optional, default to 500L)
     * @param offset  (optional, default to 0L)
     * @return AttendanceImportSummaryPage
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun listAttendanceImportSummary(limit: kotlin.Long? = 500L, offset: kotlin.Long? = 0L) : AttendanceImportSummaryPage = withContext(Dispatchers.IO) {
        val localVarResponse = listAttendanceImportSummaryWithHttpInfo(limit = limit, offset = offset)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as AttendanceImportSummaryPage
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /api/v1/hr/attendance-import/summary
     * List governed direct attendance import runs
     * Lists attendance_direct import runs and summaries for authorized HR readers without exposing raw source rows.
     * @param limit  (optional, default to 500L)
     * @param offset  (optional, default to 0L)
     * @return ApiResponse<AttendanceImportSummaryPage?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun listAttendanceImportSummaryWithHttpInfo(limit: kotlin.Long?, offset: kotlin.Long?) : ApiResponse<AttendanceImportSummaryPage?> = withContext(Dispatchers.IO) {
        val localVariableConfig = listAttendanceImportSummaryRequestConfig(limit = limit, offset = offset)

        return@withContext request<Unit, AttendanceImportSummaryPage>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation listAttendanceImportSummary
     *
     * @param limit  (optional, default to 500L)
     * @param offset  (optional, default to 0L)
     * @return RequestConfig
     */
    fun listAttendanceImportSummaryRequestConfig(limit: kotlin.Long?, offset: kotlin.Long?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (limit != null) {
                    put("limit", listOf(limit.toString()))
                }
                if (offset != null) {
                    put("offset", listOf(offset.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/v1/hr/attendance-import/summary",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /api/v1/hr/attendance-records
     * List employee attendance records for HR/payroll review
     * Authorized HR/payroll readers can inspect direct attendance records and their payroll material lineage.
     * @param employeeId  (optional)
     * @param limit  (optional, default to 500L)
     * @param offset  (optional, default to 0L)
     * @return EmployeeAttendanceRecordPage
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun listEmployeeAttendanceRecords(employeeId: java.util.UUID? = null, limit: kotlin.Long? = 500L, offset: kotlin.Long? = 0L) : EmployeeAttendanceRecordPage = withContext(Dispatchers.IO) {
        val localVarResponse = listEmployeeAttendanceRecordsWithHttpInfo(employeeId = employeeId, limit = limit, offset = offset)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as EmployeeAttendanceRecordPage
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /api/v1/hr/attendance-records
     * List employee attendance records for HR/payroll review
     * Authorized HR/payroll readers can inspect direct attendance records and their payroll material lineage.
     * @param employeeId  (optional)
     * @param limit  (optional, default to 500L)
     * @param offset  (optional, default to 0L)
     * @return ApiResponse<EmployeeAttendanceRecordPage?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun listEmployeeAttendanceRecordsWithHttpInfo(employeeId: java.util.UUID?, limit: kotlin.Long?, offset: kotlin.Long?) : ApiResponse<EmployeeAttendanceRecordPage?> = withContext(Dispatchers.IO) {
        val localVariableConfig = listEmployeeAttendanceRecordsRequestConfig(employeeId = employeeId, limit = limit, offset = offset)

        return@withContext request<Unit, EmployeeAttendanceRecordPage>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation listEmployeeAttendanceRecords
     *
     * @param employeeId  (optional)
     * @param limit  (optional, default to 500L)
     * @param offset  (optional, default to 0L)
     * @return RequestConfig
     */
    fun listEmployeeAttendanceRecordsRequestConfig(employeeId: java.util.UUID?, limit: kotlin.Long?, offset: kotlin.Long?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (employeeId != null) {
                    put("employee_id", listOf(employeeId.toString()))
                }
                if (limit != null) {
                    put("limit", listOf(limit.toString()))
                }
                if (offset != null) {
                    put("offset", listOf(offset.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/v1/hr/attendance-records",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /api/v1/hr/attendance-summary
     * List branch-scoped attendance summaries
     * Read-only summary over durable site attendance events. It exposes business clock-in facts, not raw geolocation pings.
     * @param limit  (optional, default to 500L)
     * @param offset  (optional, default to 0L)
     * @return AttendanceSummaryPage
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun listHrAttendanceSummary(limit: kotlin.Long? = 500L, offset: kotlin.Long? = 0L) : AttendanceSummaryPage = withContext(Dispatchers.IO) {
        val localVarResponse = listHrAttendanceSummaryWithHttpInfo(limit = limit, offset = offset)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as AttendanceSummaryPage
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /api/v1/hr/attendance-summary
     * List branch-scoped attendance summaries
     * Read-only summary over durable site attendance events. It exposes business clock-in facts, not raw geolocation pings.
     * @param limit  (optional, default to 500L)
     * @param offset  (optional, default to 0L)
     * @return ApiResponse<AttendanceSummaryPage?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun listHrAttendanceSummaryWithHttpInfo(limit: kotlin.Long?, offset: kotlin.Long?) : ApiResponse<AttendanceSummaryPage?> = withContext(Dispatchers.IO) {
        val localVariableConfig = listHrAttendanceSummaryRequestConfig(limit = limit, offset = offset)

        return@withContext request<Unit, AttendanceSummaryPage>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation listHrAttendanceSummary
     *
     * @param limit  (optional, default to 500L)
     * @param offset  (optional, default to 0L)
     * @return RequestConfig
     */
    fun listHrAttendanceSummaryRequestConfig(limit: kotlin.Long?, offset: kotlin.Long?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (limit != null) {
                    put("limit", listOf(limit.toString()))
                }
                if (offset != null) {
                    put("offset", listOf(offset.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/v1/hr/attendance-summary",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /api/v1/hr/leave-balances
     * List employee leave-balance rows
     * Read-only HR leave summary extracted from imported employee workbooks. Payroll and sensitive columns remain preserved in raw import JSON unless explicitly modeled.
     * @param limit  (optional, default to 500L)
     * @param offset  (optional, default to 0L)
     * @return LeaveBalancePage
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun listHrLeaveBalances(limit: kotlin.Long? = 500L, offset: kotlin.Long? = 0L) : LeaveBalancePage = withContext(Dispatchers.IO) {
        val localVarResponse = listHrLeaveBalancesWithHttpInfo(limit = limit, offset = offset)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as LeaveBalancePage
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /api/v1/hr/leave-balances
     * List employee leave-balance rows
     * Read-only HR leave summary extracted from imported employee workbooks. Payroll and sensitive columns remain preserved in raw import JSON unless explicitly modeled.
     * @param limit  (optional, default to 500L)
     * @param offset  (optional, default to 0L)
     * @return ApiResponse<LeaveBalancePage?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun listHrLeaveBalancesWithHttpInfo(limit: kotlin.Long?, offset: kotlin.Long?) : ApiResponse<LeaveBalancePage?> = withContext(Dispatchers.IO) {
        val localVariableConfig = listHrLeaveBalancesRequestConfig(limit = limit, offset = offset)

        return@withContext request<Unit, LeaveBalancePage>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation listHrLeaveBalances
     *
     * @param limit  (optional, default to 500L)
     * @param offset  (optional, default to 0L)
     * @return RequestConfig
     */
    fun listHrLeaveBalancesRequestConfig(limit: kotlin.Long?, offset: kotlin.Long?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (limit != null) {
                    put("limit", listOf(limit.toString()))
                }
                if (offset != null) {
                    put("offset", listOf(offset.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/v1/hr/leave-balances",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /api/v1/hr/attendance-records/me
     * List the signed-in employee&#39;s attendance records
     * Returns only records for the employee row explicitly linked to the authenticated user account.
     * @param limit  (optional, default to 500L)
     * @param offset  (optional, default to 0L)
     * @return EmployeeAttendanceRecordPage
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun listMyEmployeeAttendanceRecords(limit: kotlin.Long? = 500L, offset: kotlin.Long? = 0L) : EmployeeAttendanceRecordPage = withContext(Dispatchers.IO) {
        val localVarResponse = listMyEmployeeAttendanceRecordsWithHttpInfo(limit = limit, offset = offset)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as EmployeeAttendanceRecordPage
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /api/v1/hr/attendance-records/me
     * List the signed-in employee&#39;s attendance records
     * Returns only records for the employee row explicitly linked to the authenticated user account.
     * @param limit  (optional, default to 500L)
     * @param offset  (optional, default to 0L)
     * @return ApiResponse<EmployeeAttendanceRecordPage?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun listMyEmployeeAttendanceRecordsWithHttpInfo(limit: kotlin.Long?, offset: kotlin.Long?) : ApiResponse<EmployeeAttendanceRecordPage?> = withContext(Dispatchers.IO) {
        val localVariableConfig = listMyEmployeeAttendanceRecordsRequestConfig(limit = limit, offset = offset)

        return@withContext request<Unit, EmployeeAttendanceRecordPage>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation listMyEmployeeAttendanceRecords
     *
     * @param limit  (optional, default to 500L)
     * @param offset  (optional, default to 0L)
     * @return RequestConfig
     */
    fun listMyEmployeeAttendanceRecordsRequestConfig(limit: kotlin.Long?, offset: kotlin.Long?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (limit != null) {
                    put("limit", listOf(limit.toString()))
                }
                if (offset != null) {
                    put("offset", listOf(offset.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/v1/hr/attendance-records/me",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /api/v1/hr/attendance-import/preview
     * Preview a direct attendance workbook or CSV through the governed import ledger
     * Creates an immutable attendance_direct import run, preserves raw source rows, masks restricted values in the response, and records coordinate-free attendance facts only after dry-run and apply. Imported rows are lineage for payroll readiness, not payable payroll lines.
     * @param file The master-list .xlsx workbook.
     * @return AttendanceImportPreviewResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun previewAttendanceImport(file: java.io.File) : AttendanceImportPreviewResponse = withContext(Dispatchers.IO) {
        val localVarResponse = previewAttendanceImportWithHttpInfo(file = file)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as AttendanceImportPreviewResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /api/v1/hr/attendance-import/preview
     * Preview a direct attendance workbook or CSV through the governed import ledger
     * Creates an immutable attendance_direct import run, preserves raw source rows, masks restricted values in the response, and records coordinate-free attendance facts only after dry-run and apply. Imported rows are lineage for payroll readiness, not payable payroll lines.
     * @param file The master-list .xlsx workbook.
     * @return ApiResponse<AttendanceImportPreviewResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun previewAttendanceImportWithHttpInfo(file: java.io.File) : ApiResponse<AttendanceImportPreviewResponse?> = withContext(Dispatchers.IO) {
        val localVariableConfig = previewAttendanceImportRequestConfig(file = file)

        return@withContext request<Map<String, PartConfig<*>>, AttendanceImportPreviewResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation previewAttendanceImport
     *
     * @param file The master-list .xlsx workbook.
     * @return RequestConfig
     */
    fun previewAttendanceImportRequestConfig(file: java.io.File) : RequestConfig<Map<String, PartConfig<*>>> {
        val localVariableBody = mapOf(
            "file" to PartConfig(body = file, headers = mutableMapOf()),)
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/v1/hr/attendance-import/preview",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /api/v1/hr/exit-cases
     * Report an employee exit case from an absence signal
     * Creates an audited employee exit case that HR can confirm and prepare for settlement/approval workflows.
     * @param reportEmployeeExitCaseRequest
     * @return kotlin.collections.Map<kotlin.String, kotlinx.serialization.json.JsonElement>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun reportEmployeeExitCase(reportEmployeeExitCaseRequest: ReportEmployeeExitCaseRequest) : kotlin.collections.Map<kotlin.String, kotlinx.serialization.json.JsonElement> = withContext(Dispatchers.IO) {
        val localVarResponse = reportEmployeeExitCaseWithHttpInfo(reportEmployeeExitCaseRequest = reportEmployeeExitCaseRequest)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.collections.Map<kotlin.String, kotlinx.serialization.json.JsonElement>
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /api/v1/hr/exit-cases
     * Report an employee exit case from an absence signal
     * Creates an audited employee exit case that HR can confirm and prepare for settlement/approval workflows.
     * @param reportEmployeeExitCaseRequest
     * @return ApiResponse<kotlin.collections.Map<kotlin.String, kotlinx.serialization.json.JsonElement>?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun reportEmployeeExitCaseWithHttpInfo(reportEmployeeExitCaseRequest: ReportEmployeeExitCaseRequest) : ApiResponse<kotlin.collections.Map<kotlin.String, kotlinx.serialization.json.JsonElement>?> = withContext(Dispatchers.IO) {
        val localVariableConfig = reportEmployeeExitCaseRequestConfig(reportEmployeeExitCaseRequest = reportEmployeeExitCaseRequest)

        return@withContext request<ReportEmployeeExitCaseRequest, kotlin.collections.Map<kotlin.String, kotlinx.serialization.json.JsonElement>>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation reportEmployeeExitCase
     *
     * @param reportEmployeeExitCaseRequest
     * @return RequestConfig
     */
    fun reportEmployeeExitCaseRequestConfig(reportEmployeeExitCaseRequest: ReportEmployeeExitCaseRequest) : RequestConfig<ReportEmployeeExitCaseRequest> {
        val localVariableBody = reportEmployeeExitCaseRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/v1/hr/exit-cases",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
