/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.maintenance.api.client.api

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import com.maintenance.api.client.model.CreatePolicyRoleRequest
import com.maintenance.api.client.model.ErrorBody
import com.maintenance.api.client.model.PolicyAssignmentPreviewResponse
import com.maintenance.api.client.model.PolicyAuditEventResponse
import com.maintenance.api.client.model.PolicyFeatureResponse
import com.maintenance.api.client.model.PolicyRoleAssignmentResponse
import com.maintenance.api.client.model.PolicyRoleCatalogResponse
import com.maintenance.api.client.model.PolicyRoleResponse
import com.maintenance.api.client.model.PolicyRoleStatusPreviewRequest
import com.maintenance.api.client.model.PolicyRoleStatusPreviewResponse
import com.maintenance.api.client.model.PolicyRoleTemplateResponse
import com.maintenance.api.client.model.ReplacePolicyRoleAssignmentsRequest
import com.maintenance.api.client.model.UpdatePolicyRoleRequest
import com.maintenance.api.client.model.UpdatePolicyRoleStatusRequest

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import com.maintenance.api.client.infrastructure.ApiClient
import com.maintenance.api.client.infrastructure.ApiResponse
import com.maintenance.api.client.infrastructure.ClientException
import com.maintenance.api.client.infrastructure.ClientError
import com.maintenance.api.client.infrastructure.ServerException
import com.maintenance.api.client.infrastructure.ServerError
import com.maintenance.api.client.infrastructure.MultiValueMap
import com.maintenance.api.client.infrastructure.PartConfig
import com.maintenance.api.client.infrastructure.RequestConfig
import com.maintenance.api.client.infrastructure.RequestMethod
import com.maintenance.api.client.infrastructure.ResponseType
import com.maintenance.api.client.infrastructure.Success
import com.maintenance.api.client.infrastructure.toMultiValue
import com.maintenance.api.client.infrastructure.Serializer

open class PolicyApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "http://localhost")
        }
    }

    /**
     * POST /api/v1/policy/roles
     * Create a tenant custom role definition
     * Creates an audited, tenant-scoped custom role definition. Custom roles never replace built-in users.roles, but ACTIVE assignments can add runtime-effective ordinary feature grants on the next request. Elevated policy-management and scope-widening features are rejected.
     * @param createPolicyRoleRequest
     * @return PolicyRoleResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun createPolicyRole(createPolicyRoleRequest: CreatePolicyRoleRequest) : PolicyRoleResponse = withContext(Dispatchers.IO) {
        val localVarResponse = createPolicyRoleWithHttpInfo(createPolicyRoleRequest = createPolicyRoleRequest)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as PolicyRoleResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /api/v1/policy/roles
     * Create a tenant custom role definition
     * Creates an audited, tenant-scoped custom role definition. Custom roles never replace built-in users.roles, but ACTIVE assignments can add runtime-effective ordinary feature grants on the next request. Elevated policy-management and scope-widening features are rejected.
     * @param createPolicyRoleRequest
     * @return ApiResponse<PolicyRoleResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun createPolicyRoleWithHttpInfo(createPolicyRoleRequest: CreatePolicyRoleRequest) : ApiResponse<PolicyRoleResponse?> = withContext(Dispatchers.IO) {
        val localVariableConfig = createPolicyRoleRequestConfig(createPolicyRoleRequest = createPolicyRoleRequest)

        return@withContext request<CreatePolicyRoleRequest, PolicyRoleResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation createPolicyRole
     *
     * @param createPolicyRoleRequest
     * @return RequestConfig
     */
    fun createPolicyRoleRequestConfig(createPolicyRoleRequest: CreatePolicyRoleRequest) : RequestConfig<CreatePolicyRoleRequest> {
        val localVariableBody = createPolicyRoleRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/v1/policy/roles",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /api/v1/policy/assignments
     * List custom-role assignments for one user
     * Returns custom-role assignments for a visible user. ACTIVE assignments are audited and can add runtime-effective ordinary feature grants on the next request; DRAFT/RETIRED roles remain inert.
     * @param userId
     * @return kotlin.collections.List<PolicyRoleAssignmentResponse>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun listPolicyAssignments(userId: java.util.UUID) : kotlin.collections.List<PolicyRoleAssignmentResponse> = withContext(Dispatchers.IO) {
        val localVarResponse = listPolicyAssignmentsWithHttpInfo(userId = userId)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.collections.List<PolicyRoleAssignmentResponse>
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /api/v1/policy/assignments
     * List custom-role assignments for one user
     * Returns custom-role assignments for a visible user. ACTIVE assignments are audited and can add runtime-effective ordinary feature grants on the next request; DRAFT/RETIRED roles remain inert.
     * @param userId
     * @return ApiResponse<kotlin.collections.List<PolicyRoleAssignmentResponse>?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun listPolicyAssignmentsWithHttpInfo(userId: java.util.UUID) : ApiResponse<kotlin.collections.List<PolicyRoleAssignmentResponse>?> = withContext(Dispatchers.IO) {
        val localVariableConfig = listPolicyAssignmentsRequestConfig(userId = userId)

        return@withContext request<Unit, kotlin.collections.List<PolicyRoleAssignmentResponse>>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation listPolicyAssignments
     *
     * @param userId
     * @return RequestConfig
     */
    fun listPolicyAssignmentsRequestConfig(userId: java.util.UUID) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                put("user_id", listOf(userId.toString()))
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/v1/policy/assignments",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /api/v1/policy/audit-events
     * List Policy Studio audit evidence
     * Returns append-only policy audit events for the current tenant. This is a read-only evidence timeline for RoleManage holders and includes only policy role and planned-assignment events, not unrelated tenant audit rows.
     * @param limit  (optional, default to 20L)
     * @return kotlin.collections.List<PolicyAuditEventResponse>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun listPolicyAuditEvents(limit: kotlin.Long? = 20L) : kotlin.collections.List<PolicyAuditEventResponse> = withContext(Dispatchers.IO) {
        val localVarResponse = listPolicyAuditEventsWithHttpInfo(limit = limit)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.collections.List<PolicyAuditEventResponse>
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /api/v1/policy/audit-events
     * List Policy Studio audit evidence
     * Returns append-only policy audit events for the current tenant. This is a read-only evidence timeline for RoleManage holders and includes only policy role and planned-assignment events, not unrelated tenant audit rows.
     * @param limit  (optional, default to 20L)
     * @return ApiResponse<kotlin.collections.List<PolicyAuditEventResponse>?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun listPolicyAuditEventsWithHttpInfo(limit: kotlin.Long?) : ApiResponse<kotlin.collections.List<PolicyAuditEventResponse>?> = withContext(Dispatchers.IO) {
        val localVariableConfig = listPolicyAuditEventsRequestConfig(limit = limit)

        return@withContext request<Unit, kotlin.collections.List<PolicyAuditEventResponse>>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation listPolicyAuditEvents
     *
     * @param limit  (optional, default to 20L)
     * @return RequestConfig
     */
    fun listPolicyAuditEventsRequestConfig(limit: kotlin.Long?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (limit != null) {
                    put("limit", listOf(limit.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/v1/policy/audit-events",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /api/v1/policy/features
     * List canonical policy feature catalog for Policy Studio
     *
     * @return kotlin.collections.List<PolicyFeatureResponse>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun listPolicyFeatures() : kotlin.collections.List<PolicyFeatureResponse> = withContext(Dispatchers.IO) {
        val localVarResponse = listPolicyFeaturesWithHttpInfo()

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.collections.List<PolicyFeatureResponse>
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /api/v1/policy/features
     * List canonical policy feature catalog for Policy Studio
     *
     * @return ApiResponse<kotlin.collections.List<PolicyFeatureResponse>?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun listPolicyFeaturesWithHttpInfo() : ApiResponse<kotlin.collections.List<PolicyFeatureResponse>?> = withContext(Dispatchers.IO) {
        val localVariableConfig = listPolicyFeaturesRequestConfig()

        return@withContext request<Unit, kotlin.collections.List<PolicyFeatureResponse>>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation listPolicyFeatures
     *
     * @return RequestConfig
     */
    fun listPolicyFeaturesRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/v1/policy/features",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /api/v1/policy/role-templates
     * List safe starter templates for tenant custom roles
     * Returns built-in starter templates that can be copied into a tenant custom role definition. Templates never grant elevated policy-management features. Templates do not affect runtime authorization until copied into an ACTIVE assigned custom role; unsupported/elevated grants remain inert.
     * @return kotlin.collections.List<PolicyRoleTemplateResponse>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun listPolicyRoleTemplates() : kotlin.collections.List<PolicyRoleTemplateResponse> = withContext(Dispatchers.IO) {
        val localVarResponse = listPolicyRoleTemplatesWithHttpInfo()

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.collections.List<PolicyRoleTemplateResponse>
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /api/v1/policy/role-templates
     * List safe starter templates for tenant custom roles
     * Returns built-in starter templates that can be copied into a tenant custom role definition. Templates never grant elevated policy-management features. Templates do not affect runtime authorization until copied into an ACTIVE assigned custom role; unsupported/elevated grants remain inert.
     * @return ApiResponse<kotlin.collections.List<PolicyRoleTemplateResponse>?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun listPolicyRoleTemplatesWithHttpInfo() : ApiResponse<kotlin.collections.List<PolicyRoleTemplateResponse>?> = withContext(Dispatchers.IO) {
        val localVariableConfig = listPolicyRoleTemplatesRequestConfig()

        return@withContext request<Unit, kotlin.collections.List<PolicyRoleTemplateResponse>>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation listPolicyRoleTemplates
     *
     * @return RequestConfig
     */
    fun listPolicyRoleTemplatesRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/v1/policy/role-templates",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /api/v1/policy/roles
     * List built-in role templates and tenant custom roles
     *
     * @return PolicyRoleCatalogResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun listPolicyRoles() : PolicyRoleCatalogResponse = withContext(Dispatchers.IO) {
        val localVarResponse = listPolicyRolesWithHttpInfo()

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as PolicyRoleCatalogResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /api/v1/policy/roles
     * List built-in role templates and tenant custom roles
     *
     * @return ApiResponse<PolicyRoleCatalogResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun listPolicyRolesWithHttpInfo() : ApiResponse<PolicyRoleCatalogResponse?> = withContext(Dispatchers.IO) {
        val localVariableConfig = listPolicyRolesRequestConfig()

        return@withContext request<Unit, PolicyRoleCatalogResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation listPolicyRoles
     *
     * @return RequestConfig
     */
    fun listPolicyRolesRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/v1/policy/roles",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /api/v1/policy/users/{id}/assignment-preview
     * Preview requested custom-role assignment impact for one user
     * Computes requested-vs-current planned custom-role assignment deltas and feature grants for a visible user. This is an impact-preview surface only: it does not write assignments and does not publish runtime authorization.
     * @param id
     * @param replacePolicyRoleAssignmentsRequest
     * @return PolicyAssignmentPreviewResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun previewPolicyAssignments(id: java.util.UUID, replacePolicyRoleAssignmentsRequest: ReplacePolicyRoleAssignmentsRequest) : PolicyAssignmentPreviewResponse = withContext(Dispatchers.IO) {
        val localVarResponse = previewPolicyAssignmentsWithHttpInfo(id = id, replacePolicyRoleAssignmentsRequest = replacePolicyRoleAssignmentsRequest)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as PolicyAssignmentPreviewResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /api/v1/policy/users/{id}/assignment-preview
     * Preview requested custom-role assignment impact for one user
     * Computes requested-vs-current planned custom-role assignment deltas and feature grants for a visible user. This is an impact-preview surface only: it does not write assignments and does not publish runtime authorization.
     * @param id
     * @param replacePolicyRoleAssignmentsRequest
     * @return ApiResponse<PolicyAssignmentPreviewResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun previewPolicyAssignmentsWithHttpInfo(id: java.util.UUID, replacePolicyRoleAssignmentsRequest: ReplacePolicyRoleAssignmentsRequest) : ApiResponse<PolicyAssignmentPreviewResponse?> = withContext(Dispatchers.IO) {
        val localVariableConfig = previewPolicyAssignmentsRequestConfig(id = id, replacePolicyRoleAssignmentsRequest = replacePolicyRoleAssignmentsRequest)

        return@withContext request<ReplacePolicyRoleAssignmentsRequest, PolicyAssignmentPreviewResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation previewPolicyAssignments
     *
     * @param id
     * @param replacePolicyRoleAssignmentsRequest
     * @return RequestConfig
     */
    fun previewPolicyAssignmentsRequestConfig(id: java.util.UUID, replacePolicyRoleAssignmentsRequest: ReplacePolicyRoleAssignmentsRequest) : RequestConfig<ReplacePolicyRoleAssignmentsRequest> {
        val localVariableBody = replacePolicyRoleAssignmentsRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/v1/policy/users/{id}/assignment-preview".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /api/v1/policy/roles/{id}/status-preview
     * Preview custom-role lifecycle status impact
     * Returns a read-only before/after impact summary for publishing, rolling back, or retiring a custom role. This endpoint never mutates policy, does not require a passkey assertion, and reminds callers that the subsequent status update is a sensitive passkey step-up action. Allowed transitions are DRAFT→ACTIVE, ACTIVE→DRAFT, and ACTIVE→RETIRED; RETIRED is terminal.
     * @param id
     * @param policyRoleStatusPreviewRequest
     * @return PolicyRoleStatusPreviewResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun previewPolicyRoleStatus(id: java.util.UUID, policyRoleStatusPreviewRequest: PolicyRoleStatusPreviewRequest) : PolicyRoleStatusPreviewResponse = withContext(Dispatchers.IO) {
        val localVarResponse = previewPolicyRoleStatusWithHttpInfo(id = id, policyRoleStatusPreviewRequest = policyRoleStatusPreviewRequest)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as PolicyRoleStatusPreviewResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /api/v1/policy/roles/{id}/status-preview
     * Preview custom-role lifecycle status impact
     * Returns a read-only before/after impact summary for publishing, rolling back, or retiring a custom role. This endpoint never mutates policy, does not require a passkey assertion, and reminds callers that the subsequent status update is a sensitive passkey step-up action. Allowed transitions are DRAFT→ACTIVE, ACTIVE→DRAFT, and ACTIVE→RETIRED; RETIRED is terminal.
     * @param id
     * @param policyRoleStatusPreviewRequest
     * @return ApiResponse<PolicyRoleStatusPreviewResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun previewPolicyRoleStatusWithHttpInfo(id: java.util.UUID, policyRoleStatusPreviewRequest: PolicyRoleStatusPreviewRequest) : ApiResponse<PolicyRoleStatusPreviewResponse?> = withContext(Dispatchers.IO) {
        val localVariableConfig = previewPolicyRoleStatusRequestConfig(id = id, policyRoleStatusPreviewRequest = policyRoleStatusPreviewRequest)

        return@withContext request<PolicyRoleStatusPreviewRequest, PolicyRoleStatusPreviewResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation previewPolicyRoleStatus
     *
     * @param id
     * @param policyRoleStatusPreviewRequest
     * @return RequestConfig
     */
    fun previewPolicyRoleStatusRequestConfig(id: java.util.UUID, policyRoleStatusPreviewRequest: PolicyRoleStatusPreviewRequest) : RequestConfig<PolicyRoleStatusPreviewRequest> {
        val localVariableBody = policyRoleStatusPreviewRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/v1/policy/roles/{id}/status-preview".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * PUT /api/v1/policy/users/{id}/assignments
     * Replace one user&#39;s custom-role assignments
     * Replaces custom-role assignments for a visible user and bumps the tenant policy version. This is a sensitive policy action requiring a fresh passkey step-up. ACTIVE assigned roles publish supported ordinary feature grants into runtime authorization on the next request; unsupported conditions/elevated grants remain inert.
     * @param id
     * @param replacePolicyRoleAssignmentsRequest
     * @return kotlin.collections.List<PolicyRoleAssignmentResponse>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun replacePolicyAssignments(id: java.util.UUID, replacePolicyRoleAssignmentsRequest: ReplacePolicyRoleAssignmentsRequest) : kotlin.collections.List<PolicyRoleAssignmentResponse> = withContext(Dispatchers.IO) {
        val localVarResponse = replacePolicyAssignmentsWithHttpInfo(id = id, replacePolicyRoleAssignmentsRequest = replacePolicyRoleAssignmentsRequest)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.collections.List<PolicyRoleAssignmentResponse>
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PUT /api/v1/policy/users/{id}/assignments
     * Replace one user&#39;s custom-role assignments
     * Replaces custom-role assignments for a visible user and bumps the tenant policy version. This is a sensitive policy action requiring a fresh passkey step-up. ACTIVE assigned roles publish supported ordinary feature grants into runtime authorization on the next request; unsupported conditions/elevated grants remain inert.
     * @param id
     * @param replacePolicyRoleAssignmentsRequest
     * @return ApiResponse<kotlin.collections.List<PolicyRoleAssignmentResponse>?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun replacePolicyAssignmentsWithHttpInfo(id: java.util.UUID, replacePolicyRoleAssignmentsRequest: ReplacePolicyRoleAssignmentsRequest) : ApiResponse<kotlin.collections.List<PolicyRoleAssignmentResponse>?> = withContext(Dispatchers.IO) {
        val localVariableConfig = replacePolicyAssignmentsRequestConfig(id = id, replacePolicyRoleAssignmentsRequest = replacePolicyRoleAssignmentsRequest)

        return@withContext request<ReplacePolicyRoleAssignmentsRequest, kotlin.collections.List<PolicyRoleAssignmentResponse>>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation replacePolicyAssignments
     *
     * @param id
     * @param replacePolicyRoleAssignmentsRequest
     * @return RequestConfig
     */
    fun replacePolicyAssignmentsRequestConfig(id: java.util.UUID, replacePolicyRoleAssignmentsRequest: ReplacePolicyRoleAssignmentsRequest) : RequestConfig<ReplacePolicyRoleAssignmentsRequest> {
        val localVariableBody = replacePolicyRoleAssignmentsRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PUT,
            path = "/api/v1/policy/users/{id}/assignments".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * PATCH /api/v1/policy/roles/{id}
     * Update a tenant custom role definition
     * Updates mutable custom-role metadata, permissions, and ABAC/PBAC conditions. The role key and lifecycle status are not changed by this route. This is a sensitive policy-definition action: callers must have RoleManage, pass delegated-scope guardrails, and supply a fresh passkey step-up assertion. ACTIVE assigned custom-role changes become runtime-effective ordinary feature grants on the next request; unsupported ABAC/PBAC conditions and elevated/scope-widening features remain inert.
     * @param id
     * @param updatePolicyRoleRequest
     * @return PolicyRoleResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun updatePolicyRole(id: java.util.UUID, updatePolicyRoleRequest: UpdatePolicyRoleRequest) : PolicyRoleResponse = withContext(Dispatchers.IO) {
        val localVarResponse = updatePolicyRoleWithHttpInfo(id = id, updatePolicyRoleRequest = updatePolicyRoleRequest)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as PolicyRoleResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PATCH /api/v1/policy/roles/{id}
     * Update a tenant custom role definition
     * Updates mutable custom-role metadata, permissions, and ABAC/PBAC conditions. The role key and lifecycle status are not changed by this route. This is a sensitive policy-definition action: callers must have RoleManage, pass delegated-scope guardrails, and supply a fresh passkey step-up assertion. ACTIVE assigned custom-role changes become runtime-effective ordinary feature grants on the next request; unsupported ABAC/PBAC conditions and elevated/scope-widening features remain inert.
     * @param id
     * @param updatePolicyRoleRequest
     * @return ApiResponse<PolicyRoleResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun updatePolicyRoleWithHttpInfo(id: java.util.UUID, updatePolicyRoleRequest: UpdatePolicyRoleRequest) : ApiResponse<PolicyRoleResponse?> = withContext(Dispatchers.IO) {
        val localVariableConfig = updatePolicyRoleRequestConfig(id = id, updatePolicyRoleRequest = updatePolicyRoleRequest)

        return@withContext request<UpdatePolicyRoleRequest, PolicyRoleResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation updatePolicyRole
     *
     * @param id
     * @param updatePolicyRoleRequest
     * @return RequestConfig
     */
    fun updatePolicyRoleRequestConfig(id: java.util.UUID, updatePolicyRoleRequest: UpdatePolicyRoleRequest) : RequestConfig<UpdatePolicyRoleRequest> {
        val localVariableBody = updatePolicyRoleRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PATCH,
            path = "/api/v1/policy/roles/{id}".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * PATCH /api/v1/policy/roles/{id}/status
     * Publish, roll back, or retire a tenant custom role
     * Changes a custom role lifecycle state. This is a sensitive policy action: callers must have RoleManage and supply a fresh passkey step-up assertion proving the actor, not just the bearer token, performed the change.
     * @param id
     * @param updatePolicyRoleStatusRequest
     * @return PolicyRoleResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun updatePolicyRoleStatus(id: java.util.UUID, updatePolicyRoleStatusRequest: UpdatePolicyRoleStatusRequest) : PolicyRoleResponse = withContext(Dispatchers.IO) {
        val localVarResponse = updatePolicyRoleStatusWithHttpInfo(id = id, updatePolicyRoleStatusRequest = updatePolicyRoleStatusRequest)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as PolicyRoleResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PATCH /api/v1/policy/roles/{id}/status
     * Publish, roll back, or retire a tenant custom role
     * Changes a custom role lifecycle state. This is a sensitive policy action: callers must have RoleManage and supply a fresh passkey step-up assertion proving the actor, not just the bearer token, performed the change.
     * @param id
     * @param updatePolicyRoleStatusRequest
     * @return ApiResponse<PolicyRoleResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun updatePolicyRoleStatusWithHttpInfo(id: java.util.UUID, updatePolicyRoleStatusRequest: UpdatePolicyRoleStatusRequest) : ApiResponse<PolicyRoleResponse?> = withContext(Dispatchers.IO) {
        val localVariableConfig = updatePolicyRoleStatusRequestConfig(id = id, updatePolicyRoleStatusRequest = updatePolicyRoleStatusRequest)

        return@withContext request<UpdatePolicyRoleStatusRequest, PolicyRoleResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation updatePolicyRoleStatus
     *
     * @param id
     * @param updatePolicyRoleStatusRequest
     * @return RequestConfig
     */
    fun updatePolicyRoleStatusRequestConfig(id: java.util.UUID, updatePolicyRoleStatusRequest: UpdatePolicyRoleStatusRequest) : RequestConfig<UpdatePolicyRoleStatusRequest> {
        val localVariableBody = updatePolicyRoleStatusRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PATCH,
            path = "/api/v1/policy/roles/{id}/status".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
