/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.maintenance.api.client.api

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import com.maintenance.api.client.model.CreateListingRequest
import com.maintenance.api.client.model.CreateListingResponse
import com.maintenance.api.client.model.CustomerInquiryPage
import com.maintenance.api.client.model.ErrorBody
import com.maintenance.api.client.model.InquiryStatus
import com.maintenance.api.client.model.ListingCondition
import com.maintenance.api.client.model.ListingKind
import com.maintenance.api.client.model.ListingType
import com.maintenance.api.client.model.SalesListingPage
import com.maintenance.api.client.model.UpdateInquiryStatusRequest
import com.maintenance.api.client.model.UpdateListingRequest

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import com.maintenance.api.client.infrastructure.ApiClient
import com.maintenance.api.client.infrastructure.ApiResponse
import com.maintenance.api.client.infrastructure.ClientException
import com.maintenance.api.client.infrastructure.ClientError
import com.maintenance.api.client.infrastructure.ServerException
import com.maintenance.api.client.infrastructure.ServerError
import com.maintenance.api.client.infrastructure.MultiValueMap
import com.maintenance.api.client.infrastructure.PartConfig
import com.maintenance.api.client.infrastructure.RequestConfig
import com.maintenance.api.client.infrastructure.RequestMethod
import com.maintenance.api.client.infrastructure.ResponseType
import com.maintenance.api.client.infrastructure.Success
import com.maintenance.api.client.infrastructure.toMultiValue
import com.maintenance.api.client.infrastructure.Serializer

open class SalesApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "http://localhost")
        }
    }

    /**
     * GET /api/v1/sales/listings
     * List all sales listings for the admin console (#6)
     * Admin catalog read (SalesManage). Unlike the public storefront, returns listings in every status (including DRAFT/SOLD/WITHDRAWN). Optional filters narrow by fuel/drive kind and sale/rental type; results are paged.
     * @param kind  (optional)
     * @param condition  (optional)
     * @param listingType  (optional)
     * @param limit  (optional, default to 24L)
     * @param offset  (optional, default to 0L)
     * @return SalesListingPage
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun adminListListings(kind: ListingKind? = null, condition: ListingCondition? = null, listingType: ListingType? = null, limit: kotlin.Long? = 24L, offset: kotlin.Long? = 0L) : SalesListingPage = withContext(Dispatchers.IO) {
        val localVarResponse = adminListListingsWithHttpInfo(kind = kind, condition = condition, listingType = listingType, limit = limit, offset = offset)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as SalesListingPage
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /api/v1/sales/listings
     * List all sales listings for the admin console (#6)
     * Admin catalog read (SalesManage). Unlike the public storefront, returns listings in every status (including DRAFT/SOLD/WITHDRAWN). Optional filters narrow by fuel/drive kind and sale/rental type; results are paged.
     * @param kind  (optional)
     * @param condition  (optional)
     * @param listingType  (optional)
     * @param limit  (optional, default to 24L)
     * @param offset  (optional, default to 0L)
     * @return ApiResponse<SalesListingPage?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun adminListListingsWithHttpInfo(kind: ListingKind?, condition: ListingCondition?, listingType: ListingType?, limit: kotlin.Long?, offset: kotlin.Long?) : ApiResponse<SalesListingPage?> = withContext(Dispatchers.IO) {
        val localVariableConfig = adminListListingsRequestConfig(kind = kind, condition = condition, listingType = listingType, limit = limit, offset = offset)

        return@withContext request<Unit, SalesListingPage>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation adminListListings
     *
     * @param kind  (optional)
     * @param condition  (optional)
     * @param listingType  (optional)
     * @param limit  (optional, default to 24L)
     * @param offset  (optional, default to 0L)
     * @return RequestConfig
     */
    fun adminListListingsRequestConfig(kind: ListingKind?, condition: ListingCondition?, listingType: ListingType?, limit: kotlin.Long?, offset: kotlin.Long?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (kind != null) {
                    put("kind", listOf(kind.toString()))
                }
                if (condition != null) {
                    put("condition", listOf(condition.toString()))
                }
                if (listingType != null) {
                    put("listing_type", listOf(listingType.toString()))
                }
                if (limit != null) {
                    put("limit", listOf(limit.toString()))
                }
                if (offset != null) {
                    put("offset", listOf(offset.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/v1/sales/listings",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /api/v1/sales/listings
     * Create a sales listing (#6)
     * Admin-gated (SalesManage). Creates a new catalog listing and returns its server-generated id.
     * @param createListingRequest
     * @return CreateListingResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun createListing(createListingRequest: CreateListingRequest) : CreateListingResponse = withContext(Dispatchers.IO) {
        val localVarResponse = createListingWithHttpInfo(createListingRequest = createListingRequest)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as CreateListingResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /api/v1/sales/listings
     * Create a sales listing (#6)
     * Admin-gated (SalesManage). Creates a new catalog listing and returns its server-generated id.
     * @param createListingRequest
     * @return ApiResponse<CreateListingResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun createListingWithHttpInfo(createListingRequest: CreateListingRequest) : ApiResponse<CreateListingResponse?> = withContext(Dispatchers.IO) {
        val localVariableConfig = createListingRequestConfig(createListingRequest = createListingRequest)

        return@withContext request<CreateListingRequest, CreateListingResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation createListing
     *
     * @param createListingRequest
     * @return RequestConfig
     */
    fun createListingRequestConfig(createListingRequest: CreateListingRequest) : RequestConfig<CreateListingRequest> {
        val localVariableBody = createListingRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/v1/sales/listings",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * DELETE /api/v1/sales/listings/{id}
     * Archive a sales listing (#6)
     * Admin-gated (SalesManage). Soft-archives the listing (status -&gt; WITHDRAWN) and removes it from the public catalog; the row and its media are preserved for history/object-graph integrity, never hard-deleted.
     * @param id
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun deleteListing(id: java.util.UUID) : Unit = withContext(Dispatchers.IO) {
        val localVarResponse = deleteListingWithHttpInfo(id = id)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * DELETE /api/v1/sales/listings/{id}
     * Archive a sales listing (#6)
     * Admin-gated (SalesManage). Soft-archives the listing (status -&gt; WITHDRAWN) and removes it from the public catalog; the row and its media are preserved for history/object-graph integrity, never hard-deleted.
     * @param id
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun deleteListingWithHttpInfo(id: java.util.UUID) : ApiResponse<Unit?> = withContext(Dispatchers.IO) {
        val localVariableConfig = deleteListingRequestConfig(id = id)

        return@withContext request<Unit, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation deleteListing
     *
     * @param id
     * @return RequestConfig
     */
    fun deleteListingRequestConfig(id: java.util.UUID) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/api/v1/sales/listings/{id}".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /api/v1/sales/inquiries
     * List customer inquiries for the admin inbox (#6)
     * Admin-gated (SalesManage) inquiry inbox. Optional status filter; results are paged.
     * @param status  (optional)
     * @param limit  (optional, default to 50L)
     * @param offset  (optional, default to 0L)
     * @return CustomerInquiryPage
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun listInquiries(status: InquiryStatus? = null, limit: kotlin.Long? = 50L, offset: kotlin.Long? = 0L) : CustomerInquiryPage = withContext(Dispatchers.IO) {
        val localVarResponse = listInquiriesWithHttpInfo(status = status, limit = limit, offset = offset)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as CustomerInquiryPage
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /api/v1/sales/inquiries
     * List customer inquiries for the admin inbox (#6)
     * Admin-gated (SalesManage) inquiry inbox. Optional status filter; results are paged.
     * @param status  (optional)
     * @param limit  (optional, default to 50L)
     * @param offset  (optional, default to 0L)
     * @return ApiResponse<CustomerInquiryPage?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun listInquiriesWithHttpInfo(status: InquiryStatus?, limit: kotlin.Long?, offset: kotlin.Long?) : ApiResponse<CustomerInquiryPage?> = withContext(Dispatchers.IO) {
        val localVariableConfig = listInquiriesRequestConfig(status = status, limit = limit, offset = offset)

        return@withContext request<Unit, CustomerInquiryPage>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation listInquiries
     *
     * @param status  (optional)
     * @param limit  (optional, default to 50L)
     * @param offset  (optional, default to 0L)
     * @return RequestConfig
     */
    fun listInquiriesRequestConfig(status: InquiryStatus?, limit: kotlin.Long?, offset: kotlin.Long?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (status != null) {
                    put("status", listOf(status.toString()))
                }
                if (limit != null) {
                    put("limit", listOf(limit.toString()))
                }
                if (offset != null) {
                    put("offset", listOf(offset.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/v1/sales/inquiries",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * PATCH /api/v1/sales/inquiries/{id}
     * Update a customer inquiry&#39;s triage status (#6)
     * Admin-gated (SalesManage). Transitions an inquiry between NEW/CONTACTED/CLOSED.
     * @param id
     * @param updateInquiryStatusRequest
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun updateInquiryStatus(id: java.util.UUID, updateInquiryStatusRequest: UpdateInquiryStatusRequest) : Unit = withContext(Dispatchers.IO) {
        val localVarResponse = updateInquiryStatusWithHttpInfo(id = id, updateInquiryStatusRequest = updateInquiryStatusRequest)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PATCH /api/v1/sales/inquiries/{id}
     * Update a customer inquiry&#39;s triage status (#6)
     * Admin-gated (SalesManage). Transitions an inquiry between NEW/CONTACTED/CLOSED.
     * @param id
     * @param updateInquiryStatusRequest
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun updateInquiryStatusWithHttpInfo(id: java.util.UUID, updateInquiryStatusRequest: UpdateInquiryStatusRequest) : ApiResponse<Unit?> = withContext(Dispatchers.IO) {
        val localVariableConfig = updateInquiryStatusRequestConfig(id = id, updateInquiryStatusRequest = updateInquiryStatusRequest)

        return@withContext request<UpdateInquiryStatusRequest, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation updateInquiryStatus
     *
     * @param id
     * @param updateInquiryStatusRequest
     * @return RequestConfig
     */
    fun updateInquiryStatusRequestConfig(id: java.util.UUID, updateInquiryStatusRequest: UpdateInquiryStatusRequest) : RequestConfig<UpdateInquiryStatusRequest> {
        val localVariableBody = updateInquiryStatusRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PATCH,
            path = "/api/v1/sales/inquiries/{id}".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * PATCH /api/v1/sales/listings/{id}
     * Update a sales listing (#6)
     * Admin-gated (SalesManage). Partial update: absent keys are left unchanged; nullable keys explicitly set to null clear the column. At least one field must be supplied.
     * @param id
     * @param updateListingRequest
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun updateListing(id: java.util.UUID, updateListingRequest: UpdateListingRequest) : Unit = withContext(Dispatchers.IO) {
        val localVarResponse = updateListingWithHttpInfo(id = id, updateListingRequest = updateListingRequest)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PATCH /api/v1/sales/listings/{id}
     * Update a sales listing (#6)
     * Admin-gated (SalesManage). Partial update: absent keys are left unchanged; nullable keys explicitly set to null clear the column. At least one field must be supplied.
     * @param id
     * @param updateListingRequest
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun updateListingWithHttpInfo(id: java.util.UUID, updateListingRequest: UpdateListingRequest) : ApiResponse<Unit?> = withContext(Dispatchers.IO) {
        val localVariableConfig = updateListingRequestConfig(id = id, updateListingRequest = updateListingRequest)

        return@withContext request<UpdateListingRequest, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation updateListing
     *
     * @param id
     * @param updateListingRequest
     * @return RequestConfig
     */
    fun updateListingRequestConfig(id: java.util.UUID, updateListingRequest: UpdateListingRequest) : RequestConfig<UpdateListingRequest> {
        val localVariableBody = updateListingRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PATCH,
            path = "/api/v1/sales/listings/{id}".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
