/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.maintenance.api.client.api

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import com.maintenance.api.client.model.ErrorBody
import com.maintenance.api.client.model.InquiryAck
import com.maintenance.api.client.model.ListingCondition
import com.maintenance.api.client.model.ListingKind
import com.maintenance.api.client.model.ListingType
import com.maintenance.api.client.model.SalesListingPage
import com.maintenance.api.client.model.SalesListingView
import com.maintenance.api.client.model.SubmitInquiryRequest

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import com.maintenance.api.client.infrastructure.ApiClient
import com.maintenance.api.client.infrastructure.ApiResponse
import com.maintenance.api.client.infrastructure.ClientException
import com.maintenance.api.client.infrastructure.ClientError
import com.maintenance.api.client.infrastructure.ServerException
import com.maintenance.api.client.infrastructure.ServerError
import com.maintenance.api.client.infrastructure.MultiValueMap
import com.maintenance.api.client.infrastructure.PartConfig
import com.maintenance.api.client.infrastructure.RequestConfig
import com.maintenance.api.client.infrastructure.RequestMethod
import com.maintenance.api.client.infrastructure.ResponseType
import com.maintenance.api.client.infrastructure.Success
import com.maintenance.api.client.infrastructure.toMultiValue
import com.maintenance.api.client.infrastructure.Serializer

open class StorefrontApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "http://localhost")
        }
    }

    /**
     * GET /api/v1/storefront/listings/{id}
     * Read one public sales listing (#6)
     * Public, unauthenticated read of a single storefront-visible listing. Returns 404 if the listing does not exist or is not public.
     * @param id
     * @return SalesListingView
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun storefrontGetListing(id: java.util.UUID) : SalesListingView = withContext(Dispatchers.IO) {
        val localVarResponse = storefrontGetListingWithHttpInfo(id = id)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as SalesListingView
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /api/v1/storefront/listings/{id}
     * Read one public sales listing (#6)
     * Public, unauthenticated read of a single storefront-visible listing. Returns 404 if the listing does not exist or is not public.
     * @param id
     * @return ApiResponse<SalesListingView?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun storefrontGetListingWithHttpInfo(id: java.util.UUID) : ApiResponse<SalesListingView?> = withContext(Dispatchers.IO) {
        val localVariableConfig = storefrontGetListingRequestConfig(id = id)

        return@withContext request<Unit, SalesListingView>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation storefrontGetListing
     *
     * @param id
     * @return RequestConfig
     */
    fun storefrontGetListingRequestConfig(id: java.util.UUID) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/v1/storefront/listings/{id}".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * GET /api/v1/storefront/listings/{id}/media/{media_id}
     * Serve one public sales-listing photo (#6)
     * Public, unauthenticated serve of one listing photo&#39;s bytes, streamed from the object store. The media must belong to the listing and the listing must be storefront-visible (published/reserved); otherwise 404. The response body is the raw image with its stored content type.
     * @param id
     * @param mediaId
     * @return java.io.File
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun storefrontGetListingMedia(id: java.util.UUID, mediaId: java.util.UUID) : java.io.File = withContext(Dispatchers.IO) {
        val localVarResponse = storefrontGetListingMediaWithHttpInfo(id = id, mediaId = mediaId)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as java.io.File
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /api/v1/storefront/listings/{id}/media/{media_id}
     * Serve one public sales-listing photo (#6)
     * Public, unauthenticated serve of one listing photo&#39;s bytes, streamed from the object store. The media must belong to the listing and the listing must be storefront-visible (published/reserved); otherwise 404. The response body is the raw image with its stored content type.
     * @param id
     * @param mediaId
     * @return ApiResponse<java.io.File?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun storefrontGetListingMediaWithHttpInfo(id: java.util.UUID, mediaId: java.util.UUID) : ApiResponse<java.io.File?> = withContext(Dispatchers.IO) {
        val localVariableConfig = storefrontGetListingMediaRequestConfig(id = id, mediaId = mediaId)

        return@withContext request<Unit, java.io.File>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation storefrontGetListingMedia
     *
     * @param id
     * @param mediaId
     * @return RequestConfig
     */
    fun storefrontGetListingMediaRequestConfig(id: java.util.UUID, mediaId: java.util.UUID) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/v1/storefront/listings/{id}/media/{media_id}".replace("{"+"id"+"}", encodeURIComponent(id.toString())).replace("{"+"media_id"+"}", encodeURIComponent(mediaId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * GET /api/v1/storefront/listings
     * List published sales listings for the public storefront (#6)
     * Public, unauthenticated catalog read. Returns only published/reserved listings (the storefront-visible set). Carries no bearer token; the store is scoped to the KNL org. Optional filters narrow by fuel/drive kind and sale/rental type; results are paged.
     * @param kind  (optional)
     * @param condition  (optional)
     * @param listingType  (optional)
     * @param limit  (optional, default to 24L)
     * @param offset  (optional, default to 0L)
     * @return SalesListingPage
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun storefrontListListings(kind: ListingKind? = null, condition: ListingCondition? = null, listingType: ListingType? = null, limit: kotlin.Long? = 24L, offset: kotlin.Long? = 0L) : SalesListingPage = withContext(Dispatchers.IO) {
        val localVarResponse = storefrontListListingsWithHttpInfo(kind = kind, condition = condition, listingType = listingType, limit = limit, offset = offset)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as SalesListingPage
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /api/v1/storefront/listings
     * List published sales listings for the public storefront (#6)
     * Public, unauthenticated catalog read. Returns only published/reserved listings (the storefront-visible set). Carries no bearer token; the store is scoped to the KNL org. Optional filters narrow by fuel/drive kind and sale/rental type; results are paged.
     * @param kind  (optional)
     * @param condition  (optional)
     * @param listingType  (optional)
     * @param limit  (optional, default to 24L)
     * @param offset  (optional, default to 0L)
     * @return ApiResponse<SalesListingPage?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun storefrontListListingsWithHttpInfo(kind: ListingKind?, condition: ListingCondition?, listingType: ListingType?, limit: kotlin.Long?, offset: kotlin.Long?) : ApiResponse<SalesListingPage?> = withContext(Dispatchers.IO) {
        val localVariableConfig = storefrontListListingsRequestConfig(kind = kind, condition = condition, listingType = listingType, limit = limit, offset = offset)

        return@withContext request<Unit, SalesListingPage>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation storefrontListListings
     *
     * @param kind  (optional)
     * @param condition  (optional)
     * @param listingType  (optional)
     * @param limit  (optional, default to 24L)
     * @param offset  (optional, default to 0L)
     * @return RequestConfig
     */
    fun storefrontListListingsRequestConfig(kind: ListingKind?, condition: ListingCondition?, listingType: ListingType?, limit: kotlin.Long?, offset: kotlin.Long?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (kind != null) {
                    put("kind", listOf(kind.toString()))
                }
                if (condition != null) {
                    put("condition", listOf(condition.toString()))
                }
                if (listingType != null) {
                    put("listing_type", listOf(listingType.toString()))
                }
                if (limit != null) {
                    put("limit", listOf(limit.toString()))
                }
                if (offset != null) {
                    put("offset", listOf(offset.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/v1/storefront/listings",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * POST /api/v1/storefront/inquiries
     * Submit a public customer inquiry (#6)
     * Public, unauthenticated lead intake. Accepts the customer&#39;s contact details and topic and acknowledges receipt without echoing any field. Generic validation; a bad payload returns 400.
     * @param submitInquiryRequest
     * @return InquiryAck
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun submitInquiry(submitInquiryRequest: SubmitInquiryRequest) : InquiryAck = withContext(Dispatchers.IO) {
        val localVarResponse = submitInquiryWithHttpInfo(submitInquiryRequest = submitInquiryRequest)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as InquiryAck
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /api/v1/storefront/inquiries
     * Submit a public customer inquiry (#6)
     * Public, unauthenticated lead intake. Accepts the customer&#39;s contact details and topic and acknowledges receipt without echoing any field. Generic validation; a bad payload returns 400.
     * @param submitInquiryRequest
     * @return ApiResponse<InquiryAck?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun submitInquiryWithHttpInfo(submitInquiryRequest: SubmitInquiryRequest) : ApiResponse<InquiryAck?> = withContext(Dispatchers.IO) {
        val localVariableConfig = submitInquiryRequestConfig(submitInquiryRequest = submitInquiryRequest)

        return@withContext request<SubmitInquiryRequest, InquiryAck>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation submitInquiry
     *
     * @param submitInquiryRequest
     * @return RequestConfig
     */
    fun submitInquiryRequestConfig(submitInquiryRequest: SubmitInquiryRequest) : RequestConfig<SubmitInquiryRequest> {
        val localVariableBody = submitInquiryRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/v1/storefront/inquiries",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
