from pathlib import Path
import hashlib,json,re,subprocess
ROOT=Path('/private/tmp/console-production-tdd-preparation-20260913');OUT=Path('/private/tmp/retained-0a625d32-independent-fast');HEAD='0a625d323be1184f94af549e20c7f47bfbd63702';PRIOR='59c38d607745e00c8e8e89d9d6e15ed163688aa3'
A=Path('/private/tmp/account-retained-0a625d32');O=Path('/private/tmp/payroll-operation8-0a625d32');W=Path('/private/tmp/workflow-period-0a625d32');sha=lambda b:hashlib.sha256(b).hexdigest()
def git(*args):return subprocess.check_output(['git','-C',str(ROOT),*args])
def keep(name,data):
 p=OUT/name;p.parent.mkdir(parents=True,exist_ok=True);p.write_bytes(data);return {'path':name,'sha256':sha(data)}
def summaries(text):return [tuple([s,*map(int,values)]) for s,*values in re.findall(r'test result: (ok|FAILED)\. (\d+) passed; (\d+) failed; (\d+) ignored; (\d+) measured; (\d+) filtered out;',text)]
records=[];artifacts=[];supervisors=[]
base_env='CARGO_TARGET_DIR=/private/tmp/console-account30-cargo RUSTUP_TOOLCHAIN=1.98.1 RUSTC_WRAPPER= SQLX_OFFLINE=true DOCKER_CONTEXT=colima-console-custody-20260914 '
ident=(A/'probe.log').read_bytes();clean=re.sub(r'\x1b\[[0-9;]*m','',ident.decode());assert summaries(clean)==[('ok',3,0,0,0,0),('ok',3,0,0,0,0)];assert len(re.findall(r'^test \S+ \.\.\. ok$',clean,re.M))==6
artifacts.append(keep('identity-retained.log',ident))
records.append({'scope':'identity-retained-two-targets','source_head':HEAD,'outer_command':base_env+'bash tools/ci/cargo_needs_postgres.sh --only identity-adapter-postgres-user_lifecycle_noop_replay-pg,identity-adapter-postgres-subject-authz-versions-freshness-rls-pg --num-threads 1','command_metadata':'Outer command and head from root; two exact raw Cargo commands and complete case rosters are printed in log.','cargo_commands':re.findall(r'^cargo-postgres: (cargo test .+)$',clean,re.M),'cases':re.findall(r'^test (\S+) \.\.\. ok$',clean,re.M),'invocations':2,'passed':6,'failed':0,'ignored':0,'filtered':[0,0],'tool_exit_root_report':0,'log_sha256':sha(ident)})
metadata=json.loads((A/'auth/results.json').read_text());artifacts.append(keep('auth/results.json',(A/'auth/results.json').read_bytes()));assert len(metadata)==4
expected={'account_root_transition':(10,0,206),'account_custody_startup':(15,0,201),'account_custody_lifecycle':(22,0,194),'account_browser::company_free_registration_me_and_empty_contexts':(0,1,215)}
def supervisor_binding(raw,label):
 text=raw.decode();start=re.search(r'^recovery-fixture run=([^ ]+) evidence=(.+)$',text,re.M);assert start
 evidence=Path(start[2]);head=(evidence/'source-sha.txt').read_text().strip();assert head==HEAD
 exit_match=re.search(r'recovery-fixture evidence=.+ exit=(\d+)\n?$',text);assert exit_match
 keep(f'supervisor/{label}/source-sha.txt',(evidence/'source-sha.txt').read_bytes());keep(f'supervisor/{label}/test.log',(evidence/'test.log').read_bytes())
 return {'run_id':start[1],'evidence_path':str(evidence),'source_sha':head,'exit':int(exit_match[1]),'source_sha_file_sha256':sha((evidence/'source-sha.txt').read_bytes()),'test_log_sha256':sha((evidence/'test.log').read_bytes())}
for r in metadata:
 name=r['name'];passed,failed,filtered=expected[name];filename=name.replace('::','-')+'.log';raw=(A/'auth'/filename).read_bytes();text=raw.decode();assert r['sha']==HEAD and sha(raw)==r['log_sha256']
 assert summaries(text)==[('FAILED' if failed else 'ok',passed,failed,0,0,filtered)]
 binding=supervisor_binding(raw,name.replace('::','-'));assert binding['exit']==r['exit']==(101 if failed else 0)
 roster=re.findall(r'^test (\S+) \.\.\. ok$',text,re.M)
 if failed:
  assert 'panicked at app/tests/auth_rest.rs:4034:13:' in text and 'left: 404\n right: 200' in text and text.count('panicked at')==1
  roster=[name]
 else:assert len(roster)==passed and all(n.startswith(name+'::') for n in roster)
 artifacts.append(keep('auth/'+filename,raw));records.append({'scope':name,'source_head':HEAD,'command':r['command'],'cases':roster,'invocations':1,'passed':passed,'failed':failed,'ignored':0,'filtered':[filtered],'exit':r['exit'],'log_sha256':sha(raw),'supervisor':binding})
for label,directory,name,passed,filtered,tail in [
('operation',O,'durability_composition_tests::required_workflow_provenance_refusal_is_operation_not_unknown',1,30,'-p console-app --lib --features test-recovery durability_composition_tests::required_workflow_provenance_refusal_is_operation_not_unknown -- --exact --test-threads=1 --nocapture'),
('period',W,'payroll_drain_period_lock',2,0,'-p console-workflow-runtime-adapter-postgres --test payroll_drain_period_lock -- --test-threads=1 --nocapture')]:
 raw=(directory/'probe.log').read_bytes();text=raw.decode();assert summaries(text)==[('ok',passed,0,0,0,filtered)]
 binding=supervisor_binding(raw,label);assert binding['exit']==0
 if label=='operation':assert f'test {name} ...' in text;roster=[name]
 else:roster=re.findall(r'^test (\S+) \.\.\. ok$',text,re.M);assert roster==['a_lock_acquired_after_the_read_gate_still_blocks_the_staging_write','payroll_period_lock_blocks_draft_creation_and_unlock_restores']
 artifacts.append(keep(label+'/probe.log',raw));records.append({'scope':label,'source_head':HEAD,'command':base_env+'CONSOLE_RECOVERY_CUT= python3 tools/lanes/recovery/supervise_recovery.py /private/tmp/console-production-tdd-preparation-20260913 -- cargo test --locked --manifest-path backend/Cargo.toml '+tail,'command_metadata':'Root exact command report; independently checked source-sha and raw case/exit records.','cases':roster,'invocations':1,'passed':passed,'failed':0,'ignored':0,'filtered':[filtered],'exit':0,'log_sha256':sha(raw),'supervisor':binding})
paths=['backend/app/tests/auth_rest.rs','backend/app/tests/auth_rest/account_root_transition.rs','backend/app/tests/auth_rest/account_custody_startup.rs','backend/app/tests/auth_rest/account_custody_lifecycle.rs','backend/crates/identity/adapter-postgres/tests/subject_authz_versions_freshness_rls.rs','backend/crates/identity/adapter-postgres/tests/user_lifecycle_noop_replay.rs','backend/crates/identity/adapter-postgres/src/lib.rs','backend/app/src/durability_composition_tests.rs','backend/app/src/lib.rs','backend/app/src/workflow_drain.rs','backend/crates/payroll/adapter-postgres/src/pay_run.rs','backend/crates/workflow/adapter-postgres/src/lib.rs','backend/crates/workflow/adapter-postgres/tests/payroll_drain_period_lock.rs','backend/crates/workflow/domain/src/lib.rs','ops/postgres-finalize-account-custody.sql','backend/app/src/account_custody_state.sql','backend/crates/platform/test-support/src/lib.rs','backend/crates/platform/auth-rest/src/lib.rs','backend/crates/platform/auth-rest/src/terms.rs']
bindings=[]
for path in paths:
 data=git('show',f'{HEAD}:{path}');prior=git('show',f'{PRIOR}:{path}');assert (ROOT/path).read_bytes()==data
 mode,kind,blob=git('ls-tree',HEAD,'--',path).decode().split('\t')[0].split();assert kind=='blob' and mode in ['100644','100755'];keep('sources/'+path,data)
 bindings.append({'path':path,'head_git_blob':blob,'sha256':sha(data),'same_as_59c38':data==prior})
assert sha(git('show',f'{HEAD}:backend/app/src/durability_composition_tests.rs'))=='0f02b3aec6f15449015b22a54b70453b66f2a5d17fb7670f3a241cce53b2a7cb'
for path in ['backend/crates/identity/adapter-postgres/tests/subject_authz_versions_freshness_rls.rs','backend/crates/identity/adapter-postgres/tests/user_lifecycle_noop_replay.rs']:
 now=git('show',f'{HEAD}:{path}').decode();old=git('show',f'{PRIOR}:{path}').decode()
 assert now.count('    prepare_account_test_database(&owner_pool).await;\n')==3
 restored=now.replace('use console_platform_test_support::prepare_account_test_database;\n','').replace('    prepare_account_test_database(&owner_pool).await;\n','').replace('#[sqlx::test(migrations = false)]','#[sqlx::test(migrations = "../../platform/db/migrations")]');assert restored==old
counts={'saved_cargo_test_invocations':sum(r['invocations'] for r in records),'executed':sum(r['passed']+r['failed'] for r in records),'passed':sum(r['passed'] for r in records),'failed':sum(r['failed'] for r in records),'ignored':sum(r['ignored'] for r in records),'source_bindings':len(bindings),'new_cargo_invocations_by_reviewer':0,'new_database_commands_by_reviewer':0,'shared_repository_writes':0};assert counts['executed']==57 and counts['passed']==56 and counts['failed']==1
report={'reviewer':'/root/fast_gate_review','review_identity':'Independent saved runtime classification; authored separate Operation control, which Capture independently source-approved before root execution.','head_sha':HEAD,'verdict':'APPROVE_RETAINED56_PASS_AND_PRESERVE_NATIVE_REGISTRATION_FIRST_FAILURE','counts':counts,'runs':records,'source_bindings':bindings,'artifacts':artifacts,
'conclusions':[
'Identity retained2x3 cases pass unchanged business assertions after the exact real finalization setup amendment: subject versions, tenant isolation, preview receipt scope, activation/deactivation replay audit behavior and legacy racing-credential revocation. Removing only helper import,3 setup calls and the migration-attribute substitutions restores59c38 source byte-for-byte.',
'Account root transition10, startup15 and lifecycle22 case rosters pass. Their test sources are unchanged from59c38, now exercised with0a625 finalizer/state sources. This is47 selected cases: native root/FK/bridge/profile and rollback, actual API/Worker startup/readiness, historical upgrade, finalizer lifecycle/drift/refusal; readiness detection does not prove every running consumer stops.',
'Actual App Operation control passes exact ordinary provenance refusal telemetry, no correlated unknown, completed drainer pass and exact observed owner/standby workflow snapshot preservation. It remains1 executed case with30filtered, not the full App8 suite.',
'Both actual period-lock tests pass using the typed staging interface: existing locked-window refusal/unlock recovery and a lock introduced after the workflow read gate but before owner staging. The compatibility wrapper source is unchanged from59c38; no runtime stage fake or weakened business assertion was added by this review.'
],
'native_registration':{'status':'RED_FIRST_HTTP_CONTRACT_FAILURE; deeper native acceptance not established','raw_fact':'Exactly1 selected case executes and fails at app/tests/auth_rest.rs:4034:13, Response::json shared helper: HTTP404 versus expected200. Supervisor exits101;0ignored,215filtered. This is a real application HTTP status mismatch, not a compile failure or missing-test count.','source_inference':'The test calls start at auth_rest.rs4518, which POSTs /api/v2/auth/registration/start. The actual auth router registers v2 terms endpoints and v1 passkey registration only (platform/auth-rest/src/lib.rs330–337); no v2 native registration handler is present in inspected routing. This strongly supports the unimplemented native registration path as the cause.','observability_limit':'Raw panic does not print the request URI and the same json helper also checks terms/me/contexts. Do not describe an HTTP trace or certify preceding public terms/artifact checks from this log alone.','unreached_or_unproved':['Native registration start response and its pending Account/cookie invariants','WebAuthn registration completion and immutable terms acceptance','Native session credentials and account projection','GET /api/v2/accounts/me and empty contexts contract','Final no-Company/Employee/Person creation and end-to-end native enrollment'], 'attribution':'Relevant auth_rest test, app router and auth-rest routing sources are unchanged from59c38. This record does not establish a regression caused by Account14, admit a new implementation lane, or clear native enrollment HOLD.'},
'limits':['Source-sha files independently bind each supervised run to0a625; they are narrower custody evidence than the Account14 driver1005-file pre/post closure. Root metadata supplies non-logged command/env details.','This receipt covers8 saved Cargo test invocations, not final CI18 or whole auth216. No skipped/filtered case is counted as executed.','No full binary provenance or production replication-durability claim follows from these selective fixtures; prior stale-build evidence remains retained separately.','Final-head CI/import/aggregate verification, native enrollment, legal/compliance/payment/production authority remain separate.'],
'pending':'Inventory curated evidence allowlist review when frozen; root final runtime17 remains separate.',
'lenses':['Cartesian doubt','Essentialism / YAGNI','Red Team','Operability / Day-2','Blast-radius / cell-based','Zero-trust / defense-in-depth']}
(OUT/'review.json').write_text(json.dumps(report,indent=2)+'\n');files={str(p.relative_to(OUT)):sha(p.read_bytes()) for p in OUT.rglob('*') if p.is_file() and p.name!='manifest.json'};(OUT/'manifest.json').write_text(json.dumps({'head_sha':HEAD,'files':files},indent=2)+'\n')
print(json.dumps({'review_sha256':sha((OUT/'review.json').read_bytes()),'manifest_sha256':sha((OUT/'manifest.json').read_bytes()),'counts':counts},indent=2))
